#start|Balance 84 Yen

@Ichinari
"...I'm so hungry."

I mumble to myself, clutching my stomach as it gurgles pitifully.

@Ichinari
"I haven't eaten since yesterday..."

I open the fridge.

Empty.

Except for a couple bottles of condiments\: mayonnaise and soy sauce.

@Ichinari
"Last time I drank soy sauce, it gave me such a banging headache I thought I was gonna die..."

When I'd searched online, I'd found that excessive consumption of soy sauce can apparently lead to death from salt poisoning.

Soy sauce sure is super salty...

@Ichinari
"Let's check my bank balance..."

I open my bank book.

84 yen.

@Ichinari
"Not like it's magically gonna have changed."

I mumble again, and close the bank book. Then I check the calendar on my computer.

@Ichinari
"Two days until I get paid for the latest manuscript I submitted."

Then my bank balance will increase by a factor of 1500. Still not a lot of money though.

With 84 yen I can buy a quarter of a cabbage...

This is the reality of Ichinari Tsuzurigi, failing hentai manga artist.

By the way my pen name is "Ichineri," which was created by simply altering one letter of my real name.

@Ichinari
"Haa... This sucks..."

I put down my stylus and flop back onto my futon.

@Ichinari
"It's a hard knock life for an unpopular manga artist..."

I stare up at the cracked ceiling of my run-down apartment. This place was built 60 years ago, and costs me 20,000 yen per month.

Three years ago, I won a prize from a little-known magazine right before finishing high school. After graduating, I'd moved to Tokyo to chase my dream.

Now I'm 21 and barely scraping by, relegated to a serialization in a hentai manga magazine.

@Ichinari
"I'm soooo hungry."

The miserable noises from my stomach are only serving to remind it of its own emptiness.

@Ichinari
"Actually, now that I think about it..."

@Ichinari
"I remember I won something sweet with that lottery ticket I found the other day. I'm sure I put it in that drawer!"

@Ichinari
"...Found it!"

@Ichinari
"Om nom nom nom."

@Ichinari
"URGH, BLARGH, BLUUUUURGH!"

I immediately throw it right back up.

@Akira/？？？
"Ah! Oh dear, Ichi!"

@Akira/？？？
"Were you eating tissues again?!"

@Akira/？？？
"I've told you before, haven't I?! Tissues aren't food!"

@Ichinari
"Urgh... A-Akira-chan!"

@Akira
"Here, I'll rub your back for you."

@Akira
"Keep retching until you feel better. Go on, get it all out!"

Her small hand rubs my back comfortingly.

@Akira
"Here, I brought you something to drink, so have a sip."

@Akira
"Take it nice and slow, okay? Can you manage it?"

@Ichinari
"Urgh... I really owe you, Akira-chan!"

I down the entire bottle of sports drink Akira-chan hands me in one go.

Aah, so sweet! The exquisite tinge of salt in the midst of the sweetness is rejuvenating my stomach...!

I find myself moved to tears.

@Akira
"Honestly, Ichi, you're such a silly boy."

@Akira
"But I suppose this is just how you are."

@Akira
"And I can't just leave my silly Ichi to fend for himself. Hehe."

She smiles at me.

This is Akira Higashibojo.

Otherwise known to me as Akira-chan.

She's 23 years old and has been in charge of me ever since she started working as an editor two years ago.

She may look cute and petite, but she actually used to be a judo athlete. She even won a championship in college.

She indulges and spoils me all the time. Sometimes she even buys me food from her own pocket. She really is my angel.

@Akira
"Ichi? C'mere."

Akira-chan plops herself down on my futon.

@Akira
"If you push yourself too hard, you'll make yourself sick."

@Akira
"Why don't you have a little lie down?"

She pats her thighs and opens her arms to me.

@Ichinari
"Akira-chaaaaaaaan!"

@Akira
"There there, there there♪"

@Akira
"Life's been hard on you, hasn't it?"

@Akira
"You don't have to worry anymore, Onee-chan is here♪ There there♪"

I rest my head on her silky soft thighs.

She pets my head comfortingly.

@Ichinari
"Haa~"

@Ichinari
"Ahh, I'm being healed by the power of Akira-chan~"

My parched and dried up soul is being nourished with cool, blessed water.

I feel like tears, drool, and other mysterious liquids are about to come overflowing out of me.

@Akira
"Yep, yep. Are you okay now?"

@Akira
"You should have called me before you got yourself into this state."

@Ichinari
"Ugh, Akira-chan..."

@Ichinari
"I'm sorry. I'm really, really sorry."

@Akira
"No need for apologies♪"

@Akira
"As long as you're okay, that's all that matters."

@Akira
"It's only right that an onee-chan looks out for the little guy."

@Akira
"Anyway, why don't you let yourself relax a bit more?"

@Akira
"Take a deeeep breath and let those worries fade away."

@Akira
"That's it. Relaaaax♪"

Stroking my head soothingly, she comforts me with a sweet and gentle voice.

I can feel myself growing calmer with every breath...

@Akira
"Sorry I couldn't come over yesterday."

@Akira
"It's my failure as your editor that's put you in such an awful position."

@Akira
"I'll make sure to pop by more often from now on."

@Ichinari
"No, you've already done plenty for me."

@Ichinari
"I'm sorry for always relying on you."

@Akira
"No, that's not how it is."

@Akira
"I love that you're always trying your best."

@Akira
"And I'd prefer it if you just came straight to me when you're struggling, okay?"

@Akira
"I may be your editor, but I'm also your onee-chan, Ichi."

@Akira
"It doesn't matter if you're a complete flop, so long as you keep trying♪"

My soul is being cleansed by Akira-chan's motherly pampering.

It hurts a bit when she refers to me as a complete flop, but I can just take it as another aspect of her maternal affection.

Although Akira-chan isn't my mom, but more like my big sis.

I give myself up to her coddling.

@Akira
"If worst comes to worst, I'll provide for you."

@Akira
"So don't worry. Even if he faces death, a true man does so head-on♪"

It’s obvious that judo has shaped her personality. She's quite spartan in her approach to her artists.

She's probably the strongest woman in the hentai manga editing world.

...Probably wins in the boob department, too.

Yeah, I reckon she's a black belt there, too. The Akira Peaks offer a truly spectacular view.

@Akira
"Oh! Naughty Ichi, you're peeking at my boobs again, aren't you?"

@Akira
"You can't gawp at girls' breasts so obviously, you know?"

@Ichinari
"No, I wasn't looking."

@Akira
"Yes you were."

@Ichinari
"No I wasn't."

@Akira
"Why're you lying to me, Ichi?"

@Akira
"Aren't I always telling you there are two things I hate\: manga artists who can't meet deadlines, and liars."

@Ichinari
"Ow, ow, ow, ow! My hair, my hair, you're ripping it out!"

@Ichinari
"I know you have a grip strength of 60 kg, so please stop the ironclaw, I'm sorry, Onee-chan, I'm sorry for lying to youuuuu!"

@Akira
"Mm, I like it when you're nice and obedient♪"

@Akira
"Humans can flourish anywhere, so long as they're meek and sincere♪"

@Ichinari
"As you please, Onee-sama."

Her judo grip is so overpowered, I swear I heard my skull plates creaking!

Her Killer Onee-chan Claw is not to be messed with.

If I push things too far, this is what happens.

Although the contrast between these two sides of her personality is pretty cute in its own right.

@Akira
"But you're a healthy young man, Ichi. You can't help yourself."

@Akira
"And I'm an onee-chan who toootally understands that♪"

@Akira
"So don't worry, I'm not going to get mad at you over something like that, okay? Tee hee~♪"

@Akira
"If you ever get to the point where you've worked your very hardest yet still find yourself at a loss, I'll marry you and make you a kept man."

@Akira
"So don't worry. Let's do our best together, until you're happy with yourself."

@Akira
"I'll give it my all, too, as your editor."

@Ichinari
"Akira-chan..."

There's a lump in my throat.

Akira-chan really is the best editor a guy could ask for.

She's cute, she's got big boobs, she pampers me...

But, more than any of that, I'm grateful for this straightforwardness of hers.

I feel charged up just from being around her!

Which is why...

@Ichinari
"I'll achieve what I set out to..."

@Ichinari
"...and it'll be thanks to you, Akira-chan."

@Akira
"Yep. I'm looking forward to it."

@Akira
"I believe in you, Ichi. I'm your number one supporter. Hee hee!"

She sounds just a little embarrassed as she continues stroking my head, ever so gently.

Success is still so far away I can't even see it...

But, as an artist, this is all I can do to repay her.

Until I finally have results that I can be proud of...

As these thoughts run through my head, I give myself up to Akira-chan's gentle ministrations.

@Akira
"Alright, that's enough Mrs. Nice Guy for now!"

@Akira
"Time to get up and get to work!"

@Akira
"Have you finished the storyboard for your latest piece?"

@Ichinari
"Indeed I have, Onee-sama."

I hold out the storyboard I've already finished.

@Akira
"Oh, you've done a really good job on this!"

@Akira
"Well done! Onee-chan is reaaaally impressed♪"

@Akira
"Now, let's have a look, shall we?"

I hand her the sheaf of papers.

@Akira
"Hmm? So this one's big sister x little brother? Hmm~?"

@Akira
"Mm-hmm."

@Akira
"Mm-hmm... Mm-hmm."

@Akira
"Yep... Hmm~"

@Akira
"Hmm~ Hmmmmmm~"

Akira-chan's face is flushing redder and redder, and she glances at me awkwardly.

@Ichinari
"What do you think, Akira-chan?"

@Akira
"I-I think it's pretty good."

@Akira
"This one's, um...pretty strong on the sex...isn't it?"

@Akira
"It's like, it just jumps right into it..."

@Akira
"Oh, but that's a really good thing, you know?! I mean, this is a hentai manga, after all!"

@Akira
"A-Anyway, I'll take this with me and run it past the editor-in-chief​."

Still red in the face, she stows my storyboard away in her bag.

Not exactly the reaction you'd expect, given the "dependable older sister" vibe she's usually going for.

Seriously, she's freakin' adorable.

@Akira
"Oh! R-Right!"

@Akira
"You must be starving, Ichi!"

@Akira
"I'll go buy you something from the convenience store!"

@Akira
"I'll be right back, so be a good boy and wait here, okay?"

@Akira
"And no more snacking on tissues. Understand?"

@Akira
"Okay, be right back!"

@Ichinari
"Akira-chan really is my angel..."

I smirk to myself as I think back on her blushing face.

Akira-chan's bashful face while reading my drafts is the most adorable thing in the world.

I'm so glad Akira-chan is my editor. Let's give it up for sanctioned sexual harassment!

At first I was pretty embarrassed having her see my sexual fantasies right there on the page, but now that part is my reward for my hard work.

@"Black Cat"
"Meow~"

@Ichinari
"Hm?"

I turn toward the sound of a cat's mewling.

There's a black cat pawing at my window.

@Ichinari
"Oh, hey, Blackie."

I open the window for her as usual. She comes into the room and immediately hops up onto my lap.

@Ichinari
"Sorry, Blackie, but I don't have anything for you today."

@Ichinari
"Akira-chan'll be back soon though."

@Ichinari
"And then we'll get her to rustle something up for you too."

@"Black Cat"
"Meow!"

This is Blackie, the black cat.

She's been my buddy since I arrived at this apartment.

It was a rainy day just after I'd moved in.

I'd let a sodden, shivering Blackie into my room, and since then she's been coming by frequently to play.

I even feed her and brush her.

To be honest, she's my only friend right now. Since moving to the big city, I've devoted myself entirely to my work.

I scratch Blackie's chin as I reassure myself with excuses.

@Ichinari
"Must be nice, living a carefree life like you do."

@Ichinari
"I was acting tough in front of Akira-chan, but honestly, I'm really not doing so great."

@"Black Cat"
"Purr, purr, purr~"

She nuzzles up against me, purring deep in her throat.

If I'm being honest, I've been going nowhere for three years now.

I've studied and practiced as much as possible, yet all I have to show for it is 84 yen in my bank account.

@Ichinari
"But it's been my dream since I was in elementary school..."

I let out a long, deep sigh. Then I pick up a battered and tattered volume of manga.

It's the manga that made me want to become a manga artist myself.

I've already read and re-read it a thousand times before, but I open it again.

"The worst thing you can do is not believe in yourself."

@Ichinari
"Noraemon spits some real truths."

My eyes linger on the famous line.

I wish I could draw a manga like this, something that can inspire the people who read it.

So far I've kept going based on those feelings alone, but...

@Ichinari
"When I was a kid, I thought I could do anything. But real life is hard."

The reality is that I'm a struggling hentai manga artist who's always just one step away from complete failure.

Drawing hentai is fun enough, and I do enjoy it. It may be a bit of a back-alley industry, but it's still manga.

It provides me with valuable experience and an income. There are also artists who've honed their skills in this industry before breaking into the mainstream.

So it's not like I'm dissatisfied with the work I'm doing right now. In fact, if we're going by job title alone, you could say I've achieved my dream. However...

@Ichinari
"...An unpopular manga artists may as well be unemployed."

The sales of my first commercially published manga volume have been uninspiring, and I have only 300 followers on my 3-year-old Dwitter account.

@Ichinari
"Plus half of them are just spam bots..."

Why are so many of my followers "looking for sex"?

Or those accounts that say they'll send nudes?

Looking over my followers list is kinda depressing. I move on and scroll down my timeline.

@Ichinari
"Hm? This article..."

I stop on a particular Dweet.

"Black Cats\: Symbols of Good Fortune and Familiars to the Gods."

@Ichinari
"Huh, so you're actually kind of a big deal, are you?"

@"Black Cat"
"Mew."

She meows disinterestedly as I continue petting her. My curiosity somewhat piqued, I cast my eyes over the article.

@Ichinari
"Hmm, what does this say..."

@Ichinari
"Black cats are a symbol of good fortune and act as familiars to the gods..."

@Ichinari
"Hmm."

I knew of some negative superstitions associated with black cats, but it's interesting to see a positive perspective like this.

@Ichinari
"Hey, Blackie?"

@Ichinari
"Does this mean you're good pals with the gods?"

@Ichinari
"Since we're friends and everything, do you think you could pass on a message for me?"

@"Black Cat"
"Meow!"

@Ichinari
"Oho, I see, I see, so you'll hear out my wish?"

@Ichinari
"Well, I guess I wish to be able to continue being a manga artist..."

@Ichinari
"...and to find happiness...?"

I clap my hands together to finish off the prayer.

@"Black Cat"
"Yaaaawn~"

Blackie opens her mouth wide in a huge yawn before jumping off my lap.

She deftly uses her front paws to slide the window open, then leaps out.

@Ichinari
"Even the cats are fed up of me, huh?"

I really must be at the end of my tether if I'm praying to some vague gods.

It's not like I'm even religious. It's no wonder Blackie's had enough.

I flop back onto my futon again.

@Akira
"I'm baaack! Onee-chan is hooome!"

@Akira
"Were you a good boy? You didn't get up to any mischief? Didn't eat anything weird?"

@Ichinari
"Meow."

@Akira
"Good answer! *pet pet pet*♪"

@Akira
"C'mon, let's hear a nice purr from you♪ Purr, purr~♪"

@Ichinari
"Purr, purr, purr~"

I let my master fawn over me.

Life as a pet could be pretty nice. I think having an owner like Akira-chan means I win at life. Yep.

I lean into Akira-chan's touch.

@Akira
"I picked up a bento at the store, do you want it?"

@Akira
"Ta-da! A nice meaty bento for Ichi!"

@Akira
"This'll give you energy! Gotta keep your strength up!"

@Ichinari
"Uh, Akira-chan, you're spilling it."

@Akira
"Gaaah! I've got meat juice all over my shirt!"

@Akira
"This is my last shirt! They make me work so much overtime I don't have time for laundry! Gyaaaah!"

@Ichinari
"Um..."

@Ichinari
"Should I suck it out before it stains?"

@Akira
"Silly Ichi! Get your mind out of the gutter!"

@Akira
"If sucking it would get it out, I'd already have your mouth on it!"

@Ichinari
"Oh, right."

She'd considered that option already, huh. Akira-chan must be feeling run down too, working such long hours.

For now, I do what I can by offering her one of my precious tissues.

@Ichinari
"Uh, your cellphone is ringin—"

@Akira
"Yes, this is Higashibojo!"

@Akira
"Yes! I'm meeting with Ichi— Excuse me, Tsuzurigi-sensei!"

@Akira
"Yes! The storyboard is perfect! This one is big sister x little brother! You got it!"

@Ichinari
"She's a real corporate slave now, huh."

I watch Akira-chan bowing furiously at the wall as she talks on the phone.

The female editor-in-chief she works for is super scary.

She's always shouting at Akira-chan for her scatterbrained ways.

My eyes prickle hotly as I watch her, still bobbing up and down at the wall.

I've gotta try my best so that at least the editor-in-chief won't get mad at Akira-chan because of me.

@Akira
"Sorry about that! I'm done now."

@Akira
"Now, Ichi."

@Ichinari
"Yes! What is it, Akira-chan?!"

I salute her smartly.

If Akira-chan has to be a corporate slave, then I'll be an Onee-chan slave.

Her training is paying off. All hail Onee-chan!

@Akira
"You know the artist Ishitaka-sensei?"

@Ichinari
"Ishitaka-sensei..."

@Ichinari
"...is your company's most famous artist, right?"

@Akira
"Right, right. You two made your debut at the same time, but Ishitaka-sensei is now our cover artist."

@Ichinari
"Ouch. Right where it hurts."

She holds nothing back, stabbing a nail right into my most sensitive spot.

@Akira
"And Ishitaka-sensei's newest manga is selling like crazy, too."

@Akira
"It's already on the third print run, and it's stayed at number one on our sales chart since release."

@Ichinari
"I know you couldn't even sell out my first run. I'm really sorry..."

She hammers the nail in even harder.

Well, I own a copy of Ishitaka-sensei's latest work myself.

Anyway, if you're working in this industry, there's no way you haven't heard of Ishitaka-sensei.

@Ichinari
"So, what about the great Ishitaka-sensei?"

@Akira
"It seems we're gonna be publishing even more of Ishitaka-sensei's work, so we're urgently seeking an assistant to help out."

@Akira
"Even though Ishitaka-sensei was always against the idea of using an assistant before..."

@Akira
"As a pro, you only have so much time, so sometimes you don't have a choice. That's just how it goes."

She folds her arms and nods knowingly.

If you're only publishing one volume per month, it's normal to handle it all yourself.

But if you're talking multiple volumes per month while also publishing in weekly magazines, it's normal to hire several assistants.

Although that's predicated on the condition that you're selling enough copies to be able to hire that many people.

@Ichinari
"So, what, you're saying I should do it?"

@Akira
"Yeeees, exactly!"

@Ichinari
"Nope, nope, nope, absolutely not!"

@Ichinari
"That's not work for an underling like me!"

@Ichinari
"There's gotta be tons of more qualified, professional assistants out there!"

@Akira
"Yeah, and they're all way busier than an artist whose work isn't selling."

@Ichinari
"Ow, got me again."

It's the third arrow sent right into my heart.

All these bullseyes are gonna knock me over.

I mean, I know it's all 100% true, but still...

@Ichinari
"Of course, I'm really grateful you'd think of me, you know?"

@Ichinari
"But I guess I just don't think I'd be up to the task?"

@Ichinari
"If my work was torn to shreds by one of my contemporaries, and one of the most popular artists of the moment..."

@Ichinari
"...I'm pretty sure I'd never recover."

@Akira
"Hmm, but surely you're already past that stage? I mean, you two are worlds apart."

@Ichinari
"Ouch. I can't take much more of this. Seriously, you're killing me."

Now she's just kicking me when I'm already down.

And I have absolutely no comebacks. I'm dying here. For real.

@Akira
"But you know, the editor-in-chief, she said..."

@Akira
"'Tsuzurigi's not even that bad. There are just some artists who don't make it.'"

@Akira
"'His art itself is fine—good, even—but it's like it lacks impact or a real presence or something.'"

@Akira
"So I'm sure you'll be fine! Probably!"

@Ichinari
"That doesn't sound like she has any confidence in me at all."

It sounded like criticism for the most part, or like she's on the verge of giving up on me for good.

In fact, the editor-in-chief's words might be the most painful shot fired yet.

@Akira
"You're so negative, Ichi. You've gotta live your life with more optimism!"

@Akira
"If she really thought you weren't worth it, she wouldn't have given you a serialization, would she?"

@Akira
"It's the editor-in-chief herself who selects which works go in the magazine."

@Ichinari
"Well, I suppose..."

She's already given me a good enough chance in letting me publish a whole tankōbon volume.

It's my own fault that I couldn't turn that opportunity into something more.

And yet Akira-chan's saying she still hasn't given up hope on me...

I may be on the brink, but I suppose I can buy it.

@Akira
"Plus, you'll be able to watch a master at work."

@Akira
"That's a valuable experience that money can't buy."

@Akira
"And you might pick up some tips to get you out of this rut."

@Ichinari
"Akira-chan..."

@Ichinari
"But, you know..."

@Akira
"Oh, and the pay is way better than what you get for your work now."

@Ichinari
"I would be absolutely honored to have this opportunity!"

I bow my head to her so fast it almost snaps off.

@Akira
"Okie dokie♪ I'll let the editor-in-chief know your answer!"

@Akira
"Just wait a minute while I make a call."

@Akira
"Hello, this is Higashibojo!"

@Akira
"Could you put me on with the editor-in-chief? Thanks!"

Akira-chan starts bowing into thin air again as she makes the call.

@Ichinari
"Ishitaka-sensei's assistant, huh?"

I'd quickly given in when talk of money came into the equation, but...

Until now, I've never had a chance to really study under anyone.

Getting paid sure is appealing, but, more than that, this'll be a great opportunity to learn.

I pick up one of the copies of the hentai magazine my work is printed in.

The cover art is incredibly sexy, yet still cute. And the name ISHITAKA is splashed across it in big letters.

Flipping past the cover, Ishitaka-sensei's work greets me in full color on the first page.

@Ichinari
"This is really good stuff..."

The illustrations and the composition both ooze sex appeal. It's got that special "something" that keeps your eyes glued to the page.

If I'm being honest, Ishitaka-sensei has been my secret idol.

We debuted at the same time, but the success Ishitaka-sensei has achieved is incredible—I have to respect that.

Honestly, someone like me can never even compare to Ishitaka-sensei...

@Ichinari
"She's right about it being an experience money can't buy."

Plus...

@Ichinari
"Being around Ishitaka-sensei might give me just the kick in the ass I need."

Over the last three years I've lost sight of my goals and stagnated.

If I can't find a way to grow from this experience, then that's when I'll—

I close the magazine, my mind made up.

@Akira
"We're good to go, Ichi!"

@Akira
"Okay, let's go get you introduced♪"

@Ichinari
"..."

@Ichinari
"Huh? Right now?"

@Ichinari
"Isn't this all moving a bit fast?"

@Akira
"I already told you, it was an urgent request."

@Ichinari
"No, I know that, but..."

@Ichinari
"I'm shy, so I like, need time to prepare myself...?"

It's so sudden! I'm breaking out in a cold sweat.

My newfound resolve is already slipping away from me.

@Akira
"What're you blabbering about? Stop being such a loser, Ichi!"

@Akira
"You've gotta sink your teeth into every chance you get!"

@Akira
"When the pedal's to the metal, having guts is what counts the most! Say it back to me!"

@Ichinari
"No, I mean, I get what you're saying..."

@Ichinari
"But I haven't showered today, and the gas has been off since yesterday."

@Ichinari
"You know, Akira-chan, that offer of marriage is starting to sound real good."

@Ichinari
"When shall we have the ceremony?"

@Akira
"Shut it, brat!"

@Akira
"Trying to get me to marry you for such a reason—my head might allow it but my heart sure won't!"

@Akira
"If you have water, you can shower!"

@Akira
"I'll pick your bones up from the battlefield if it comes to it, so show me your fighting spirit! Move it! Oorah!"

@Ichinari
"As you command, Onee-sama!"

She is, at her heart, a spartan commander.

@Ichinari
"So this is where the Ishitaka-sensei magic happens, huh?"

I look up at the office blocks surrounding Yokohama Station.

This is my local station, too, but my place is on the old, residential side of town.

You can't even compare it to this hip new business area.

Even the passersby seem to have a different aura to them.

@Akira
"It's close to the company, so it's a convenient location."

@Akira
"Ishitaka-sensei's super shy, so we never have meetings at the company office—I always have to come here."

@Ichinari
"Life's pretty different for the big shots, huh."

I don't even have meetings. I'm sinking into despair here.

@Ichinari
"If Ishitaka-sensei's so shy, is it okay for me to just show up out of the blue?"

@Akira
"That's why I'm here with you."

@Akira
"I mean, Ishitaka-sensei doesn't usually allow men over at all."

@Akira
"But it seems the editor-in-chief recommended you since it's a real emergency."

@Akira
"'Tsuzurigi's a real loser so he's completely harmless. Plus he's got plenty of time on his hands.'"

@Akira
"Or so she said."

@Ichinari
"THOSE are her reasons for recommending me?"

Even the editorial department officially acknowledges me as a loser and a total flop.

I can't believe that's how they see me... Although what they're saying is true, so I can hardly argue with it.

As I'm gritting my teeth over this, I notice something strange about what Akira-chan just said.

@Ichinari
"Huh?"

@Ichinari
"Why no men?"

@Ichinari
"When you get that successful do you just refuse to work unless you have a harem around you?"

@Akira
"Don't be silly!"

@Akira
"Ishitaka-sensei's a woman. She just hates men."

@Ichinari
"What? A woman?! How old is she?"

@Akira
"Around same age as you, I think?"

@Ichinari
"...Are you kidding me?"

Not only did we enter the industry at the same time, but Ishitaka-sensei is a girl the same age as me...

...And yet there's a whole world between us. So this is what people call a genius, huh.

I stare up at the sky high above me.

I've wanted to be a manga artist ever since I was in elementary school.

But even back then, there was that kid who lived next door who was really good at drawing.

And there was the girl in manga club with me who improved dramatically before my eyes.

Right. I'm not the only person in the world who works hard.

Rather than getting down on myself, I stare up at the towering buildings with a renewed sense of purpose.

@Akira
"*staaare*"

@Akira
"Ichi, you've got a pervy look in your eyes. You're oogling and ogling."

@Akira
"And just 'cause you heard Ishitaka-sensei's a young woman. Gross!"

@Ichinari
"Er, actually I was feeling really sentimental just now."

@Akira
"Honestly, ew. This is exactly why she doesn't want boys around."

@Akira
"There are all these egotistical guys out there who won't touch a computer or a woman unless it's brand shiny new."

@Akira
"They get like this the moment they see a sweet young thing."

Akira-chan shrugs and shakes her head.

She seems really down on herself all of a sudden...

I wonder if there are shitty guys at her company who say stuff like that?

I think 23 is still pretty damn young. I don't understand the complex some women have about their ages.

I try to console Akira-chan.

@Ichinari
"Don't you listen to the shitty guys who say crap like that."

@Ichinari
"Most men don't think that way."

@Ichinari
"Plus you're a stunner, regardless of your age."

@Akira
"Ichi..."

@Akira
"Wh-What's this? Are you trying to butter me up?♪"

@Akira
"Onee-chan doesn't know what to do with sudden compliments like that♪"

@Akira
"Are you trying to slay the onee-chan?♪ You little tyke, you♪"

@Ichinari
"Ow! Oww!"

@Ichinari
"You don't know your own strength, Onee-chan!"

Her finger pokes are almost powerful enough to floor me.

@Akira
"Oh, but do be careful, okay?"

@Akira
"If Ishitaka-sensei tells me she doesn't like the pervy way you're looking at her..."

@Akira
"...you'll never work with our magazine again. Got it?"

@Ichinari
"I will be absolutely, 120% careful."

You don't wanna get on the wrong side of a big shot artist.

Although it's not like I'd ever sexually harass someone, regardless.

I was honestly just feeling emotional earlier, but she'd interpreted the glisten in my eye as pervy.

All right, I need to be vigilant as the dudes on packed trains holding their hands up in the air. Absolutely nothing that could be perceived as sexual harassment.

@Ichinari
"So, are we near her workplace?"

@Ichinari
"It's all super fancy office blocks around here..."

@Akira
"Oh, no, it's not here."

@Akira
"It's over there, where it's even hipper and fancier."

@Ichinari
"Huh?"

@Ichinari
"Over there...?"

@Akira
"Look, that's the place! That big apartment block."

@Akira
"It's on the 29th floor. There's an amazing view."

@Ichinari
"The 29th floor?"

@Ichinari
"...These are real, honest-to-god skyscrapers."

I look up at the high-rise apartment blocks sitting along the coast line, a short walk from Yokohama Station.

This place isn't far from where I live, but it's like a whole new world to me.

We walk across the huge park in the center.

@Akira
"Rich people know no limits, do they?"

@Akira
"Here, check out this keycard."

@Akira
"You just have to tap this on the intercom to get in. Amazing, isn't it?"

@Akira
"If you manage to get popular, you can live somewhere like this too! Maybe!"

@Ichinari
"You think so?"

I can't believe I'm even working in the same industry as this person.

I didn't even know there were apartments that used keycards.

I always wondered what kind of people lived in buildings like this...

...but I never imagined it was a female hentai manga artist who's the same age as me.

I wonder what she eats?

I bet she's never eaten tissues.

@Akira
"Hello, this is Akira Higashibojo."

@Akira
"Oh, hello, Editor-in-Chief."

@Akira
"Huh? Uh, those documents?"

@Akira
"Huh, they were the wrong ones?! Seriously?!"

@Akira
"Eeeek! I'll go back and get them right now! I'll just be five minutes! Yes!"

@Akira
"Sorry, Ichi."

@Akira
"Due to unforseen circumstances, I'm going to have to rush back to the office. Tee hee☆"

@Ichinari
"Yeah, I got the gist, don't worry. I'll just wait around here till you get back."

@Akira
"But I told Ishitaka-sensei we'd be there right away..."

@Akira
"So would you mind going on ahead?"

@Akira
"Oh, and there's another assistant already there, so you can go right on in without calling on the intercom!"

@Akira
"She's so shy she turned it off, you see."

She hands me the keycard she'd previously shown me.

@Ichinari
"Huh? I should go on ahead? Huh?"

@Akira
"Make sure you absolutely, one hundred percent, do not offend her in any way!"

@Akira
"If worst comes to worst and you do mess up, just get down on your knees and play for time!"

@Akira
"I'll be right back!"

@Ichinari
"Hey, wait, Akira-chan!"

@Akira
"Aaargh, CRAP! Gotta run! SCRAMBLE DAAAAASH!"

@Ichinari
"...Are you kidding me?"

You've gotta be kidding me, Akira-chan...

I know the editor-in-chief summons you to the office all the time...

But this is definitely the worst timing ever.

Even if there is another assistant already there...

I don't wanna be left all on my own to meet a manga maestro who's so shy she can't even answer the intercom.

But since she's been told we're on our way, it'll look bad if I'm not there soon...

@Ichinari
"Guess I'd better go."

I've gotta take things as they come.

This must be fate.

If I can get through this, there'll be something good in store for me.

I take a deep, overly dramatic breath.

Steeling myself, I head toward the building Akira-chan had pointed out.

