#start|Three Fates

@Ichinari
"Hmm..."

@Ichinari
"Somehow I always feel more relaxed in an environment like this."

I look around the interior of the store, at least half of which is filled with pornographic content.

It's an hour before my appointment with Ishitaka-sensei.

I'm at Tomato Books, a dōjinshi shop close to Yokohama Station.

I stare at the section for newly-published adult comics.

@Ichinari
"Ishitaka-sensei really is incredible..."

Some time has passed since its original publication, but her book is still stacked in pride of place.

Akira-chan had said that it's still the company's number one seller.

As for my own release, there's a single measly copy.

But that's exactly why it'll be good for me to study under Ishitaka-sensei!

This way I'll become a best-seller too! Hell yeah!

After hoisting my spirits back up, I turn my gaze to the dōjinshi corner.

@Ichinari
"Whoa, check out this crazy display."

"The newest release from hugely popular circle of the moment, Soggy Panda!"

"Number one seller!"

"Nagomi-sensei delivers another explosively hardcore experience!"

The gaudy, hand-made signs jump out at me.

@Ichinari
"Oh, Soggy Panda's new release is out already."

I flip through the sample pages.

@Heroine
"Eep♪ Ahh, gimme that thick tentacle cock♪♪"

@Heroine
"Gyaaah♪ Mmf, the tentacles slamming against my womb feel soooo goooood♪♪♪"

@Heroine
"More! More! Fill me up with your sperm and impregnate meeeee♪♪♪"

@Ichinari
"Nagomi-sensei's stuff is as hardcore as ever, huh."

I continue flipping through the sample, each page crammed with coiling tentacles.

Nagomi-sensei's work is super hardcore, covering things like tentacles, brainwashing, and hypnosis.

Even though they only arrived on the scene about a year ago, their extreme content has already become super famous online.

@Ichinari
"I've followed them since they first debuted... I can't believe how far they've come."

I nod to myself as I stare at the big letters spelling out "NAGOMI."

While their main appeal is their attention to hardcore fetishes, the quality of their illustrations is also incredibly high.

They're totally on a par with professional manga artists, and miles better than some of the more mediocre ones.

At least, they're way ahead of me and my one measly book...

@Ichinari
"Anyway, this is really hot."

I'm blown away by the expressiveness of the art, which shows a fine-tuned aesthetic sense.

It's extreme, sure, but you can also tell that the artist is putting their all into something they genuinely love.

I studiously observe the tentacle and fluid-filled images.

@Nodoka/？？？
"..."

@Nodoka/？？？
"...Huh?"

@Nodoka/？？？
"Huh? Huuuh?"

The girl standing next to me blushes. She looks between me and the comic in my hands, confused.

She's dressed super fashionably. She doesn't look like the kinda girl who should be in a section full of tentacle romance and rape scenes.

I feel a bit guilty for perusing tentacle rape in front of such a cute girl, but...

Well, I guess she's not into these genres. She'll probably walk away soon.

Satisfied by this thought, I keep reading the Soggy Panda sample.

@Nodoka/？？？
"*staaare*"

She's not showing any sign of leaving.

Is it that unusual for a guy to enjoy reading rape-y manga?

I mean, it's obviously not something you should broadcast to the world, but...

@Nodoka/？？？
"*staaare*"

@Ichinari
"..."

I can't bear this stare of hers.

I grab a copy of Soggy Panda's new release and head for the register.

@Nodoka/？？？
"Could it be..."

@Nodoka/？？？
"Yes, it is..."

@Ichinari
"Well that sucked..."

I plop down on a bench in the park in front of Iori's building.

It's still half an hour until my appointment.

Thanks to that girl, I'd ended up fleeing the store much earlier than I'd wanted to.

@Ichinari
"And I ended up buying Nagomi-sensei's newest dōjinshi, too."

I'd used up the money I borrowed from Akira-chan for food.

Oh well, I should get paid for my most recent work tomorrow.

I'll just think of this as study material, which makes it a totally worthwhile purchase. Yep.

@Ichinari
"(looking around)"

@Ichinari
"I'll just have a little peek inside..."

After checking that there's no one else around, I pull the comic out of my bag.

@Ichinari
"Mm-hmm... This is really hot..."

The tentacles have no mercy.

They plunder and defile the heroine like nobody's business.

The illustrations are so freaking hot. I'm a step away from having a tentacle of my own rearing its head.

@Ichinari
"I get why they'd make a special display for this."

Even if you're not into tentacles, this dōjin could be your gateway drug into the genre.

That's how hot it is. I wonder what kinda super-perv (in a good way) drew this.

According to Akira-chan, there are actually a lot of female authors and fans of hardcore content.

In fact, one of my female friends in high school was into some pretty extreme stuff.

@Ichinari
"Was that fashionista girl back in the store actually a fan of Nagomi-sensei?"

I imagine her turning to me and saying something like "I'm really into brainwashing hypnosis tentacle porn!"

@Ichinari
"That'd be pretty cool."

The idea that a girl like that could be into wild sex stuff like this—

@Nodoka/Girl
"..."

@Ichinari
"...Huh?"

Speak of the devil! She's heading this way.

...Has she been following me?

Wait, no, that's ridiculous. But...

Tomato Books is on the other side of the station, meaning it's pretty far from here.

This side of the station is all luxury apartment blocks.

It's not the kinda place you just run into people from town, right?

Then why is she here? No, stop, I'm overthinking it.

@Ichinari
"Ah?!"

As I'm about to go back to reading, it hits me that I'm sitting here with a hardcore porn comic spread open in broad daylight.

Crap.

It may have been acceptable back in the store, but reading it out in public definitely makes me a pervert!

I quickly shove the dōjinshi back into my bag.

@Ichinari
"...Hm?"

@Nodoka/Girl
"Alrighty."

@Nodoka/Girl
"Haa, it's so hot today~"

The girl sits down beside me. She start to fan herself with her hand.

Then she pulls out a popsicle and starts to slowly lick it.

@Nodoka/Girl
"Mm. *lick* *suck*"

@Nodoka/Girl
"Haa, mm. *slurp*"

@Ichinari
"...Ngh."

This is hot.

Her voluptuous body.

The way she purposefully sticks her tongue right out of her mouth to lick the popsicle.

Her long, silky blonde hair.

The plunging cleavage between her breasts that holds a thousand secrets.

@Nodoka/Girl
"*lick* *suck* Mmm."

@Nodoka/Girl
"Hahn. *suck* Mm. *lick*"

@Ichinari
"..."

...This is so sexy.

I can't help but stare. Thankfully, it looks like she's so focused on licking the popsicle that she hasn't noticed me.

It's probably creepy if I keep staring for too long, but if I just take a peek from time to time instead—

@Nodoka/Girl
"...*glance*?"

Our eyes meet.

I let my gaze drift smoothly away from hers.

I turn my head away, acting as natural as possible.

Then I sneak another quick look to the side.

@Nodoka/Girl
"*staaare*"

@Ichinari
"..."

Crap, she caught me.

...Calm down.

It's not like she saw me practically undressing her with my eyes. Our gazes just happened to meet, simple as that.

I can just leave before she says anything. It's not like she's gonna chase me down.

I'll just casually, super casually, get up from the bench. Then I'll walk away like I'm going for an everyday stroll.

Perfect. Let's do it.

I'll slowly stand up in 3, 2, 1—

@Nodoka/Girl
"You were watching me, weren't you?"

@Ichinari
"Huh?"

@Nodoka/Girl
"This whole time."

@Nodoka/Girl
"You've been sneaking peeks at me, haven't you?"

@Ichinari
"No, uh... I wasn't..."

@Ichinari
"I mean, if you're asking if I was looking or I wasn't looking, then..."

@Ichinari
"Uh... I guess...I was looking?"

Argh, I'm such an idiot! Why am I confessing!

A cold sweat breaks out across my skin. I swallow hard, my heart beating fast, as I wait for her reaction.

@Nodoka/Girl
"And you were totally leering."

@Nodoka/Girl
"Girls can tell when they're being watched, you know? Hee hee."

Headlines flash through my head\: "Hentai Manga Artist Arrested for Perving in Broad Daylight."

Then a lawyer's comment saying something like, "if you're falsely accused, you should run before they can arrest you."

This is the time to pull out all the stops and run the fastest race of my life.

Ready, set—

@Nodoka/Girl
"You can't run from me..."

@Nodoka/Girl
"...Ichinari Tsuzurigi?"

@Ichinari
"...Huh?"

@Ichinari
"H-How do you know my name?!"

@Nodoka/Girl
"Hee hee. I knew it."

@Nodoka/Girl
"Do you want to know how I know?"

Has she been targeting me all along?!

You can shake me down all you want, but all you're gonna get is the copyright of a hentai manga that won't even sell.

@Nodoka/Girl
"Ngh! Ah, cold...!"

@Nodoka/Girl
"I dropped ice on my boobs! Ah, no! Ah...!"

@Nodoka/Girl
"Ah, now my fingers are all sticky..."

@Nodoka/Girl
"Mm. *lick* *suck* Ngh."

@Nodoka/Girl
"...*glance*?"

@Ichinari
"..."

@Ichinari
"Um..."

@Ichinari
"You're doing this on purpose, aren't you?"

I accuse the girl as she licks at her fingertips.

@Nodoka/Girl
"Hee hee. Just a little♪"

@Nodoka/Girl
"You don't like it?"

@Ichinari
"No, I really like it."

I see, so SHE'S the molester.

Then you should've said so earlier, so I could— Wait, no, that's ridiculous!

Seriously, what the hell is with this girl?!

Clearly, she knows my name, but I'd definitely remember a hottie like her if we'd met before.

@Ichinari
"Um, I think maybe you've mistaken me for someone else?"

@Ichinari
"There're probably a lot of guys out there with the same name..."

@Nodoka/Girl
"I think Ichinari Tsuzurigi's a pretty rare name."

@Ichinari
"...Yeah, it is."

Unable to argue with that, I find myself nodding along.

Tsuzurigi is an unusual surname; I've never met anyone with it other than my own family.

Which means that... Um...

@Nodoka/Girl
"Hee hee. I wouldn't act this way around a stranger, you know?"

@Nodoka/Girl
"I just wanted to mess around with you a bit, Senpai."

@Nodoka/Girl
"Your reactions are sooo good, I just couldn't help myself."

@Nodoka/Girl
"Although I didn't plan on dribbling ice on myself. Hee hee."

@Ichinari
"..."

@Ichinari
"...Huh?"

@Ichinari
"Senpai...?"

@Nodoka/Girl
"Yes. You're my senpai, Ichinari."

She blushes slightly, then turns to me with the sweetest, gentlest smile on her face.

@Ichinari
"If you're calling me 'senpai,' does that mean..."

@Ichinari
"Hang on..."

@Ichinari
"There's only one person I can think of who'd call me that..."

But that girl wasn't sexy and fashionable like this woman before me.

And she certainly wasn't so voluptuous.

She'd had regular old black hair, and had been kinda plain...

@Nodoka/Girl
"Shall I give you a hint?"

She pulls a glasses case from her bag.

@Nodoka/Girl
"How about now?"

@Nodoka/Girl
"Is it coming back to you?"

As soon as she puts the glasses on, she becomes the girl I'd been thinking of.

@Ichinari
"So it IS you..."

@Ichinari
"...Nodoka Amabane?"

@Nodoka
"Yes. I haven't seen you in a long time, Senpai."

@Nodoka
"Not since you graduated."

She adjusts her glasses and beams at me.

@Ichinari
"Huh? But when we were in manga club together, you were... Um..."

@Ichinari
"You weren't this, uh, confident...?"

@Nodoka
"Hee hee. You can go ahead and say it. I was totally uncool."

@Nodoka
"I had boring black hair back then. It's no wonder you didn't recognize me."

She uses both hands to form her hair into bunches.

@Ichinari
"It really is you."

@Ichinari
"You've really, uh, changed..."

@Ichinari
"You're like a real big-city girl now."

@Nodoka
"Hee hee. It's not like that. In fact, it's the opposite."

@Nodoka
"I'm actually only half-Japanese. I used to dye my hair black."

@Nodoka
"Back then, I didn't want to stand out."

@Nodoka
"So this is my natural hair color. They say it's quite rare even for a mixed-race person."

She flashes me a playful smile.

Oh, I remember that look.

A wave of familiarity rolls over me when I see it.

@Ichinari
"Ah, I get it..."

@Ichinari
"But it's not just your hair color that's different."

A narrow waist and long, lean legs. Plus sexy, voluptuous curves.

She oozes the kind of confidence you'd expect from an older woman, not someone younger than me.

I mutter to myself in admiration.

@Nodoka
"I put a lot of work in too."

@Nodoka
"I got my hair done, learned how to use makeup..."

@Nodoka
"Exercised properly, and learned what clothes suit me..."

@Nodoka
"A lot has changed with me since you graduated, Senpai♪ Hee hee♪"

Closing her eyes, she giggles happily to herself.

@Nodoka
"You said you'd keep in touch with me, but I never received a single message from you."

@Nodoka
"I tried contacting you, but none of my calls or messages went through."

@Ichinari
"Oh, uh, my phone broke and I lost all my contacts..."

@Ichinari
"I'm really, really sorry about that."

@Nodoka
"Oh no you don't."

@Ichinari
"Huh?"

@Nodoka
"You promised me..."

@Nodoka
"And I've been waiting, all this time."

@Nodoka
"So I'm not going to forgive you just like that."

@Nodoka
"I'm not going to let you off so easily..."

@Nodoka
"...or say that it's all well and good now that we've finally met again."

@Ichinari
"Hey, that's—"

@Nodoka
"Hee hee! You're so cute when you're feeling bad♪"

@Nodoka
"But you broke your promise to me, so I want you to feel even worse about it."

@Nodoka
"You deserve punishment for making me think I'd never see you again♪"

Contrary to her words, her tone is cheerful. She flicks her tongue out to lick at the popsicle that's melting over her hand.

@Iori
"Huh?"

@Iori
"Ichinari and Nodoka? Huh...?"

@Nodoka
"Oh, Iori-san."

@Ichinari
"Oh, Ishitaka-sensei."

@Nodoka/Nodoka＆Ichinari
"...Huh？"
"...Huh？"

Nodoka and I look at one another.

@Nodoka/Iori＆Nodoka
"Umm..."
"Umm..."

Now it's Iori and Nodoka staring at each other.

@Nodoka/Iori＆Nodoka
"..."
"..."

@Iori
"Do you two...know each other?"

@Nodoka
"Oh, yes, we do. Ichinari was the year above me at high school, and we were in the same club."

@Iori
"So he's the one who taught you how to draw manga?"

@Nodoka
"Um... So you know each other, too?"

@Ichinari
"Oh, um, yes."

@Ichinari
"I lived next door to her when we were in elementary school."

@Nodoka
"So he's the one you promised to become a manga artist with when you were kids."

@Nodoka/Iori＆Nodoka
"..."
"..."

Each of them awkwardly averts their gaze from the other.

@Ichinari
"Umm..."

@Ichinari
"So I take it you two also know each other?"

@Iori
"Y-Yes... You could say that..."

@Iori
"Nodoka here has been working as my assistant for the past two years."

@Nodoka
"Iori-san's been teaching me all about drawing manga."

@Ichinari
"You've got to be kidding me."

It's almost too much of a coincidence to believe.

@Nodoka
"*ahem*"

@Nodoka
"So, to introduce myself properly..."

@Nodoka
"I'm Ishitaka-sensei's assistant, Nodoka Amabane."

@Ichinari
"And I'm Ichinari Tsuzurigi. Starting today, I'll be Ishitaka-sensei's new assistant."

@Iori
"Oh, um... I'm Iori Shitaka...manga artist."

@Iori/Iori＆Nodoka＆Ichinari
"I look forward to working with you all."

We all make our formal introductions and bow our heads to one another.

@Ichinari
"Anyway..."

@Ichinari
"This is a pretty huge coincidence."

@Nodoka
"Yes, it is. Who'd have thought?"

@Iori
"Y-Yeah, it really is..."

The mood between us is strained. We're all exchanging awkward looks.

Although we do know each other, it's been ages since I last saw either of these two.

I get the feeling that, if I try to bring up the past, one of them will end up feeling left out.

I stare at them both, wondering how I'm going to deal with this.

@Iori
"...What?"

@Nodoka
"Is something wrong?"

@Ichinari
"No, it's all good."

Damn, they both turned out super hot.

I feel kinda emotional, talking to the two of them now they're all grown up like this.

@Ichinari
"So you're in this industry too, huh, Nodoka?"

@Ichinari
"You said you're learning from Ishitaka-sensei, so does that mean you're getting ready to make your own debut on the scene? "

@Nodoka
"Oh, no, I'm not really interested in commercial manga."

@Nodoka
"I'm more about dōjinshi—amateur stuff, where I can draw whatever I like."

@Ichinari
"Wow, so you draw dōjinshi?"

@Iori
"Nodoka's already a pretty popular dōjin artist, so there's no need for her to work for a commercial magazine."

@Iori
"And she says I'm teaching her, but all I really did was show her the basic rules."

@Iori
"She always had the talent, so there was nothing for me to teach her."

@Nodoka
"That's not true! I'm still learning a lot from you."

@Nodoka
"If it weren't for you, Iori-san, I probably would have lost heart long ago♪ Purr, purr~♪"

@Iori
"Hey, Nodoka!"

@Iori
"I told you to stop doing that, come on...!"

@Nodoka
"Okaaay, my baaad♪"

Nodoka nuzzles Iori's shoulder without any hint of remorse. Iori blushes, but she's not pushing Nodoka away.

These two seem like they're really good friends.

@Nodoka
"Anyway, you buy dōjinshi, right, Senpai?"

@Ichinari
"You mean like the one earlier? Yeah."

@Ichinari
"I've bought every single one of Nagomi-sensei's releases, right from the start."

@Ichinari
"The content's a bit extreme, but the art is just so good."

@Ichinari
"Do you know who I'm talking about, Ishitaka-sensei? The author of this."

I pull the dōjinshi I'd just bought out of my bag and show it to her.

@Iori
"Huh? Uh, yes, I know them, but..."

She looks down with a sideways glance at the girl beside her.

@Nodoka
"Yep, that's me♪"

@Ichinari
"...Huh?"

Nodoka grins, and it suddenly hits me.

@Ichinari
"Nodoka..."

@Ichinari
"Nodo...ka...?"

@Ichinari
"The 'nodo' kanji character can also be read as 'nagomi'..."

@Ichinari
"You're Nagomi?!"

I point directly at her, asking her to confirm what I've already figured out.

@Nodoka
"Yep. Thank you for being a fan♪"

She flashes me a V sign.

@Ichinari
"..."

@Ichinari
"Huh? Wait, what? ...Huh?!"

@Ichinari
"Nagomi-sensei is Nodoka?!"

@Nodoka
"It really warms my heart to hear praise from you, Senpai."

@Nodoka
"And to think you've been a fan right from the start! Hee hee♪"

She suppresses a little giggle, then ducks her head slightly and gives me a bashful look.

@Ichinari
"...Huh?"

@Ichinari
"WHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAT?!"

@Ichinari
"Ishitaka-sensei...?! And Nagomi-sensei...?!"

I point at each of them in turn with a trembling finger.

@Iori
"*nod*"

@Nodoka
"*nod*"

@Ichinari
"WHAAAAaaaAAAAAaaaAAAAAATTTTT?!"

@Ichinari
"The number one of the hentai manga world..."

@Ichinari
"And the numero uno of the dōjin world...?!"

@Ichinari
"There are not one but TWO hentai manga maestros right in front of me?!"

@Iori
"I wouldn't call myself number one... You don't need to act so shocked."

@Nodoka
"Although you are being very cute right now, Senpai♪"

@Ichinari
"IS THIS REAL LIFE?!"

My two idols, who I've looked up to all this time, are right here before my eyes.

And they're both also friends from my past?! What kind of miracle is this?!

I can feel sweat running down my forehead as I freak out.

@Nodoka
"Now I get to draw manga with Senpai again!"

@Nodoka
"I'm so happy! It'll be just like back when we were in manga club together."

@Nodoka
"Do you remember how we used to stay up late into the night, just the two of us, drawing together?"

@Iori
"Just the two of you... Late into the night...?"

@Iori
"Uh... The whole time you were in high school...?"

@Nodoka
"It's a hard life being an otaku out in the boonies."

@Nodoka
"It took a lot of courage for me to even join the manga club."

@Nodoka
"But having Senpai there gave me strength~"

@Ichinari
"That doesn't sound like something the hardcore artist Nagomi-sensei would say."

@Nodoka
"Hee hee. Even now I make sure to maintain a double life."

@Nodoka
"I love my work and I have great pride in it, but I'm also aware I'm in somewhat of a seedy industry."

@Ichinari
"Well, it's hard to argue with that."

As I nod in agreement with Nodoka, I find myself calming down.

@Iori
"..."

@Nodoka
"So, Iori-san, what about you and Senpai?"

@Iori
"Huh?"

@Iori
"Oh, um, r-right..."

@Iori
"Like Ichinari said, we were neighbors when we were little..."

@Ichinari
"Yeah, and we became really good friends due to our shared love of manga."

@Ichinari
"Back then we'd spend every day at one of our houses, just drawing manga all day long."

@Iori
"Y-Yeah... We always drew together..."

@Nodoka
"Huh~ So you guys are childhood friends~"

@Nodoka
"Which means that you're the first person Senpai drew manga with, Iori-san..."

@Nodoka
"I always thought I was his first. Haha..."

Nodoka looks away with a forced laugh.

@Nodoka
"Oh, so does that mean..."

@Nodoka
"...that you have some of Senpai's old manga, Iori-san?"

@Iori
"Uh, y-yeah... I hung onto it..."

@Nodoka
"I have some from when we were in high school! Can we share it?!"

@Nodoka
"I really wanna see what his drawings were like in elementary school~♪"

@Iori
"That's a very appealing idea."

@Iori
"I want to see his manga from high school too."

@Ichinari
"No, no, no, no! Wait just a minute!"

@Ichinari
"Don't drag me out for public humiliation!"

@Ichinari
"Anyway, work! Let's talk about work! Okay?!"

@Ichinari
"If you wanna see my manga, I brought some recent drafts as references for the assistant job."

@Ichinari
"Here you go! Please take a look!"

Desperately trying to divert their attention elsewhere, I hand them the drafts I'd put together yesterday.

@Iori
"Hmm..."

@Nodoka
"Hmm..."

@Ichinari
"..."

We're in the spacious living room of the 29th-floor apartment. The only sound is the rustle of paper as they flip through my drafts.

I'm showing my manga to the top dogs of the commercial and dōjin world and awaiting their judgement. I'm super nervous.

I'm on the edge of my seat as I await their comments.

@Iori
"Hmm."

@Iori
"Of course, I've read your previous works, but..."

@Iori
"You're the kind of guy who can do anything he puts his mind to, aren't you, Ichinari."

@Nodoka
"Yeah, you're really, really good, so..."

@Nodoka
"...why have you been struggling to the point where you have to eat tissues?"

@Ichinari
"Oh, you already heard about that, huh."

Did Akira-chan tell them? Well, it's a pretty straightforward way to explain my situation.

But anyway, I'm pleased that they both gave positive assessments.

@Nodoka
"They're not quite on a level with Iori-san's, but your character designs are really cute."

@Iori
"And they're not quite on a level with Nodoka's, but I think you draw the backgrounds and actions really well."

@Ichinari
"Mm-hm. I see, I see."

@Ichinari
"So what's your overall verdict?"

@Nodoka/Iori＆Nodoka
"...Kinda average?"
"...Kinda average?"

@Ichinari
"I appreciate your valuable opinions."

Average...

They have the same opinion as the editor-in-chief, which Akira-chan had conveyed to me before.

These two in front of me sure aren't average.

I guess that's why their stuff sells like hot cakes, while I still just can't figure out what it takes.

@Iori
"B-But I don't mean that in a bad way!"

@Nodoka
"Right! 'Average' can be a good thing, can't it?"

@Iori
"Yes, I think you have plenty of talent..."

@Nodoka
"And I think it's pretty amazing that there isn't really anything to criticize."

They hurry to comfort me, probably thinking from my expression that they've upset me.

They're both so kind. But that's exactly why I need to say this.

@Ichinari
"Thank you."

@Ichinari
"Although I don't even know where exactly my problem lies..."

@Ichinari
"I'll do my very best, so please, teach me everything you know!"

At first I'd only accepted this job offer for the money, but now it's become something more than that.

I've been reunited with two old friends, and on top of that, I get to hone my skills under two hentai masters.

This is the best environment I can think of, both personally and professionally.

I bow my head to them in gratitude.

@Iori
"Ichinari..."

@Iori
"Okay, I understand. I'll do whatever I can to help."

@Nodoka
"Me too. After all, I still owe you for everything you taught me."

@Iori
"And I'll be counting on you, too."

@Iori
"We can do this."

@Nodoka
"I'm really glad I get to work with you, Senpai."

@Nodoka
"I'm looking forward to it♪"

The two of them both bow to me in return, and I feel a warmth in my chest.

@Akira
"Guuuuuys! How are you doing?!"

@Akira
"I brought snacks! Dorayaki pancakes, on me!"

@Iori
"Oh, Akira-chan."

@Nodoka
"Evening, Akira-san~"

@Akira
"Oh, you're here too, Nodoka-chan!"

@Akira
"Ichi may be a loser, but he's not a bad guy, so please be nice to him!"

@Akira
"Like, he's a real loser, but he's really not a bad kid!"

@Iori
"Yes, I know, so don't worry."

@Nodoka
"I know that too, so no worries here~!"

@Ichinari
"Oh, is that so...?"

The two of them are smiling and nodding away. Their reaction is a little disappointing.

I acknowledge myself that I'm a loser, but knowing that they both agree is kind of a blow to the ego.

@Akira
"Huh? I heard about you and Iori-chan yesterday, but..."

@Akira
"You know Ichi too, Nodoka-chan? Huh?"

~Explaining how I know Nodoka to Akira~

@Akira
"Ichi, you little liar!"

@Akira
"You're actually a total normie."

@Akira
"I thought neither of us were getting any, but now it turns out you're a real fuckboy!"

@Ichinari
"No, uh, I haven't been 'getting any.'"

@Akira
"Hmm? Hmmmmm?"

@Akira
"Well, I suppose if you INSIST, then we'll leave it at that."

She's giving me a really dubious look.

Well, I suppose if you look at it on the surface, I did spend a lot of time with each of these two cute girls.

And if you were to ask me if I made the most of it... Well, sure.

Although I didn't "get any." At all.

Still, that being said, I'm also blessed with an editor who herself is blessed with—

@Akira
"What? What're you giving me that look for?"

@Ichinari
"Uh, no reason."

Whatever I say right now is gonna be the wrong thing.

I avert my eyes and keep my mouth shut.

@Iori
"Earlier, I formally applied for Ichinari to be my assistant."

@Iori
"I already know him, and he has the skills..."

@Iori
"Could you please thank the editor-in-chief for the introduction?"

@Akira
"Sure thing! I'll let her know."

@Akira
"And you'd better work your butt off here, Ichi, you hear me?"

@Akira
"Do that, and it's sure to bring results! Probably!"

@Ichinari
"Yessir, I'll do my very best, yessiree."

I give her my best martial arts-style salute.

@Nodoka
"By the way, Senpai, how have your comics been doing in terms of sales?"

@Akira
"Ahh, as his editor, this is kind of a sort point."

@Akira
"I worked really hard on the sales promo, you know?"

@Akira
"But it just wasn't meant to be. Ahaha!"

@Ichinari
"I'm sure you can tell from my current lifestyle."

@Nodoka
"W-Well, sometimes sales pick up well after release. Ahaha~"

@Iori
"Right, if you get some good reviews, you can start to gain a following later..."

@Ichinari
"It's already been quite a while since the release and we still have tons of the first print run left over. Ahaha!"

@Nodoka/Iori＆Nodoka
"Oh..."
"I see..."

They both avert their eyes from me.

Hey, the reviews weren't bad.

At least as far as I know. I think.

@Iori
"Umm, well, anyway, about the current schedule..."

@Iori
"Nodoka will be assisting me with the same amount as she has been doing..."

@Iori
"And Ichinari will work on the stuff for the extra monthly manga. Does that sound okay?"

@Nodoka
"Broadly speaking, Iori-san does the character work, and we do the rest."

@Iori
"You'll pick it up as you go along."

@Ichinari
"Understood. I'll do my best."

@Akira
"You'd better. Iori-chan's super strict about her schedule!"

@Akira
"As her editor, it's a real lifesaver. I'm suuuper grateful."

@Akira
"When a manuscript is late I have to bow so much it feels like my neck is gonna snap... Ahaha..."

Akira-chan gazes into the distance.

Being an editor sounds rough. I'll try and take more care from now on. Yep.

@Iori
"Um, also..."

@Iori
"Ichinari, do you, um, want to work here?"

@Iori
"Nodoka mostly works from home, so, um..."

@Iori
"We'd end up spending a lot of time alone together..."

@Ichinari
"Oh, uh, right."

@Ichinari
"I'm sure I'm gonna have a lot of things to ask you in the beginning, so..."

@Ichinari
"If possible, I think it'd be better if I could work here."

@Ichinari
"But if that would be a problem, I'm fine with communicating online."

@Iori
"I-I..."

@Iori
"If you're fine with it, then...I have no problem..."

@Akira
"No worries, no worries!"

@Akira
"I'll drop by as much as possible!"

@Nodoka
"If Senpai's going to be here, then I'll work here too♪"

@Iori
"...Oh."

@Iori
"Okay then."

@Iori
"I'll put in an order for a workstation for you tomorrow."

@Iori
"So you can start as soon as it arrives."

@Iori
"I'll probably have everything set up by the day after tomorrow."

@Ichinari
"Oh, sure... That sounds good."

I nod to Iori, who suddenly seems to have lost her enthusiasm.

I'm probably gonna have a lot of questions for Nodoka, too. And with Akira-chan here, we'll be able to keep the conversation going.

Honestly, if I were left all alone with Iori, I'd probably act super weird.

I can't figure out what the appropriate distance between us should be.

I haven't seen Nodoka since high school, which is quite recent compared to Iori, who I'd lost contact with for ten years.

Not to mention that she's secret my manga idol, who I'm now gonna be working as an assistant to.

@Nodoka
"So, I think that's enough shop talk for today."

@Nodoka
"How about we go out for a drink to celebrate?"

@Nodoka
"We have a lot to catch up on♪"

@Akira
"Ooooh, great idea!"

@Akira
"As his editor, I'm pretty much obliged to join you!"

@Akira
"Ahh, beer tastes best while the sun's still up~!"

@Iori
"Yes, I'm in too."

@Iori
"Are you okay with this, Ichinari?"

@Iori
"It'll be on me."

@Ichinari
"Yes, I would be very much obliged."

I'm already bowing deeply to her.

@Nodoka
"Okay then, I'll make a reservation at the usual place♪"

@Akira
"I've just gotta reply to a few emails."

Nodoka leaves with her cellphone, and Akira-chan leaves with her laptop.

Iori and I are left behind in the living room.

@Iori
"Hey, Ichinari..."

Iori says my name and I turn to look at her.

@Iori
"Umm..."

@Iori
"Since you're going to be working as my assistant from here on..."

@Iori
"...I have one request."

@Ichinari
"Yes, I'll do anything you ask, Ishitaka-sensei."

@Iori
"It's that..."

@Ichinari
"That...?"

@Ichinari
"What's that...?"

I'm confused.

@Iori
"I'd like you to stop calling me that."

@Ichinari
"That? You mean Ishitaka-sensei?"

She nods.

@Iori
"I know I'm Ishitaka the manga artist..."

@Iori
"But..."

@Iori
"Around you...I don't want to be..."

@Iori
"I want to be your friend, Iori... Like before..."

@Iori
"I'm the same as I was back then, after all."

@Iori
"So..."

Her eyes are glistening with tears, and her lips are set in a tight line as she gazes at me.

Ah, I see.

Iori simply kept on chasing her dream until she finally realized it.

She's not changed on the inside, so to have me treating her differently must have unnerved her.

@Ichinari
"Okay, I understand. And I'm sorry."

@Ichinari
"So, let's try this again."

@Ichinari
"I'm looking forward to working with you, Iori."

@Iori
"Ichinari..."

@Iori
"Yeah. Me too, Ichinari."

With a little nod, she shows me the sweetest smile I've ever seen on her.

Ah, she's so cute.

She may not have changed on the inside, but she sure has changed a lot on the outside.

@Akira
"All dooooone! ...Hm?"

@Akira
"Hey, did something happen? Something feels different between you two."

@Ichinari
"No, nothing's changed."

@Ichinari
"Actually, maybe we just went back to normal."

@Ichinari
"Right, Iori?"

@Iori
"Yes, we just went back to normal. Hee hee."

I share a laugh with my childhood friend.

Iori worked hard to realize her dream. I can't let myself be outdone.

@Akira
"Hm? Hmmm?"

@Nodoka
"I got us a table for four!"

@Akira
"Oh, thanks, Nodoka-chan!"

@Akira
"Alrighty, let's go go goooo♪"

@Iori
"Yes, let's head out."

@Ichinari
"Thanks for footing the bill!"

After we're done with all the formalities, the four of us head out and walk to the bar Nodoka's made a reservation at.

@Akira
"Umm, sooo..."

@Akira
"Cheers to our new assistant, Ichi!"

@Akira/Iori＆Nodoka＆Akira
"Cheers""Cheeeers♪""Cheeeers♪"

@Akira
"*glug glug glug glug*"

@Akira
"Pwaaaah!"

@Akira
"Ahhh, beer before sundown really is THE BEST!"

@Akira
"MANAGER! Can we get another pint over here?!"

@Nodoka
"Akira-san, this is a classy place, so could you maybe keep it down a bit?"

@Akira
"Oops! I haven't been out in ages, so I got a bit carried away~♪"

@Iori
"Akira-chan, you've got a foam mustache."

@Akira
"You think I'm worried about a lil foam?!"

@Akira
"*glug glug glug♪* PWAAAAAAH!"

We're in a trendy bar/restaurant with limited seating.

The background music is a smooth, relaxing jazz. The wait staff are all dressed in smart waistcoats.

Of course, the food and drink is all top-notch.

@Ichinari
"So this is your regular bar, huh?"

@Ichinari
"It's like something out of a manga..."

I mutter to myself as I look around the stylish interior.

@Iori
"Hee hee. That's going a bit far."

@Nodoka
"It's just our favorite local place."

@Ichinari
"I see..."

So to Iori and Nodoka, this place is like my local fast food joint, huh?

I sip at my cocktail, which costs as much as three full beef bowls at said local joint.

It's really good.

@Nodoka
"Anyway, I can't believe you all know Senpai, too."

@Iori
"It really is a small world."

@Akira
"Woulda helped if I knew about all this earlier though. *glug glug*"

@Ichinari
"I was shocked that I got to meet the great Ishitaka-sensei and Nagomi-sensei, but..."

@Ichinari
"I'm even more shocked at meeting Iori and Nodoka again."

I nod earnestly.

@Iori
"It's been over ten years, hasn't it."

@Iori
"I never thought I'd actually get to see you again."

@Nodoka
"And I haven't seen you since you graduated high school, three years ago."

@Nodoka
"Although it feels like it's been way longer than that. Hee hee."

@Akira
"I've only known you since I started this job, so that's two years, I guess."

@Akira
"Time flies, doesn't it, Ichineri-sensei♪"

@Ichinari
"Oh, well, it's thanks to all of you that I've gotten anywhere at all."

@Ichinari
"I do wish I could've met you again under better personal circumstances though."

@Iori
"Hee hee. I think you're doing fine."

@Iori
"I don't look down on you or anything."

@Nodoka
"You've always been so concerned with appearances~"

@Nodoka
"Although I guess that's one of the things that's so cute about you♪"

@Akira
"The Ichi I know is a total loser though!"

@Akira
"But he used to be a real go-getter at one point, huh? I see, I see."

We get into reminiscing about times both long and not so far gone.

I feel like, bit by bit, the distance opened up over the years between us is closing.

@Nodoka
"But you haven't changed at all, have you, Senpai."

@Nodoka
"I knew it was you straight away when I saw you at Tomato Books."

@Ichinari
"Whereas you've changed so much I didn't recognize you at all."

@Nodoka
"Really? How have I changed?"

@Ichinari
"You're, like, a real big-city girl now."

@Nodoka
"You said that earlier, too."

@Nodoka
"But I wanna know specifics, like how exactly have I changed?"

@Ichinari
"Are you drunk, Nodoka? You okay?"

@Nodoka
"I'm not even tipsy! Stop dodging the question and answer me!"

@Ichinari
"Er, well, I guess I didn't recognize you because..."

@Ichinari
"...you've gotten super pretty."

@Nodoka
"What? Really? Reaaaally?"

@Nodoka
"I see, so I got pretty, did I? Tee hee~♪"

@Nodoka
"I put in a lot of effort to make people think that♪"

@Nodoka
"So I'm suuuper happy to hear that from you, Senpai♪ Tee hee~♪"

She smiles, and her cheeks are slightly flushed, perhaps from the alcohol. She swirls her glass, making the ice clink.

SO CUTE.

While her appearance is totally polished, she still retains her innocence of the past; the contrast only serves to make her even more adorable.

I take a drink to cover up how flustered I'm feeling.

@Iori
"Yes..."

@Iori
"Isn't it great that Nodoka's so pretty..."

@Nodoka
"What're you pouting about?"

@Nodoka
"You're a stunner yourself, Iori-san♪"

@Nodoka
"You think so too, don't you, Senpai?"

@Ichinari
"Huh? Me?"

@Nodoka
"Like, when you first met her, didn't you think..."

@Nodoka
"OMG I can't believe such a cute girl draws such naughty manga!!!"

@Nodoka
"Or something along those lines?"

@Ichinari
"Nodoka-san, you're definitely drunk."

I tease Nodoka for acting out of character.

@Nodoka
"Hee hee! This is just my true personality rearing its head."

She covers her mouth with her hand, then shoots a mischievous glance my way.

@Iori
"..."

@Iori
"Did you really...think so, Ichinari?"

@Ichinari
"Huh?"

@Iori
"Did you think that..."

@Iori
"...about...me..."

She fidgets with her fingers, then she looks up at me through her lashes.

@Ichinari
"Uh, well..."

@Ichinari
"Yeah, I did."

I look away in embarrassment as I answer honestly.

@Iori
"..."

@Iori
"You don't have to try and spare my feelings."

@Iori
"It's not like I think of myself that way..."

Pouting slightly, she fiddles with her straw, chasing around the ice in her glass.

@Ichinari
"U-Uh, no, that's not...you know...?"

@Ichinari
"I'm not trying to spare your feelings..."

@Ichinari
"It's just embarrassing to admit it in front of you. Sorry."

I dip my head apologetically, then clear my throat.

@Ichinari
"Umm, well, I..."

@Ichinari
"When I saw you, I thought you were really, really pretty."

@Ichinari
"And I'm not saying that to spare your feelings. I mean it."

@Iori
"Ichinari..."

Although, if I'm being honest, my very first thought was far more lascivious.

But I won't mention that. Besides, it is true that I thought she was pretty.

@Iori
"Really? You're not lying?"

@Ichinari
"I already told you I'm not."

@Ichinari
"I swear on my life as a manga artist."

@Iori
"..."

@Iori
"Hee hee! I'm so happy!"

@Iori
"Tee hee hee♪"

Grinning widely, she giggles to herself. Then she takes her glass in both hands and raises it to her lips to take a sip.

...Oh, crap.

Her relieved expression after putting on that I-don't-care act is adorable as hell.

Nodoka is cute too, but Iori has her own charm...

I take another big gulp of my drink.

@Akira
"Waaaah! Why don't I get called cute and pretty?!"

@Akira
"Is it MY fault I get worked to the bone?! Ya fuckers!"

@Akira
"Just challenge me to a judo match and you'll see how strong I am!"

@Akira
"Lemme demonstrate my pinning technique on you, Ichi!"

@Ichinari
"Calm down! No one's pinning anyone!"

@Akira
"Then tell me I'm pretty too, Ichi!"

@Ichinari
"Uhh..."

@Akira
"What's with that reaction?! You're soooo mean!"

@Akira
"You won't shut up about how cute Iori-chan and Nodoka-chan are!"

@Akira
"What about me?! SAY IT!"

@Ichinari
"Uh, well..."

@Ichinari
"I do think you're pretty, Akira-chan."

@Akira
"Again! Say it from the heart! One more time!"

@Ichinari
"You're pretty and cute, Akira-chan! The cutest of the cute!"

@Akira
"AGAIN!"

@Ichinari
"You're a goddess, Akira-chan! A national treasure!"

@Akira
"Mm-hmm, mm-hmm, that's more like it~"

@Akira
"So that's how it is~ I see, I see♪"

@Akira
"Well, of course, I am pretty great, aren't I?"

@Akira
"You're so sweet when you're being nice and meek and honest, Ichi. Hee hee♪"

She seems satisfied.

I really don't understand women...

But it's true that Akira-chan is cute and pretty, so it's worth telling her so if it'll satisfy her.

Plus the fact that she's so blunt and straightforward is part of her appeal.

@Ichinari
"Haha..."

Just yesterday, the crushing poverty I was experiencing had me on the verge of giving up on my dreams.

I couldn't have imaged that my life would be turned upside down in a single day.

Looking down into my class, I think about how miracles really do exist.

And that's where I see it.

@Ichinari
"...A black cat."

It's a simple, clean design in keeping with the bar's atmosphere.

A small black cat stamped on the bottom of the glass.

@Iori
"Yep, it's the bar's logo."

@Iori
"Since its name is 'The Black Cat.'"

@Nodoka
"It's a cute design, right?"

@Nodoka
"I love the trendy interior of this place too~"

@Ichinari
"I see. 'The Black Cat,' huh?"

Those words remind me of my best buddy.

@Ichinari
"I wonder if that wish worked...?"

Given how miraculous this change in my circumstances is, the words slip from my lips before I can stop them.

@Akira
"Wish?"

@Ichinari
"I read this article online that said black cats are messengers to the gods."

@Ichinari
"So I made a wish to Blackie the cat."

@Ichinari
"So I was just wondering if maybe she passed it on to one of them."

@Nodoka
"Oh, I read that article too!"

@Nodoka
"That's sooo cute that you made a wish to a cat, Senpai♪"

@Iori
"Hee hee. You draw so well, though, you don't need to rely on wishes."

@Iori
"This has come from your own hard work."

@Akira
"She's right! Onee-chan knows how hard you've been working, Ichi."

@Akira
"You never would've been recommended for the assistant job otherwise."

@Ichinari
"It'd be nice if that were true..."

I smile wryly in response to their compliments. Then I gently run a finger over the black cat logo on the glass.

@Ichinari
"Whether it's come from the gods or not, I think I've been given a really great opportunity here."

@Ichinari
"So I'm really going to give it my all. I promise."

I bow my head to them yet again.

@Iori
"I'll be counting on it."

@Nodoka
"I hope to learn a lot from you, too, Senpai♪"

@Akira
"And there won't be any mollycoddling from me. I'll keep you on the straight and narrow♪"

@Akira
"So, let's have another toast!"

@Akira
"To Ichi's fresh start!"

@Akira/Iori＆Nodoka＆Akira
"Cheers♪""Cheeeers♪""Cheeers♪"

@Akira
"Ahhh, that was so much fun♪"

@Akira
"The food was sooo good. I feel like I'll have tons of energy for tomorrow!"

@Nodoka
"Yeah, and the drinks were really good too♪"

@Iori
"They were! I haven't been this drunk in a long time."

Everyone's a lot more relaxed on the way back than they were on the way there. The cool night breeze feels good on my warm skin.

The four of us walk along, shoulder to shoulder, toward Yokohama Station.

@Ichinari
"Thanks for taking us out, Iori."

@Ichinari
"It was really, really good. Seriously."

@Ichinari
"It's been so long since I had such good food, it actually made me tear up a little."

@Iori
"Hee hee. I'm just glad you enjoyed it."

@Iori
"Since you liked it so much, let's go again sometime."

@Ichinari
"I'd love that."

Unlike yesterday, she's smiling openly now. She gives me a little nod.

While we've been chatting, we've arrived in front of the station.

@Iori
"Well, this is me."

@Iori
"I'll be in touch once your workstation's set up."

@Ichinari
"Yeah, I'll be waiting to hear from you."

@Akira
"I've gotta stop by the office, so I'll see you guys later!"

@Ichinari
"I'm heading through to the other side of the station, so I'll be off too."

@Nodoka
"I'll head home too then."

@Iori
"'Kay. Night everyone."

We all wave to one another before we splinter off on our separate ways home.

@Iori
"Phew, that was fun."

@Iori
"Ichinari said I'm pretty..."

@Iori
"Hee hee... Tee hee hee~♪"

@"Black Cat"
"Meow."

@Iori
"Hm?"

@Iori
"A black cat?"

@Akira
"Oh, hey there pretty kitty♪"

@Akira
"Come here girl~ Here girl!"

@"Black Cat"
"Meow."

@Akira
"There we go! Who's a good girl? Good kitty♪"

@Akira
"You look just like Ichi's pal."

@Akira
"Come on and give us a purr~ Purr, purr, purr♪"

@"Black Cat"
"*purr purr purr*"

@Akira
"Hey, didn't Ichi say something about his black cat buddy being a friend to the gods?"

@Akira
"Does that mean you're thick as thieves with them, too?"

@"Black Cat"
"Meow."

@Nodoka
"Aww, you're a friendly kitty, aren't you♪"

@"Black Cat"
"Meow."

@Nodoka
"Wishing on a black cat, huh...?"

@Nodoka
"I'm not the type to believe in stuff like that..."

@Nodoka
"But..."

@Nodoka
"Hey, kitty, would you pass on my wish to the gods?"

@"Black Cat"
"Meow."

@"Black Cat"
"Mew, mew!"

@"Black Cat"
"Mew, mew!"

@Ichinari
"Oh, hey, Blackie!"

@Ichinari
"I drank for the first time in ages today, so I'm kinda drunk—"

@"Black Cat"
"Just let me in, Ichinari."

@Ichinari
"..."

@Ichinari
"...Come again?"

@"Black Cat"
"I said let me in. I need to talk to you."

@Ichinari
"Uh..."

@Ichinari
"A cat...needs to talk to me..."

@Ichinari
"Uh, to me...?"

I'm kind of thrown for a loop, but for the time being, I decide to open the window. Blackie bounds into my room with her usual light step.

@"Black Cat"
"Ichinari, I'm in a bit of a pickle."

@Ichinari
"Umm..."

@Ichinari
"I'm in a lot of a pickle right now too."

@"Black Cat"
"Never mind that."

She licks her paw and starts to wash her face.

It's definitely a feline action.

And yet here she is totally talking down to me.

@Ichinari
"Well, I guess there're plenty of talking cats in manga..."

I must be drunker than I thought.

@"Black Cat"
"As I'm sure you're aware, I'm actually a messenger to the gods."

@"Black Cat"
"Oh, but that doesn't go for every black cat in the world, okay?"

@"Black Cat"
"Things have gotten a little out of hand, so I was sent to convey their words to you."

@Ichinari
"I see, so that's how it is, huh."

I nod knowingly.

@Ichinari
"So what's up? I don't have anything to feed you, if that's what you're after."

@"Black Cat"
"Could you take this a bit more seriously?"

@Ichinari
"Sorry."

I apologize out of reflex.

@"Black Cat"
"I owed a debt to you, so I passed your wish on to the gods."

@"Black Cat"
"But when we tried to grant it, it interfered with three other wishes."

@Ichinari
"It interfered with three other wishes?"

@Ichinari
"..."

@Ichinari
"...I have no idea what you're talking about."

@"Black Cat"
"Have you forgotten what you asked of me?"

@Ichinari
"What I asked of you...?"

@Ichinari
"Erm, I wished to be able to continue being a manga artist..."

@Ichinari
"...and to be happy, or something like that..."

@Ichinari
"Umm, are you telling me that..."

@"Black Cat"
"Yeah, that's the one."

@"Black Cat"
"You're able to continue being a manga artist, aren't you?"

Blackie twists around and starts grooming herself.

@Ichinari
"..."

@Ichinari
"...Huh? Are you serious?"

@"Black Cat"
"I'm serious. Are you even listening to me?"

@Ichinari
"C'mere girl, purr purr purr~"

@"Black Cat"
"Stop it. Now is not the time."

@Ichinari
"Sorry, I couldn't help myself."

She bats at my hand.

Well, it's true that, now I'm an assistant, I can continue working on manga for a living...

And in such an amazing environment, too. It does seem like it would've taken a miracle, but...

I stare intently at the talking cat before me.

@Ichinari
"Blackie, are you seriously in league with the gods?"

@"Black Cat"
"That's what I've been telling you."

@"Black Cat"
"You know that shrine outside?"

@"Black Cat"
"I have a position there similar to a shrine maiden."

@Ichinari
"What, you, a shrine maiden?!"

Not only is this cat a messenger to the gods, but she's supposedly a pure and holy shrine maiden? Pfft.

Oh, and then there's the talking thing, all while looking like just an ordinary cat. Isn't this going a bit far?!

@"Black Cat"
"Well this is my repayment for everything you've done for me."

@"Black Cat"
"So, you humans have these "Fates" that are a product of your everyday behavior."

Now she twists around the other way and starts grooming her opposite side.

She's so carefree...

Although it's not like this'd be any easier to swallow if she was being super serious.

But I guess if Blackie's saying my recent good luck is thanks to her, then I should be grateful.

Honestly, I'm too drunk to bother thinking about it that hard.

@"Black Cat"
"Because, well, you see..."

@"Black Cat"
"Even a god can't make a miracle from nothing."

@"Black Cat"
"So they alter your destiny by connecting these Fates together."

@"Black Cat"
"So I did as the gods asked, and searched for your Fate, but..."

@"Black Cat"
"As it turns out, you have three of them, and strong ones at that."

@"Black Cat"
"Actually, you created them yourself—you should be proud."

@Ichinari
"Uh, thanks, I guess?"

I still don't really know what the heck she's talking about, but I bow my head respectfully anyway.

@"Black Cat"
"Well, it would've made things easier for us if we could just merge them into one."

@"Black Cat"
"But we can't just ignore all these wishes and Fates and things, you see."

@"Black Cat"
"Even gods have their quotas to fill and their reputations to think about."

@Ichinari
"So being a god is like a regular job, huh?"

@"Black Cat"
"Well, you don't need to concern yourself with that."

@"Black Cat"
"But, anyway, we ended up with these three overlapping Fates for you."

@"Black Cat"
"So the gods decided we should just connect all of them up and let you deal with the fallout."

@Ichinari
"That sounds pretty irresponsible."

Let me deal with the fallout?

They may not be ignoring me, but isn't it just as bad?

If the gods are gonna grant my wish, they could at least see it through to the end.

Despite my inner thoughts, I pull out my cellphone.

@Ichinari
"By the way, can I take a video of you speaking?"

@"Black Cat"
"You really are an idiot."

@"Black Cat"
"We're talking about your destiny here. Could you take it a bit more seriously?"

@"Black Cat"
"Those Fates have already started coming together, and shaping your destiny—"

@Ichinari
"Check it out, I haven't washed these socks in a week."

@"Black Cat"
"GYAH! Stinky! EWWWWWWWW!"

@Ichinari
"Whoa, nice reaction."

@"Black Cat"
"Shaaaa! I'll rip you to shreds!"

@Ichinari
"Ow!"

@Ichinari
"Hey, put your claws away!"

@Ichinari
"I can't draw if you hurt my fingers!"

@Ichinari
"You say you'll grant my wishes, yet you're trying to take my future from me?!"

@"Black Cat"
"Like I care! Don't mess with a cat's sense of smell!"

@Ichinari
"Oh, you wanna go, do you? Let's do this, you and me, outside!"

@Ichinari
"I don't care if you're some godly messenger or what, to me you're just a regular old ca—"

@Ichinari
"...Huh?"

@Ichinari
"What's that? An earthquake?"

@"Black Cat"
"Oh, that's my signal."

@"Black Cat"
"Honestly, you wasted so much time with your idiocy."

@"Black Cat"
"Just as a final parting word..."

@"Black Cat"
"...I had fun with you."

@"Black Cat"
"But now it's time for you to make some real human friends."

@"Black Cat"
"Oh, and you should grab your wallet and cellphone and get the heck outta here. Laters."

With that, she leaps out of the window and disappears.

@Ichinari
"Hey! Blackie, wait a—!"

@Ichinari
"Huh?"

@Ichinari
"Is it just me or is the shaking getting stong—"

@Ichinari
"GYAAAAAAAAAAAAAAAAAAAAAAH!"

