#start|Connected Fates

@Ichinari
"Um, so, you see..."

@Ichinari
"The water pipe running directly beneath my apartment exploded..."

@Ichinari
"Which caused the apartment to collapse, and now I have nowhere to live..."

It's first thing in the morning the following day.

I'm explaining the situation to Iori at her office.

@Iori
"Huh? A water pipe exploded?"

@Iori
"A-Are you okay?! Were you hurt?!"

@Ichinari
"Oh, no, I'm completely fine."

I managed to get out with my wallet and phone intact. But everything else, including my computer, was completely destroyed.

No one is currently allowed into the half-collapsed husk of the building.

@Iori
"Ichinari, is your apartment..."

@Iori
"...this one, that's at the top of the news this morning?"

@Ichinari
"Yeah, that's the one."

There's a photo of a building blocked off by barrier tape. You wouldn't think a burst water pipe could cause such damage, but...

It was an old, dilapidated place that was already on the verge of falling down at any moment. It makes sense that the water pipes would have been old and rusting, too.

The rent was only 20,000 yen per month. In fact, I should probably appreciate the fact it stayed standing until now.

@Ichinari
"In any case, it doesn't seem like I'm going to be able to afford to rent anywhere else on my salary."

@Iori
"Huh? Isn't the landlord going to cover it for you?"

@Ichinari
"It looks like there's going to be an insurance payout, but..."

@Ichinari
"Well, look at the place. I doubt they'll get much."

@Ichinari
"Plus, they said it'll take some time."

During the three years I lived there, I'd been the only tenant.

Even though the rooms were pretty decent; providing you weren't bothered about bugs, draughts, and leaks.

And there were absolutely no security systems in place; but it's not like I had anything worth stealing anyway.

@Iori
"Um..."

@Iori
"So, do you want to stay here for now?"

@Iori
"I know it's a workspace, but there's a bathroom, and bedding, and all the basic things you'd need..."

@Iori
"I don't mind you staying here, until you find a new place to live."

@Ichinari
"Oh, no, I couldn't..."

@Iori
"You won't be able to work as my assistant without a place to live, right?"

@Iori
"And that'd make things difficult for both of us."

@Iori
"Plus..."

@Iori
"...I want you here."

@Iori
"I had a lot of fun with you yesterday..."

A faint blush spreads across her cheeks. She averts her gaze and fiddles with her fingers awkwardly.

@Ichinari
"Iori..."

My last storyboard was rejected, meaning my monthly manga serialization has been put on hold. Yet here Iori is, sticking her neck out for me.

I've also been informed that the editor-in-chief wants me to focus on the assistant job for a while.

Maybe I don't have what it takes to be a manga artist after all. If that's the case, then the least I can do is be of use to Iori.

@Ichinari
"Okay then... I guess I'll take you up on your kind offer."

@Ichinari
"I'm really, really sorry about all this."

@Ichinari
"But...I do want to be here, too."

@Iori
"Ichinari..."

@Iori
"Mm. It's no trouble at all."

@Iori
"In fact, I'm happy to hear that. Hee hee."

She shrugs my words off awkwardly. But at the same time, a giggle escapes her lips, and she smiles.

I'm constantly taking advantage of other people's kindness.

But if it hadn't been for Iori, my life would have been in real jeopardy...

@Ichinari
"Fates, huh?"

I guess what happened yesterday wasn't a dream. It's hard to believe in talking cats and stuff, but...

If this accident had occurred just a few days earlier, I would've been on a direct course back to my parents' house.

I honestly don't know if I would've been able to keep drawing manga back at home.

But with this string of good luck, it's actually way more convincing to put it down to a miracle from the gods.

@"Black Cat"
"So, you humans have these "Fates" that are a product of your everyday behavior."

@"Black Cat"
"Actually, you created them yourself—you should be proud."

Iori, Nodoka, and Akira-chan...

I'm living beholden to these people I'm connected to; whose fates have intertwined with mine.

@Iori
"Ichinari? What's wrong?"

@Ichinari
"Oh, nothing. I was just thinking how grateful I am."

I send a silent prayer of thanks for my connection to Iori.

@Iori
"You can't work without a computer, so..."

@Iori
"Shall we go buy you one now?"

@Iori
"I hadn't ordered one for you yet."

@Iori
"It'd be faster for us to go pick something up rather than ordering online."

@Ichinari
"I'm really, really sorry for everything."

@Ichinari
"Thank you so much."

@Ichinari
"Hmm, what should we go for..."

We're in Toyohashi Camera, a big electronics store next to Yokohama Station. I'm looking around the computer section together with Iori.

@Iori
"I don't really know much about computers..."

@Iori
"So why don't we just go for the newest model?"

@Iori
"The higher the specs, the better it'll be for work."

@Iori
"Although Nodoka's the one who really knows about this stuff."

@Iori
"She said a luddite like me couldn't go wrong if I just pick the newest, most expensive model."

@Ichinari
"I mean, that's probably true, but..."

The computer alone is 400,000 yen. A good monitor will set us back 100,000. And a graphics tablet will be another 200,000.

And that's not to mention the desk, chair, lights, and all that other stuff. Iori goes along picking up the purchase cards for each item without even blinking.

@Ichinari
"Umm, Iori...?"

@Ichinari
"We're already at at least 800,000 yen..."

@Iori
"Don't worry about that. It's a work expense."

@Iori
"My accountant told me I need to spend more on expenses anyway."

@Iori
"I don't usually have much reason to spend money myself."

Without a moment's hesitation, she picks an extension cord costing over 10,000 yen. Being a best-selling hentai manga artist must be awesome...

I've never seen someone shop like this. Nodoka-san, you should know that Iori is following your advice to the letter.

By this point I've stopped even trying to keep track of the figure. I just follow along meekly behind Iori.

@Iori
"Hm. This should do it."

@Iori
"If we're missing any little things, we can pick them up online later."

@Ichinari
"Yes. Indeed."

I nod mechanically, staring blankly at the unprecedented amount.

@Iori
"Okay, I'll leave it to you."

Iori holds out a credit card to me.

@Ichinari
"Huh?"

@Ichinari
"Umm, what do you mean?"

@Iori
"Huh? You've never seen a credit card before?"

@Ichinari
"No, I mean, I'm not THAT behind the times."

@Ichinari
"It's just, you're not supposed to go handing your credit card to strangers, are you?"

@Iori
"Well you're not a stranger, so it's fine."

@Ichinari
"No, that's not what I meant..."

@Iori
"..."

@Iori
"I don't like talking to people I don't know."

Oh, right. I forgot that Iori has really bad social anxiety.

I suppose god doesn't give with two hands, huh? It's kinda cute though—she reminds me of a cat who keeps its distance from humans.

@Ichinari
"What do you do when you go to the hairdressers or something?"

@Iori
"I get Nodoka to come with me."

@Iori
"And I pretend to be asleep while they're cutting my hair."

It seems Iori has her own struggles.

Filled with a warm, fuzzy feeling toward this tortured genius before me, I take Iori's credit card and head for the register.

@Ichinari
"They said they'll deliver the stuff later this evening."

@Iori
"Mm. It's good we've got it all sorted out."

I give Iori her credit card back, along with the delivery receipt.

@Ichinari
"I'm really sorry you had to spend all that money on me."

@Ichinari
"I'll try and make it worthwhile."

@Iori
"Not at all. I'm the one who hired you as my assistant."

@Iori
"If you're working for me, it's only fair I provide the equipment you need."

@Iori
"I bought everything for the workplace, including Nodoka's computer."

@Ichinari
"I guess you're right."

@Ichinari
"But, still, you really spent a lot of money on me."

@Ichinari
"So, I guess I shouldn't be saying 'sorry,' but rather..."

@Ichinari
"...'Thanks'?"

@Iori
"..."

@Iori
"Ugh, could you stop stop trying to act all cool..."

Iori blushes and purses her lips. I wasn't actually trying to act cool.

As I regard her blushing profile, I see the traces of her younger self in her face. It's such a nostalgic feeling, I can't help but smile.

@Ichinari
"You haven't changed at all."

@Iori
"Huh?"

@Ichinari
"I mean, I was just thinking, you've always been shy."

@Ichinari
"I remember when you first transferred to our school..."

@Ichinari
"...you were like this, too. I was just reminiscing."

@Iori
"Ichinari..."

@Iori
"Hee hee. You're right."

@Iori
"I haven't changed since then."

@Iori
"Not one bit."

@Iori
"And it's thanks to you that I am where I am now."

She's clearly embarrassed, but she keeps looking straight at me. She shows me a soft, gentle smile, the same as back when we were young.

@Iori
"You know, when I was little, I moved schools all the time."

@Iori
"But I was always too shy to make friends on my own."

@Iori
"Back then I was always alone, and it was really hard."

@Ichinari
"Iori..."

@Iori
"And then you..."

@Iori
"You showed me this manga you thought was really good, and let me borrow it."

@Iori
"We were both really into manga, so we started hanging out and drawing at each other's houses..."

@Iori
"And then we made a promise to become manga artists together."

@Iori
"You were my very first friend. I was so happy."

@Iori
"I was so happy that we had the same dream, to become manga artists."

@Iori
"After that I had to move schools again, but..."

She looks me straight in the eye.

Smiling her soft smile, she gives a slight nod.

@Iori
"I am who I am today because you spoke to me back then."

@Iori
"I didn't have the courage to say it at the time, but..."

@Iori
"Thank you."

@Iori
"I've been wanting to say that all these years."

Her smile is so open and natural, I feel like it's drawing me in.

She regards me intently.

@Iori
"I'm so glad I finally got to tell you."

@Iori
"It's been ten years coming. Hee hee."

@Ichinari
"Iori..."

@Iori
"So I'm just glad I could do something for you in return, however small."

@Iori
"I think it's nice that you're so grateful for everything, but..."

@Iori
"This is something I wanted to do for you."

@Iori
"Seeing you working hard on this will bring me joy."

Her warm smile and words make my heart clench in my chest.

Now it's my turn to blush. I find I can't quite look her in the eye.

@Ichinari
"You really don't owe me anything."

@Ichinari
"I'm really glad you feel that way, but..."

@Iori
"Not at all. At least, this is how I feel..."

@Iori
"If you hadn't encouraged me back then..."

@Iori
"...I probably never would have achieved my dream."

@Iori
"So it's all thanks to you that I am where I am right now. I truly believe that."

@Ichinari
"Iori..."

I stop walking and turn to face her head on.

@Ichinari
"It may be be true that I gave you a push in the beginning."

@Ichinari
"But the reason you made it as a manga artist..."

@Ichinari
"...is because you worked your ass off for it."

@Iori
"Ichinari...?"

@Ichinari
"I thought I was working hard too, but..."

@Ichinari
"You must have worked ten times harder."

@Ichinari
"And it shows in your manga."

@Iori
"Ichinari..."

@Ichinari
"I may not be on your level, but I am an artist, so I can tell."

@Ichinari
"I can tell that you've been working your ass off all these years, on no one's talent but your own."

@Iori
"..."

Her pretty eyes widen slightly, then she looks down at the ground like before.

She clasps her small hands together in front of her chest. That gesture, the way her slim fingers interlock tightly...

I can feel the unimaginable weight of her effort. I reach out to gently caress her head.

@Ichinari
"You've done really well, Iori."

@Iori
"Ichi...nari..."

@Iori
"I..."

She reaches both hands up to cup my cheeks, softly and gently.

I have no time to speak. Suddenly, I see her long, dark hair flutter as she leans in...

@Ichinari
"...!"

Time stands still.

I feel a soft sensation on my lips, followed by a sweet scent. Iori's face is right in front of mine, her eyes closed.

I can't make heads nor tails of what's happening. Then the pressure of her lips slowly pulls away.

@Iori
"I love you."

@Iori
"I've always loved you, Ichinari, since way back then."

@Ichinari
"Iori..."

@Iori
"I always knew I'd see you again..."

@Iori
"If I worked hard and kept our promise."

@Iori
"Because I knew you'd keep it too."

@Iori
"I made it this far because I always believed that."

Her cheeks are slightly flushed, but this time she doesn't look away. Instead, she shows me a sweet, gentle smile.

@Iori
"I told you, didn't I?"

@Iori
"That I haven't changed at all."

@Iori
"My dreams, and my feelings..."

@Iori
"They're all the same as they were back then, Ichinari."

@Ichinari
"Iori..."

Her words go straight to my heart. My chest feels tight.

My heart is pounding furiously. Earlier it'd felt like it was about to stop...

But now it's racing. Time, which had been frozen for one long moment, starts to move again.

@Iori
"Phew, I feel so refreshed after finally getting that off my chest."

@Iori
"Let's head back, shall we?"

@Iori
"If we don't hurry, the computer stuff will arrive before we do."

@Ichinari
"Uh... R-Right..."

My life has been all about chasing headfirst after my own dreams, so I'd assumed Iori was just like me in that regard.

It had never even crossed my mind that she'd been yearning to be reunited with me; not to mention that she'd been in love with me all these years.

She's so adorable, and as sweet and innocent as she was back then... No doubt I could fall for her, too.

That being said, am I even worthy of accepting her love?

@Iori
"Ichinari? Are you coming?"

@Ichinari
"Y-Yeah, sorry!"

I'm still in somewhat of a daze as I reply to her.

I hurry along to where Iori's waiting for me.

How should I respond to her confession?

@Nodoka
"A burst water pipe, huh? That sounds really bad~"

@Nodoka
"But the most important thing is that you're okay."

@Nodoka
"Right, Iori-san?"

@Iori
"Huh?"

@Iori
"O-Oh, yeah... R-Right."

@Iori
"It's really good that...Ichinari's okay..."

@Iori
"*glance*"

@Ichinari
"Y-Yeah... It sure is..."

@Ichinari
"It's great that I wasn't hurt... It really is..."

@Nodoka
"???"

As we assemble the speedily-delivered desk and set up the computer...

...the mood between myself and Iori is totally awkward.

@Iori
"..."

@Iori
"*glance*"

@Iori
"Ah!"

@Ichinari
"..."

After Iori had suddenly confessed her love and kissed me, the moment to respond had completely passed me by, and now I'm stuck.

Iori being Iori, she'll just run off the moment I try and make eye contact. Not that I have any experience with this kind of thing either.

The strained mood in the office shows no sign of abating.

@Ichinari
"Um... Iori?"

@Iori
"Oh, s-sorry!"

@Iori
"I just remembered I have an appointment, so I'm going to head home for today!"

@Iori
"Oh, a-and, Ichinari? Here's a duplicate key for you."

She extends her hand to me, seemingly from across a vast gulf, and hands me an extra keycard to the workplace.

@Iori
"There's a futon and bedding in the back room."

@Iori
"You're free to use anything that's here."

@Ichinari
"Thanks, I appreci—"

@Iori
"O-Okay, see you tomorrow!"

@Ichinari
"...Haa."

I watch Iori disappear through the front door and continue to stare at it after it's closed behind her.

I definitely deserve for Akira-chan to call me a loser...

But I don't want things to stay weird between us... What should I do...?

@Nodoka
"Um, Senpai...?"

@Nodoka
"Did something happen between you and Iori?"

@Nodoka
"Things seem kinda awkward between you two..."

@Ichinari
"Uh, well, I guess you could say that..."

@Ichinari
"I guess that's how it looks, yeah."

@Ichinari
"Hmm... Hmmm..."

@Nodoka
"???"

I can't exactly talk to Nodoka about it.

She tilts her head at me as I mutter to myself with my arms folded.

@Nodoka
"Umm, well how about this..."

@Nodoka
"Why don't we go grab dinner, once we've finished setting up your PC?"

@Nodoka
"Iori's already gone home anyway."

@Nodoka
"Oh, and I'll pay, so you don't have to worry about that."

@Ichinari
"Thanks. I'd really, really appreciate that."

There's no point in continuing letting this get to me. I decide to take Nodoka up on her offer and let her treat me to dinner.

@Ichinari
"Thank you sooo much, Nodoka-sensei!"

@Ichinari
"I'll treat you in return once I get paid!"

Putting my hands together, I bow to her in a show of gratitude.

@Nodoka
"He hee. It's no big deal, seriously."

@Nodoka
"I might not earn as much as Iori-san, but I'm definitely doing okay for myself."

She strikes a cute, flexed arm pose. Right—her dōjinshi was the number one seller at Tomato Books.

I wonder how many times higher her income is than mine.

While I'm feeling sorry for myself, we slowly wind our way through the park, illuminated by street lights.

@Ichinari
"You've gotten so good at drawing."

@Ichinari
"Even though you were just a beginner back in high school."

@Nodoka
"Hee hee. That's because I had a wonderful teacher."

@Nodoka
"I kept practicing even after you graduated."

@Nodoka
"But, you know, hearing that from you now..."

@Nodoka
"...makes it worth all the hard work I put in, for the day I met you again."

She peers up at me from my side, a mischievous smile playing across her lips.

She's really changed.

She used to be so shy; but now, these flirtatious gestures seem like her second nature. It's all extra impressive to me, since I know what she was like before.

@Nodoka
"Hey, Senpai."

@Nodoka
"Why don't we have a little rest on that bench over there?"

@Nodoka
"The breeze feels really good tonight."

@Nodoka
"Could you sit with me while I sober up a bit?"

@Ichinari
"Sure thing. Let's go sit down."

I sit down on the bench Nodoka had suggested.

We sit in silence for a while. I look up at the night sky, enjoying the pleasant feel of the wind on my skin.

@Nodoka
"You know, it really doesn't feel like we were ever apart."

@Nodoka
"There were so many things I wanted to say if I saw you again, and yet..."

@Nodoka
"Now that you're actually here, it's like it's all slipped my mind."

@Nodoka
"Somehow, just being able to see you again is enough. Hee hee."

The breeze stirs her silky golden hair as her giggle tinkles in my ear like bell.

@Ichinari
"Yeah, I get what you mean."

Even though it's been three years between when I graduated and now...

...there's no sense of distance between us. In fact, I feel natural and comfortable around her.

@Nodoka
"We used to walk home together like this in high school too."

@Ichinari
"Well, we were the only two club members."

@Nodoka
"And after you graduated, it was just me."

@Ichinari
"No new students joined?"

@Nodoka
"Nope. Although I didn't really try and recruit anyone."

@Ichinari
"Weren't you lonely on your own?"

@Nodoka
"Not really. I was too busy practicing every day~"

@Nodoka
"You could have kept in touch, you know?"

@Ichinari
"I told you, I'm really sorry about that."

@Nodoka
"And I told you, I'm not going to forgive you. Tee hee."

The mood between us is relaxed. It feels nice to enjoy this light banter again.

It's like we're back in high school. I gaze at Nodoka as I fondly think back on the past.

@Ichinari
"You've really changed on the outside..."

@Ichinari
"...but you're still the same Nodoka on the inside."

@Nodoka
"Hee hee. Of course I am."

@Nodoka
"I'll always be me, even if I look a little different."

She sweeps her long hair back from her face, her wide eyes narrowing as she smiles.

@Ichinari
"Nodoka..."

@Ichinari
"You said you'd worked hard at a lot of things..."

@Ichinari
"But why did you work so hard?"

@Nodoka
"You want to know?"

@Ichinari
"If it's something you're comfortable sharing."

@Nodoka
"Hmm, let's see."

She taps her index finger against her delicate chin. Then she looks up at the sky, seemingly deep in thought, before turning back to me.

@Nodoka
"Yeah, I guess I can tell you now."

Blushing slightly, she tilts her head to the side and smiles at me.

@Nodoka
"I don't really have much confidence in myself, you know."

@Nodoka
"I know you wouldn't think so from my personality, but it's true."

@Nodoka
"And because of that, I was left with the regret of not being able to say what I wanted to."

@Ichinari
"Regret?"

@Nodoka
"Yes. There's something I've regretted every day, for these last few years."

@Nodoka
"And so I thought that, if I changed myself, and became more confident..."

@Nodoka
"...then, if I found myself in the same position again, this time I'd come away with no regrets."

@Nodoka
"And so I worked hard to change."

@Nodoka
"To change my manga, my looks, my personality."

Nodoka stares down at her hands as she speaks. There's a gleam of sadness in her narrowed eyes.

@Ichinari
"So doesn't that mean you have that confidence now?"

@Nodoka
"I wonder about that..."

@Nodoka
"I get the feeling that's not the case."

@Nodoka
"No matter how hard I tried to change..."

@Nodoka
"...like you just said, I'm still the same person on the inside."

@Nodoka
"Maybe, if the same thing happens again, I still won't have the courage."

She gives me a troubled smile. Then she cheekily sticks her tongue out at me.

@Ichinari
"You'll be fine, Nodoka."

As I watch her, looking sad and unsure, I find myself instinctively reassuring her.

@Nodoka
"Senpai...?"

Her eyes widen slightly as she turns to face me fully.

@Ichinari
"I can't even imagine how much effort you've made."

@Ichinari
"I really didn't recognize you when we ran into each other; that's how beautiful you've become. And my heart pounded so hard when you were teasing me."

@Ichinari
"I didn't recognize your manga either. I've been a big fan of Nagomi-sensei's work from the beginning..."

@Ichinari
"But even as someone who knew you from high school, I couldn't tell it was you who'd drawn it."

@Ichinari
"So you'll be fine. You've changed; you've grown into someone truly special. You won't repeat those same regrets again. "

@Ichinari
"I guarantee it."

@Nodoka
"Senpai..."

A soft smile blooms across her face and her eyes narrow happily, tears glistening in their corners.

Ahh, she's so cute when she smiles like this.

@Ichinari
"Sorry, I guess I fell back into my senpai role there, even though it's not my place..."

I scratch my head, pulling a wry smile to hide my embarrassment.

@Nodoka
"No, not at all."

@Nodoka
"I'm so...so happy to hear that from you, Senpai..."

@Nodoka
"Because it's from you in particular...I..."

Her slim fingers cup my cheek.

@Ichinari
"...!"

A soft sensation brushes my lips.

A moment later, I feel the warmth of Nodoka's lips on mine. I can feel her breath on my lips and the warmth of her body slowly seeping into me through her fingertips.

@Nodoka
"I found the courage not to leave any regrets."

@Ichinari
"Nodo...ka..."

The moonlight glows across her blushing face.

I can't seem to form words. All I can do is stare at her in amazement.

@Nodoka
"I've always loved you, Senpai."

@Nodoka
"My regret was not being able to tell you that before you graduated."

@Nodoka
"And so I vowed that, if I ever met you again..."

@Nodoka
"...I'd tell you how I felt that time, for sure."

@Nodoka
"That thought kept me going."

She doesn't look away from me. She looks straight into my eyes, as though searching for something.

@Ichinari
"Nodoka..."

@Nodoka
"I still don't have confidence in myself, but..."

@Nodoka
"I believe in you. And you believe in me."

@Nodoka
"I tried my best, so that I wouldn't have any regrets this time around."

She sticks her tongue out slightly, giving her an impish look. Then she flashes me a V sign.

She giggles to herself again before getting up from the bench and turning to face me.

@Nodoka
"That was my first kiss, you know?"

@Nodoka
"Because you're the only man I've ever loved."

@Nodoka
"I've been in love with you all these years, Ichinari-senpai."

@Nodoka
"I'll be heading home now."

@Nodoka
"See you later."

She dips her head to me. Then she leaves, walking off at a quick pace.

When her swaying blonde hair is finally out of sight, I remember to breathe again and slump back onto the bench.

@Ichinari
"...Are you kidding me?"

I'd honestly had no idea Nodoka felt this way about me...

I'm extremely flattered that she's worked so hard on herself, and her dōjin, all in the hopes of being reunited with me one day.

But...I have the same doubts as I had with Iori. Am I worthy of Nodoka's love?

I've spent all these years focusing only on my own dreams, forgetting the promises I'd made to others...

@Ichinari
"Guess I should head home, too."

My mind is a complete mess. But for the time being, I decide to go back to Iori's workplace.

@Akira
"Hey guuuuuys! Been working hard, or hardly working?!"

@Akira
"...Huh? Huh?"

@Akira
"It's just you, Ichi? Where's everyone else?"

Akira-chan swivels her head, looking around the empty room. I look up at her from where I'm slumped on the sofa.

@Ichinari
"Iori and Nodoka have already gone home for today."

@Akira
"Whaaat? On your first day? They're making you do overtime alone?"

@Ichinari
"No, I'm not actually working..."

I look away.

@Akira
"Hm? Hmmm?"

@Akira
"Ichi, you seem kinda down in the dumps. What's up?"

@Akira
"Did you mess up on your very first day?"

@Akira
"If there's anything bothering you, you can talk to Onee-chan about it."

@Ichinari
"Don't worry, I didn't do anything wrong this time."

@Akira
"Come and tell Onee-chan all about it."

@Ichinari
"Hey, Onee-chan, you're getting way up in my personal space!"

Her sweet, feminine scent washes over me. I rush to regain the distance between us.

@Akira
"Ahaha! Are you blushing?"

@Akira
"What's got you so riled up? It's always like this between us."

@Akira
"You've come up with some really cute new reactions, Ichi~♪"

@Ichinari
"No, it's not like that..."

The kiss I just experienced pops back into my mind. My gaze is drawn to Akira-chan's lips... This is Not Good.

This is Not Good in a way that could have a serious impact on my working life. I mean, I haven't even responded to Iori or Nodoka yet...

@Ichinari
"Haaaa~~~"

Holding my head in my hands, I breathe out an exaggerated sigh.

@Akira
"...Seriously, what's up?"

@Akira
"I'm seriously worried about you, you know?"

@Akira
"If there's something bothering you, you should talk to me about it."

@Akira
"I may be your editor, but..."

@Akira
"Before all that, I'm your onee-chan. 'Kay?"

@Ichinari
"Akira-chan..."

@Ichinari
"..."

@Ichinari
"I was just thinking, since when did my life become so precarious? Ahaha."

I cut myself off from saying anything more with a dry chuckle.

@Akira
"Precarious? Hmm?"

Akira-chan's brow furrows. She shakes her head from side to side, muttering to herself.

I can't possibly talk about this, even to Akira-chan. She'd probably just ask me if this was some new manga scenario I was concocting.

I also don't want her to worry about me even more.

But, for real, what am I going to do tomorrow? I clutch at my head, agonizing internally.

@Akira
"Umm... Ichi?"

@Akira
"I don't really know what's going on with you, but..."

@Akira
"You seem stressed out, so why don't you go on home?"

@Akira
"Iori-chan and Nodoka-chan have already left."

@Akira
"And it's not like you're going to get any work done in this state."

@Ichinari
"Oh, right."

@Ichinari
"I forgot to tell you..."

@Ichinari
"Actually, a water pipe burst underneath my apartment and completely destroyed the building."

@Akira
"You idiot! Why didn't you come straight to me?!"

@Akira
"Are you injured?! Are you hurting anywhere?!"

@Akira
"Have you contacted your parents? The police?! Is your head okay?!"

@Ichinari
"Calm down. My head's fine."

@Ichinari
"It's already been twenty-four hours, so everything's fine now, okay?"

I console Akira-chan, who has tears in her eyes.

@Akira
"You're so stupid! I'm just finding out NOW, so of course I'm freaking out!"

@Akira
"If something had happened to you, it would've been too late! Ugh, you big idiot!"

@Akira
"Ahh, but I'm so glad you're okay! Ichi! Ichiiiii!"

@Ichinari
"Hey, Aki—! I can't breathe...!"

@Ichinari
"And your boobs...! They're pressing right up against me... Gah!"

@Akira
"How can you be thinking about THAT at a time like THIS, doofus!"

@Akira
"You must have been so, so scared! You poor little thing!"

@Akira
"You're okay now! Waaaah, you big stupid idiot doofus!"

Half in tears, Akira-chan crushes me between her arms in a bear hug. She's clearly super worried about me.

@Ichinari
"Akira-chan..."

She really cares about me.

If it weren't for Akira-chan, I'm sure I would've given up on this job long ago.

The reason I've been able to keep going, despite lackluster sales, is because I've had Akira-chan by my side.

The truth of it is brought home to me all over again. I pat Akira-chan's hand as she continues to embrace me.

@Akira
"You've really had it rough, Ichi."

@Akira
"With no house and no money, you must've thought you'd have to give up on your dream of being a manga artist."

@Akira
"But you needn't worry about that, 'kay?"

@Akira
"Onee-chan's here for you, so you'll be okay."

@Ichinari
"Uh, well..."

That's actually totally not the case. But it's not like I can tell her about what happened with Iori and Nodoka.

Not when she's showering me with such concern. Besides, it's something I have to come to a decision about on my own.

I'm so sorry I can't tell you anything, Akira-chan.

@Akira
"Why don't you come stay with me?"

@Akira
"I only have a one-room apartment, like yours, but..."

@Akira
"I'd be fine sharing it with you, Ichi."

@Akira
"I'm not just here to look out for you as your editor, you know."

@Akira
"When I see you working so hard..."

@Akira
"...it encourages me to do my best too."

@Akira
"So you're more than welcome to rely on your onee-chan, 'kay?"

@Ichinari
"Akira-chan..."

@Akira
"I'm not just joking around when I say I can make you a kept man."

@Akira
"C'mere."

With a big smile on her face, she opens her arms wide to me.

@Ichinari
"Akira-chan..."

I'm about to jump into them, almost out of reflex, but I hold myself back.

I feel like it'd be wrong to take advantage of Akira-chan's kindness right now.

@Ichinari
"Thanks, Akira-chan."

@Ichinari
"But I don't need that right now."

@Akira
"Why not?"

@Akira
"I'll even let you have a proper nuzzle today."

@Ichinari
"Seriously?"

No! Bad me! This isn't the time for that, Ichinari!

I shake my head, like I'm shaking off the temptation.

@Ichinari
"No, um, Akira-chan..."

@Ichinari
"I can't let myself be spoiled by you right now, okay?"

@Ichinari
"There are times when a man just can't indulge himself like that, you know?"

@Ichinari
"And I'm not worthy of your pampering right now."

@Akira
"Ichi..."

@Akira
"..."

@Ichinari
"..."

@Ichinari
"...Huh?"

@Ichinari
"A-Akira-chan...?"

@Akira
"...Idiot."

@Ichinari
"Huh?"

I peer into her face as she hangs her head.

@Akira
"YOU MASSIVE FUCKIN' IDIOT!"

@Akira
"You're such an idiot, Ichi! The biggest idiot! The biggest idiot in the whole world! Idiot!"

@Ichinari
"Whaaat?!"

@Ichinari
"Wh-What did I do, Akira-chan?!"

@Akira
"Why would you say that?!"

@Akira
"You ARE a loser, Ichi! A real loser! You're SO useless!"

@Akira
"So useless that your name comes up every editorial meeting on the Uh-Oh Authors list!"

@Ichinari
"Wait, I'm in that dangerous a position? Seriously?"

@Akira
"But you work so hard! You try your very, very best!"

@Akira
"And that's great! That's the great thing about you, Ichi!"

@Akira
"Which is why I want you to achieve your dreams, even if it means me looking after you!"

@Ichinari
"Akira-chan..."

She's shouting the words in a tone I've never heard from her before. Her wide eyes are filled with glossy tears.

Crap. She's working herself up into a lather all over a misunderstanding.

But knowing she feels this way about me, I feel the corners of my own eyes start to prickle hotly.

@Akira
"There are a lot of times when I struggle with work, too."

@Akira
"Of course I work overtime, my salary's low, and I never get reimbursed for expenses!"

@Akira
"But because I get to see you working so hard..."

@Akira
"...I realize that I have to work hard too, and I'm able to give it my all!"

@Akira
"If it weren't for you, I wouldn't be able to smile through it all!"

@Akira
"So I don't want you to give up over this."

@Akira
"I believe, more than anyone else, that you're going to make it."

Akira-chan curls her small hand into a tight fist. She looks like she's desperately trying to hold back her tears...

...but she loses the battle, and they start to trail down her cheeks in fat drops. Yet she still doesn't avert her gaze from mine.

@Ichinari
"Akira-chan..."

She cares about me so deeply. She does so much more for me than her work role requires of her.

I reach out my hand toward her cheek and gently wipe away her tears.

@Ichinari
"If it weren't for you, I would have given up long ago."

@Ichinari
"When I had to redraw entire stories, when I missed out on getting serialized..."

@Ichinari
"When I couldn't sell any copies of my anthology..."

@Ichinari
"You always cheered me up and encouraged me."

@Ichinari
"The reason I've been able to work so hard..."

@Ichinari
"...is because I've always had you by my side, supporting me."

@Akira
"Ichi..."

@Ichinari
"I promise I won't give up."

@Ichinari
"So don't cry, okay?"

@Ichinari
"If I can't see your smiling face, I'll lose my drive too."

As I speak, I stroke her head in the same way as she does for me.

@Akira
"Ichi..."

@Akira
"You're being so kind to me..."

@Akira
"I just..."

@Ichinari
"...!"

I feel lips, soft against my own. Then, her slender arms, wrapped around my neck.

And, a moment later, the warmth of her body against mine.

Her bangs feather softly across my brow.

The distance between us closes to nothing, and then she slowly pulls back again.

@Akira
"I'm sorry."

@Akira
"I just couldn't stop myself."

@Akira
"Not when you were saying things like that. Hee hee."

She giggles with a soft smile I've never seen on her before.

It's like there's a different woman before me, smiling gently at me.

@Akira
"You're such a loser you probably haven't noticed, but..."

@Akira
"I've...been in love with you for a long time, you know?"

@Akira
"I wouldn't hug you or let you sleep in my lap if I didn't feel that way about you."

@Akira
"I wouldn't say things about marrying you if I didn't have feelings for you."

@Akira
"And I wouldn't be able to support you like this if I didn't love you."

She gently caresses my cheek, as though memorizing the curve of it. Her eyes narrow affectionately as she gazes at me.

@Ichinari
"Akira-chan..."

In a daze, I murmur her name. That seems to snap her back to her senses, as she suddenly covers her face with her hands.

@Akira
"Wh-What am I doing...?!"

@Akira
"I-I'm sorry...! I just...!"

@Akira
"You were being so cute... I just moved without thinking...!"

@Akira
"...!"

@Akira
"Y-You'll be staying here tonight, right?"

@Akira
"So I'd better be getting home! Bye!"

@Ichinari
"Ah, wait...!"

@Ichinari
"Akira-cha—!"

@Ichinari
"..."

@Ichinari
"Are you kidding me?"

This is the most unexpected of unexpected developments. I slump down onto the sofa.

@Ichinari
"A message?"

I pull my cellphone out of my pocket.

@Akira
"I meant what I said."

@Ichinari
"Seriously, what am I meant to do with that?!"

@Ichinari
"What am I meant to do with all of this?!"

I slide off the sofa and onto the floor. Then I proceed to roll around while yelling incomprehensibly. GYAAAAAAAH!

I have zero experience with relationships and zero friends to go to for advice!

Too many good things are stacking up on top of me, I'm being crushed...! GyyyAAaaaaAAAaaaaAAAaaaAAAhhhhh!

@Ichinari
"Haa..."

After I've burned myself out, I gaze emptily into the distance as I mutter to myself.

@Ichinari
"Are real-life harems seriously this stressful...?"

Iori, Nodoka, Akira-chan. I recall their confessions.

@Iori
"I always knew I'd see you again..."

@Iori
"If I worked hard and kept our promise."

@Iori
"Because I knew you'd keep it too."

@Iori
"I made it this far because I always believed that."

When I first saw Iori again, I felt an emotion I can't put into words.

Perhaps our reunion has come as a result of never giving up on pursuing our dreams...

@Iori
"My dreams, and my feelings..."

@Iori
"They're all the same as they were back then, Ichinari."

Now I know that Iori has loved me since ever since then, and that she's been yearning to see me again all this time.

All these years, she's held on to our promise. Her innocent purity strikes me like an arrow straight to my heart.

@Nodoka
"I've always loved you, Senpai."

@Nodoka
"My regret was not being able to tell you that before you graduated."

@Nodoka
"And so I vowed that, if I ever met you again..."

@Nodoka
"...I'd tell you how I felt that time, for sure."

@Nodoka
"That thought kept me going."

I didn't notice Nodoka's feelings for me either, even though we hung out in the same club every day.

@Nodoka
"I still don't have confidence in myself, but..."

@Nodoka
"I believe in you. And you believe in me."

@Nodoka
"I tried my best, so that I wouldn't have any regrets this time around."

When I encountered Nodoka again after all these years, she'd blossomed into a beautiful young woman. My heart races when I'm around her.

She changed herself in order to convey her feelings to me... The thought makes me so happy, I want to respond in kind.

@Akira
"There are a lot of times when I struggle with work, too."

@Akira
"Of course I work overtime, my salary's low, and I never get reimbursed for expenses!"

@Akira
"But because I get to see you working so hard..."

@Akira
"If it weren't for you, I wouldn't be able to smile through it all!"

@Akira
"I believe, more than anyone else, that you're going to make it."

Akira-chan has been taking care of me ever since I started my career.

She supported a worthless loser like me, in both my work and my personal life.

@Akira
"I've been in love with you for a long time, you know?"

@Akira
"I wouldn't hug you or let you sleep in my lap if I didn't feel that way about you."

@Akira
"I wouldn't say things about marrying you if I didn't have feelings for you."

@Akira
"And I wouldn't be able to support you like this if I didn't love you."

I constantly relied on her help, never once imagining that she felt that way about me.

Since I always thought she saw me as nothing more than a little brother, her confession came as a big surprise to me...

But as a grown man, I want to meet her expectation.

This isn't working. The more I think, the more I realize just how happy their feelings make me, and how much I value them. I can't possibly pick just one.

On the other hand, I don't want to hurt them by being dishonest...

When it comes down to it, am I even worthy of accepting their love?

@Ichinari
"Up until now, I've barely even had a connection with a woman, let alone a romance." 

@Ichinari
"...Connection?"

I just heard that word yesterday. Erm, what was it that Blackie said again?

The gods don't work miracles, but if they have your "Fates," they can connect them together...?

@Ichinari
"Hm?"

@Akira/Iori＆Nodoka＆Akira
"A water pipe in my house burst..."

@Iori
"I didn't lose my entire house, like you, Ichinari, but..."

@Nodoka
"My house is flooded, so I can't really stay there..."

@Akira
"They said the repairs are gonna take a while, so..."

@Ichinari
"Are you kidding me?!"

In the space of one day, we've all been made homeless. And what are the odds that a water pipe would burst in everyone's place...?

If this is really the work of a god, then it's totally sloppy. Surely there was a better way of doing this?

Like, seriously, what are they doing? These gods don't have any creative talents.

@Akira/Iori＆Nodoka＆Akira
"...""...""..."

@Ichinari
"..."

But, as it stands, the mood here is a more pressing issue.

I was already worrying about how to face each of them tomorrow. And now here we are, forced together by the violent hands of fate.

All four of us are searching for words and coming up empty-handed, tapped in this oppressively awkward atmosphere. If only there were someone else here to—

@"Black Cat"
"Meow."

@Akira/Iori＆Nodoka＆Akira
"Huh?""Huh?""Huh?"

Everyone turns to look at the window.

@"Black Cat"
"Meow."

@Ichinari
"Huh? Blackie?"

Blackie is outside the window, as usual, scratching to be let in.

@Iori
"Blackie? Is that your pet cat?"

@Ichinari
"No, she's not mine, she just lives around my apartment block."

@Akira
"She's like your best friend, so maybe she followed you here?"

@Iori
"But pets aren't allowed in this building."

@Nodoka
"Forget about that—this is the 29th floor, isn't it?"

@Nodoka
"How on earth did she get up here?"

@Akira
"On the strength of her desire to see Ichi?"

@Nodoka
"Ooh, how romantic!"

@Nodoka
"That really gets my imagination going♪"

@Ichinari
"Uh, that explanation makes sense to you?"

Wow, the power of her imagination is really something.

Must make life easier, having a brain wired like that.

@"Black Cat"
"Mew, mew."

@Nodoka
"Anyway, we can't just leave her out there."

@Iori
"No, you're right. Let's let her in, shall we?"

@"Black Cat"
"Whoa, I really thought I was gonna fall to my death during that climb."

@"Black Cat"
"Yo, Ichinari. Could you get a girl some milk? I'm thirsty."

@Akira
"She talked! Blackie just talked?!"

@Akira
"What the heck? Is this some kinda new species of cat?!"

@Akira
"And she asked for milk, Ichi! Go get her some kitty milk!"

@Ichinari
"We don't have any of that stuff."

For the time being, I head to the kitchen to get her some water.

@Iori
"Umm..."

@Iori
"You sure have some odd friends, Ichinari."

@Nodoka
"Mhm, that's Senpai for you."

@Nodoka
"Oh, do you mind if I take a video?"

@"Black Cat"
"I'd rather you didn't. It'd make things difficult for me."

Everyone's taking this in their stride unexpectedly well. I suppose they're all unconventional people, in their own ways.

Still marveling at how open-minded they are, I place a shallow bowl of water in front of Blackie.

@"Black Cat"
"Now, allow me to explain. *glug*"

@"Black Cat"
"I'm here as a messenger of the gods. *lap*"

@"Black Cat"
"Usually I'm a regular old non-talking cat, you see. *slurp*"

@Ichinari
"Could you not drink while you're trying to talk?"

I wipe up the water she's splashed all over the floor.

@"Black Cat"
"Phew, that's better. Thanks."

@"Black Cat"
"So, I told all this to Ichinari yesterday, but..."

@"Black Cat"
"Since things have escalated, I figure I'd better fill you all in."

@"Black Cat"
"So this god told me to tell you that all your wishes have been heard, and your Fates have been connected."

@"Black Cat"
"And that the rest is up to you to decide."

@"Black Cat"
"Oh, and that they won't be getting involved with the result, so please don't come crying to them."

While washing her face with her paw, Blackie delivers the same explanation as she had yesterday.

@Ichinari
"'All of your wishes'...?"

@Ichinari
"Huh? So this isn't just about me?"

@Akira/Iori＆Nodoka＆Akira
"...""...""..."

@Ichinari
"Huh?"

None of them will look at me.

@Iori
"So this means that you, Blackie..."

@Iori
"You're really a messenger of the gods?"

@Nodoka
"And everything that's happened since yesterday is their work?"

@Akira
"And that, um, me doing something so forward was because of that, too?"

@"Black Cat"
"That one was on you. All of you."

@Akira/Iori＆Nodoka＆Akira
"...""...""..."

@"Black Cat"
"Well, humans are prone to letting themselves get carried away in the moment."

@"Black Cat"
"Still, there was no real harm in it, so what's the problem?"

@"Black Cat"
"None of you were exactly against kissing him, were you?"

@Akira/Iori＆Nodoka＆Akira
"...No.""...No.""...No."

@Ichinari
"Hm? Hmmm?"

I look between Blackie and the others, not quite sure what's going on.

@"Black Cat"
"It looks like the girls already get it, but you, Ichinari..."

@"Black Cat"
"You really are pretty dense."

@"Black Cat"
"Which is why it feels like yo-OOOWWW DON'T PULL MY WHISKERS YOWWW!"

@Ichinari
"Sorry, sorry. I just got kinda annoyed and couldn't help myself."

I let go of Blackie's whiskers.

@"Black Cat"
"Honestly, is that how you treat the cat who's granting your wishes?"

@"Black Cat"
"To cut a long story short, these Fates that are going to make your wishes come true..."

@"Black Cat"
"...are your connections with these women."

@Ichinari
"Erm..."

@Ichinari
"Which means...?"

@"Black Cat"
"You really are an idiot."

@"Black Cat"
"Which means, that the granting of your wish..."

@"Black Cat"
"...coincides perfectly with these three's wishes."

@"Black Cat"
"That's what we call Fates being aligned."

@"Black Cat"
"You're the one who told these three about me, aren't you, Ichinari?"

Blackie swipes at her whiskers. Then she points her paw at Iori, Nodoka, and Akira-chan in turn.

It's true that I'm the one who told them about Blackie, but...

@"Black Cat"
"Like I said yesterday, it's your personal virtue that you have several such strong Fates."

@"Black Cat"
"What it all comes down to is that your wish to continue your work and live a happy life..."

@"Black Cat"
"...and their wishes to bang you are in perfect alignment."

@Iori
"I-I never said anything about banging anyone! Don't make things up!"

@Nodoka
"What she said! I mean, it's the logical extension, but still!"

@Akira
"There's more to it than that! Don't make light of a girl in love!"

@"Black Cat"
"Pffft. You're still calling yourself a girl at your age?"

@Akira
"I'll kill you, cat! I'll flay you and turn your skin into a shamisen!"

@Ichinari
"Calm down, Akira-chan! I don't wanna see my onee-chan sink to such a level!"

I grab her arms and pin them behind her back.

@"Black Cat"
"Well, all I did was give you a little push toward honesty..."

@"Black Cat"
"...in exchange for granting your wishes, you see."

@"Black Cat"
"But I didn't force you into doing anything you didn't want to do yourselves."

@"Black Cat"
"Look inside yourself, and you'll see I'm right."

@Ichinari
"Honesty...?"

Blackie starts grooming herself, looking like the cat who got the cream. Um, so all this means...

It's true that all three women have been in love with me for a while now...

And all three of them made wishes, like I did...

And all of them wished...to date me...?

@"Black Cat"
"Meow."

Blackie mews, like she can read my thoughts.

@Ichinari
"Umm, so what you're saying is that I..."

@"Black Cat"
"I already walked you through it."

@"Black Cat"
"Your Fates have come together just as you wished, so now it's up to you."

@Ichinari
"Right. You're shirking all responsibility."

I may as well just accept that it's all exactly as Blackie said.

@Iori
"Well..."

@Iori
"Then there's not much we can do about it, is there?"

@Nodoka
"Nope. Nothing at all."

@Akira
"Right. We can't do anything, can we."

They all nod, seemingly satisfied with this explanation.

@Ichinari
"Huh? Wait, what?"

@Ichinari
"You guys..."

@Ichinari
"Aren't you being a bit TOO understanding about all this?"

@"Black Cat"
"Because they're all at their most honest right now."

@Ichinari
"Maybe, but still! You just be quiet a minute!"

Blackie leaps nimbly away.

@"Black Cat"
"My 'little push' will fade away once your Fates are properly resolved."

@"Black Cat"
"Now it's up to you. Good luck."

@"Black Cat"
"See you around."

With that, she deftly opens the window with her front paws, then disappears outside without a sound.

@Ichinari
"...You've got to be kidding me."

I mutter to myself, completely flabbergasted. I gaze blankly after my feline friend, who's already vanished from view.

@Iori
"Ichinari..."

I turn toward her voice.

@Nodoka
"Senpai..."

@Akira
"Ichi..."

They're all blushing and fidgeting as they gaze right at me.

@Ichinari
"Um... Well..."

@Ichinari
"I guess that's just kinda how it is?"

@Iori
"I guess it is."

@Nodoka
"If you think of these past two days as all being god's work, it does kind of make sense."

@Akira
"Although I'm not sure how I feel about you not telling me about what happened with Iori-chan and Nodoka-chan, Ichi."

@Ichinari
"Uh, well, that was..."

@Ichinari
"I wasn't hiding anything. I just hadn't had time to get my thoughts straight yet..."

@Akira
"Ichi?"

Akira-chan places a gentle hand on my shoulder.

@Akira
"Rather than apologizing, you should be taking off your pants, Ichi."

@Ichinari
"..."

@Ichinari
"I'm sorry? What was that?"

Akira-chan smiles at my question.

@Akira
"I want to see your cock, Ichi."

@Iori
"Oh, me too."

@Nodoka
"I wouldn't mind getting a peek either♪"

@Ichinari
"...What?"

@Ichinari
"Um, guys...?"

@Ichinari
"I have not the faintest clue of what you might be speaking..."

@Akira
"...Huh?!"

@Akira
"D-Did I really just say that?!"

@Akira
"My inner thoughts just slipped out...!"

@Iori
"A-And I just went along with it...!"

@Iori
"Oh my word, what was I saying..."

@Nodoka
"I-It's not like that! It's not like I've been thinking about it all the time...!"

@Nodoka
"Although, you know, I'm really interested, for work purposes...!"

Now they're all holding their heads in their hands and muttering to themselves.

@Ichinari
"Umm..."

I falter, unsure what I should say to them.

@Iori
"Speaking frankly..."

@Iori
"I don't care about gods, or Fates, or whatever."

@Iori
"I've loved you all this time, Ichinari."

@Ichinari
"Iori...?"

@Nodoka
"Yeah. Iori's right."

@Nodoka
"We can't help that things have turned out like this."

@Nodoka
"It's true that I'm in love with you, Senpai."

@Ichinari
"Uh, Nodoka...?"

@Akira
"Right. In fact, this might be a good opportunity."

@Akira
"I was always too close to you, Ichi, so I never had the chance to confess."

@Akira
"This is way better than having things end without me ever getting to tell you how I felt."

@Ichinari
"Akira-chan...?"

@Akira/Iori＆Nodoka＆Akira
"So...""So...""So..."

The three of them close in on me.

@Ichinari
"Wait, wait, wait."

@Ichinari
"Can we all just take a step back and calm down?"

@Ichinari
"I'm so happy. So happy I could die."

@Ichinari
"But, you know, don't you think that..."

@Ichinari
"...this is going beyond mere honesty? Isn't this veering into obsessive territory?"

@Iori
"H-How can I possibly be calm at a time like this?!"

@Iori
"Now that I'm finally reunited with the man who's been the star of all my fantasies!"

@Iori
"Ever since you caught me masturbating, I've gotten so embarrassed and wet every time I looked at you!"

@Akira
"Right! Like hell I can be calm right now!"

@Akira
"No matter how hard I tried to seduce you, you only ever gave my boobs a sideward glance..."

@Akira
"...and never once made a grab for them!"

@Nodoka
"Whenever we were alone together..."

@Nodoka
"...I'd get so wet imagining you ravishing me, Senpai!"

@Nodoka
"How can I possibly be calm when I have the chance to bring my well-honed fantasies to life♪"

@Ichinari
"Um, I don't really know what to do with all these confessions..."

Have I really been this oblivious to the signs?

But, rather than just being more honest, isn't it more like they've totally lost control...?

Or is this what their true personalities were like all along?

@Ichinari
"Okay."

@Ichinari
"Now how about we all just calm down?"

@Ichinari
"First, let's all take a deep breath, shall we?"

@Ichinari
"All together now, a deep breath in..."

@Iori
"I-I don't know what's gotten into me, I have no idea why I'm saying these things!"

@Iori
"It's not like I want everyone to know what I masturbate to!"

@Iori
"But I'm being forced to be honest, so I can't help it!"

@Iori
"So the least you can do is take off your pants, Ichinari!"

@Akira
"You know, when I'm checking your plot outlines or your storyboards..."

@Akira
"...and I'm getting all embarrassed, and you smirk at me, it turns me on!"

@Akira
"Just listening to your ideas for your latest story gets me sooo wet, you doofus!"

@Nodoka
"That time, when I was licking the popsicle in front of you and it leaked down my boobs..."

@Nodoka
"...I was more worried about staining my skirt than my top♪"

@Nodoka
"Knowing that you bought my books..."

@Nodoka
"Ah, I imagined all the ways you might be using them♪"

@Ichinari
"No, hold up there, you're not listening to me at all, are you?"

@Ichinari
"Seriously, you're leading my mind in all kinds of directions, so could you please stop? For real?"

@Akira
"SHUT UP AND COUGH UP!"

@Akira
"You think you can get away with listening to us girls expose ourselves without getting your measly little cock out?!"

@Iori
"Just a peek! Just a little peek is fine!"

@Iori
"Just pull your pants down a little bit!"

@Nodoka
"You see this kinda situation a lot in hentai manga, don't you?"

@Nodoka
"Are you actually aroused? Is that why you can't show us?"

@Ichinari
"Stop! Seriously, guys, stop!"

@Ichinari
"If we let ourselves get carried away, we're gonna regret it!"

@Ichinari
"Ah, no, get your hands off my pants!"

@Ichinari
"Hey, three on one isn't fair! It's not fair!"

@Ichinari
"Seriously, wait! Please, get a hold of yourselves!"

@Ichinari
"I'm a virgin! I don't want my cherry popped like this! NOT LIKE THIIIIIIIIISSSSSSSSS!"

And so...

...the three of us were bound together by the gods.

And, whether we wanted it or not...

...our lives were about to change, big time.

