#start|Dōjin Event

One week later...

@Iori
"Ichinari, could I ask you to work on this background?"

@Iori
"The background materials are all available on the server."

@Ichinari
"On it."

@Iori
"Nodoka, can I get you to do these effects and speech bubbles?"

@Nodoka
"Sure thing!"

@Akira
"Yep, yep. I can rest suuuper easy knowing you guys are on top of things~♪"

@Akira
"Okay, I'll go and prepare some tea and cake for our break!"

@Akira
"Gyaaah! The tealeaves have spilled EVERYWHERE!"

@Akira
"The top-tier tealeaves from the purveyor to the British royal family! I'M SO SORRY!"

@Ichinari
"I'll take care of the rest, Akira-chan, so you go sit back down."

@Akira
"Yessir, over to you... Sorry for my failings as a woman..."

Slightly dejected, she returns to her desk.

The office has calmed down a lot now that everyone's finished moving their luggage into their individual rooms.

I've mostly gotten used to Iori's workflow, and I'm learning a lot from working alongside her. Basically, it's all smooth sailing so far.

Akira-chan's also working in the office with us to keep an eye on me. I guess the editing department is flexible when it comes to Ishitaka-sensei's team.

Although I don't know how she explained things in order to wrangle this deal.

Incidentally, I came here pretty much empty-handed, given that my apartment was destroyed. I'm borrowing a blanket and sleeping on the sofa.

But even that arrangement is way comfier than my previous wafer-thin futon! I'm sleeping like a log these days.

@Nodoka
"Oh, Iori-san."

@Nodoka
"Will this month's schedule be okay at our current pace?"

Sipping on the tea Akira-chan had poured for her, Nodoka looks through her diary and checks in with Iori.

@Iori
"Thanks to all of you, things are chugging along nicely, so we'll be fine."

@Iori
"We shouldn't have any urgent extra work coming in."

@Iori
"And even if we do, I think Ichinari and I will be able to handle it."

@Iori
"So you can take some time for your own project too, Nodoka."

@Nodoka
"Okay. Thank you, as always~♪"

@Ichinari
"Is this project for a dōjin event?"

@Nodoka
"Yep. Comic Carnival will be held at the end of this month."

@Nodoka
"And I plan to release a new dōjinshi for it~"

Nodoka scribbles her plans down into her diary.

@Akira
"There's been a huge increase in participating circles and visitors to Comica recently, hasn't there."

@Akira
"Our company'll have a booth there too, so I'll come say hi to you, Nodoka-chan."

@Akira
"A lot of our artists will be exhibiting too, so I have to go around greeting them all anyway."

@Akira
"And Comica means more late manuscript submissions that usual this month. Ahahaha..."

@Ichinari
"Being an editor sure is tough. There there."

I console Akira-chan as she sulks over her cake.

@Nodoka
"There are plenty of artists who get the majority of their income from their dōjin activities."

@Ichinari
"So they use their pro work to gain a following, while the dōjin work is what really pays the bills?"

@Nodoka
Of course, once you decide to start doing dōjin, you've got to keep up with it.

@Nodoka
"You've got to periodically attend events and publish new issues."

@Nodoka
"Plus post content to Dwitter, and promo the events and new releases..."

@Akira
"Honestly, the internet is everything these days."

@Akira
"If you're popular enough, there are plenty of places you can sell without going through a publisher."

@Iori
"Still, I'm really grateful to have the editorial department of a publisher behind me."

@Iori
"It means I can concentrate entirely on creating."

@Iori
"Since I hate going out and talking to people."

@Ichinari
"Huh, I see, I see."

The dōjin world is completely unfamiliar to me. If I didn't have publisher...

I would have to do absolutely everything myself\: jacket design, communicating with printers, stores, and fans...

...advertising online, managing my inventory—the list goes on and on.

@Nodoka
"But the appeal of dōjinshi is being able to go all-in on whatever it is you want to do, with no one to answer to but yourself."

@Nodoka
"So long as you adhere to some basic rules, you can draw pretty much whatever you want in any genre at all~♪"

Putting a hand to her cheek, Nodoka stares off into space, her face flushing and her eyes taking on a distinctly lewd glint.

Man, Nodoka really loves her porn. What did she say she was working on next? NTR?

I can't wait! I give an internal "like" to my little kōhai, who's matured into such an enviable woman.

@Ichinari
"So how much of the manuscript do you have left to do?"

@Nodoka
"I've only just finished storyboarding."

@Ichinari
"Huh? How many pages are you planning?"

@Nodoka
"Hmm. Around 40, give or take?"

@Nodoka
"Taking into account when I need to send it to press, I guess I'll have to finish it up in about a week."

@Ichinari
"...What? While still doing your assistant work?"

@Nodoka
"Yep♪"

She smiles and nods. Then, after elegantly taking another sip of tea, she lets out a contented sigh.

@Ichinari
"Wait, wait, wait, wait. That's just not possible with our current schedule."

@Ichinari
"I mean, maybe if you had a bunch of assistants working under you, but it's just you, right?"

@Nodoka
"Huh? But this is how I always do things?"

@Nodoka
"The fans would be so disappointed if I showed up at the event without anything new to offer."

Her response is totally nonchalant.

@Ichinari
"Never mind the fans! If you push yourself that hard, you'll have some kind of breakdown."

@Nodoka
"I'm not going to have a breakdown over this. I'm used to it."

@Nodoka
"Are you concerned about my health, Senpai?"

Pushing her cleavage together, she peers up at me with her usual playfulness.

@Ichinari
"Nodoka... I am genuinely concerned about you."

@Nodoka
"Senpai?"

I look her straight in the eye.

@Ichinari
"I know you're talented, and you're determined."

@Ichinari
"But you're also only human. You've gotta take care of your body, okay?"

@Nodoka
"Senpai..."

@Nodoka
"..."

@Nodoka
"Iori-san... This is like, super awkward, isn't it?"

@Nodoka
"Like, I'm happy he's treating me like a fragile flower and all, but... Tee hee~♪"

@Iori
"Yeah, yeah. I totally get it."

@Iori
"It's super cute when he tries to act tough like this, isn't it?"

@Akira
"He may be a loser, but very occasionally he'll get all serious on us."

@Akira
"Is this what they call 'gap moe'? Is it?"

@Ichinari
"You guys..."

And here I was trying to be serious... I can feel my face flushing hotly as the three of them make fun at my expense.

@Nodoka
"Hee hee. Thank you for your concern, Senpai♪"

@Nodoka
"But I'm honestly fine."

Tilting her head to the side, she smiles as she reassures me confidently.

@Nodoka
"It's true that it's going to be cutting things close this time, but..."

@Nodoka
"I do this because I love it."

@Nodoka
"And when it comes to work, it's my personal rule to always do it to the best of my ability."

@Ichinari
"Nodoka..."

Her smile is as gentle as ever, yet I can sense the strength in it. I swallow any other words I'd been about to say.

@Ichinari
"I guess just because something's amateur doesn't mean you slack off on it."

@Nodoka
"Nope."

@Nodoka
"And for the fans who are looking forward to it..."

@Nodoka
"I have to do my best, just like with any other job."

@Nodoka
"It's because I get to do what I love..."

@Nodoka
"...that I have to do it justice."

She speaks softly, with a hand pressed to her chest; but her words are sent to me straight as arrows.

@Ichinari
"Right..."

@Ichinari
"You're totally right. Sorry for sticking my nose in where it doesn't belong."

I bow my head to show her I accept what she's saying.

@Nodoka
"Oh, no, I'm really touched by your concern."

@Nodoka
"And I know you're looking forward to it, so I want to work hard for you, t—"

@Ichinari
"So, listen here."

I cut her off.

@Ichinari
"Would you mind if I helped out? I'll have time in the evenings, after I finish up my jobs for Iori."

@Nodoka
"Senpai?"

@Ichinari
"I can't draw as well as you, but I'm sure there's something I could help with."

@Ichinari
"I'm a Nagomi-sensei fan, so I've been looking forward to your next release, too."

@Ichinari
"But above all that, I'm your senpai. If there's anything at all I can do to help, I want to do it."

@Nodoka
"Senpai..."

She blinks at me, wide-eyed. The her big eyes slowly narrow.

@Ichinari
"Oh, um, obviously I'm not gonna force you to let me help."

@Ichinari
"Only if you're okay with letting me near your valuable work...!"

@Ichinari
"I just think it's better to have a little breathing room, rather than trying to take everything on yourself...!"

@Ichinari
"And if you're struggling, I want to be able to do something—anything—to help...!"

As I trip over myself to explain, Nodoka covers her mouth and giggles.

@Nodoka
"You really know how to give me butterflies, Senpai."

@Nodoka
"Do you really think I could turn down such a request from the man I love after hearing all that?"

@Ichinari
"Uh, no, I mean, I didn't say it to try and convince you."

@Ichinari
"I was just being honest...!"

@Nodoka
"Yes, I know, so don't worry."

@Nodoka
"This is exactly why I love you, Senpai. Hee hee."

@Ichinari
"Nodoka..."

She tilts her head, her eyes narrowed affectionately and her expression bashful.

Damn, she's really freakin' cute. Despite being the younger one, she's always messing around and trying to get a rise out of me, but now...

Receiving such a frank, open reaction from her, it's my turn to blush.

@Nodoka
"Do you think I could take you up on that offer?"

@Nodoka
"I'd really, really love it if you helped me out, Senpai♪"

@Ichinari
"Oh, uh... Yeah, sure, of course."

@Ichinari
"I'll do my best not to drag you down."

@Nodoka
"I've been keeping a beady eye on you this past week, so I know I can count on you."

@Nodoka
"You're Iori-san's assistant—have a little more faith in yourself, ya big nerd♪"

@Ichinari
"No, I mean, I'm really not all that."

I return her elbow jab with one of my own.

@Akira
"Um, excuuuse me."

@Akira
"Could you two please get a room before you make me gag?"

@Iori
"Um... I-I..."

@Iori
"I was planning on finishing up my own work early, so I could help out Nodoka too..."

@Ichinari
"Oh, I didn't mean to..."

@Ichinari
"I'm sorry."

I do my best to console the two sulking girls.

@Ichinari
"Nodoka? I'm coming in!"

@Nodoka
"Senpai."

@Nodoka
"What's up?"

Nodoka looks over her shoulder at me from where she's been working on her computer.

It's one in the morning. I show her the mug of coffee I've brought.

@Ichinari
"Since it seemed like you were still up working, I thought maybe we could take a little break together."

@Nodoka
"Oh, thank you so much♪"

@Nodoka
"I was just thinking I needed a coffee~"

@Nodoka
"Please, come on in."

@Nodoka
"I don't have an extra chair, so if you could just take a seat on the bed..."

Nodoka shows me into her room.

The previously empty spare room has been transformed into a feminine paradise.

Although she'd only brought the bare minimum of things from her own flooded place...

In contrast to Iori's room, it's totally cute and girly, with clothes and makeup scattered around.

And the cutting-edge all-in-one PC is definitely Nodoka's style, too.

Still...

I feel kinda like this is pushing it, even for your own bedroom...

I mean, is this what women usually wear to bed...?

I'm not quite sure where to look.

@Nodoka
"Senpai? Is something wrong?"

@Ichinari
"Oh, no, nothing."

@Ichinari
"Anyway, how is your dōjin work progressing?"

@Nodoka
"Really well, thanks to you."

@Nodoka
"In fact, maybe a little too well..."

@Nodoka
"I'm already pressed for time, yet I keep getting carried away and drawing even more."

@Ichinari
"You can just give me the extra work. So long as you're happy with where it's going."

@Nodoka
"Okay. You're a real lifesaver, Senpai♪"

She giggles into her coffee cup as she clasps it in both hands and raises it to her lips.

@Nodoka
"Are you not interested in drawing dōjin yourself?"

@Ichinari
"My dream was always to become a professional artist."

@Ichinari
"And I never knew anyone involved in the amateur scene, so I guess I never really thought about it."

While I do enjoy looking at fanworks, I've never considered creating any myself.

@Nodoka
"You don't have to draw fan stuff—if you do original content, it's pretty much the same as drawing commercially."

@Nodoka
"Plenty of professionals are also active in the dōjin scene—why don't you give it a try too?"

@Nodoka
"I can fill you in on all the dos and don'ts~♪"

@Ichinari
"Me? Draw dōjin?"

I contemplate the idea.

@Ichinari
"It sounds great to be able to draw whatever you want, however you like, but..."

@Ichinari
"To be honest, I don't have the confidence."

I’ve seen miserable situations on Dwitter where people printed more copies than they could sell, and I don't feel like I have what it takes to self-promote.

Besides, I don't even have the money to fund printing in the first place. The hurdles are so high, it's downright depressing.

@Nodoka
"Well I think you should have a little more faith in yourself, Senpai."

@Nodoka
"Besides, creative pursuits aren't something you get into because you have confidence."

@Nodoka
"I mean, you're not drawing manga as your job right now because you're confident you're good at it, are you?"

@Ichinari
"That's...a good point, but..."

@Nodoka
"Also, sales aren't everything when it comes to dōjin."

@Nodoka
"Being able to meet your fans in person when they come to buy your comics is really fulfilling."

@Nodoka
"In fact, I would say that's probably the best thing about the amateur scene."

@Ichinari
"The fans' voices, huh?"

If I witnessed someone buying my book before my very eyes, I'd be so emotional I'd probably break down in tears.

But just as her words are on the verge of igniting some spark within me, something occurs to me.

@Ichinari
"But what if..."

@Ichinari
"I fail because those fans don't exist in the first place..."

@Ichinari
"I only have about 150 real followers on Dwitter."

@Nodoka
"...That is quite low for someone who's serialized in a commercial magazine. Ahaha..."

She averts her eyes from me awkwardly.

Damn. It's worse than I thought.

@Ichinari
"Speaking of that..."

@Ichinari
"I don't tend to follow even my favorite artists on social media, so..."

@Ichinari
"How big are the troops rallying behind Nagomi-sensei?"

@Nodoka
"Oh, me? Well, you know..."

Seeming a little unsure how to answer, she pulls out her phone and shows me her profile.

@Ichinari
"16,000 followers... I...see..."

@Nodoka
"Yes, well... Ahaha..."

She gives a dry, awkward chuckle.

...Yeah. I'm even more doomed than I thought.

@Ichinari
"W-Well, for the time being, I'm prioritizing being the best assistant I can be, you know?"

For some reason, I feel compelled to put on a false show of bravado.

@Nodoka
"Oh, then if you like..."

@Nodoka
"Why don't you join me at the next event?"

@Nodoka
"It'd make me really happy if it served to spark your interest in dōjin♪"

@Nodoka
"Yes, actually, this is a great idea~♪"

@Nodoka
"I have other staff members who help out at the booth, so you could just chill out and watch how we do it~♪"

@Nodoka
"So? So? Do you think it's a good idea, Senpai? Do you?"

Beaming broadly, she leans forward eagerly and grips my hand. Her sweet post-bath scent washes over me.

Through the thin fabric of her nightgown, I can feel her sensual heat and the undulations of her breathing as it lightly brushes against me.

My gaze is drawn down to her lips as my mind takes me back to that moment...

@Nodoka
"Ah!"

@Nodoka
"I-I'm sorry, Senpai!"

@Nodoka
"I just...got overexcited and...!"

@Nodoka
"..."

Her cheeks flushing scarlet, she glances up at me through her lashes before looking away.

@Ichinari
"Uh, no... Um...!"

@Ichinari
"I... I'm sorry!"

@Ichinari
"I know you weren't implying anything, I just...!"

@Nodoka
"Oh, no! I think I'm the one who was out of line...!"

@Nodoka
"Um, sorry."

Usually she'd make some sort of mischievous joke, but right now she's oddly meek as she twists her fingers together.

What the hell...

SHE'S SO FREAKING CUTE! This contrast is like, super unfair...!

I don't know what to do with myself as I sneak glances her way.

@Ichinari
"A-Anyway...!"

@Ichinari
"If you really want me to come, then maybe you could let me help out at the booth?"

@Ichinari
"I've been wanting to get a look at a proper dōjin event anyway."

@Nodoka
"Senpai..."

@Nodoka
"Yes, I'd be super grateful!"

Smiling bashfully, we nod our agreement to one another.

@Ichinari
"Well, sorry to intrude so late at night."

@Nodoka
"Not at all. It was nice for me to have a break, too."

@Nodoka
"Oh, but since it is so late..."

@Nodoka
"How about turning this into a little rendezvous?"

@Nodoka
"I just took a shower, so I'm squeaky clean~♪"

@Ichinari
"...I already told you not to joke about that stuff."

@Nodoka
"Hee hee, but I'm not joking."

@Nodoka
"I'm always ready, so..."

@Nodoka
"Please drop by any time, if the mood strikes you♪"

She's completely back to her usual self as she pokes her tongue out at me impishly.

@Ichinari
"I shall give due consideration to your offer."

@Nodoka
"And I shall be looking forward to your conclusion."

@Ichinari
"Now, don't you work yourself too hard."

With that, I stand up from the bed.

With a little wave to her, I leave Nodoka's room.

@Nodoka
"Alrighty."

@Nodoka
"Guess I've gotta keep pushing on..."

@Nodoka
"...so I can look good in front of Senpai too~"

@Nodoka
"Mmm, it's the perfect weather for Comica~♪"

@Nodoka
"I've had all the books and our other luggage sent ahead to the venue already."

@Nodoka
"So now all that's left is for us to make it to the convention center ourselves~♪"

It's 7 a.m. on the first day of Comica.

Narrowing my eyes against the bright glare of the sun, I see that Nodoka's smile is almost as brilliant.

@Ichinari
"Man, imagine if we had to deal with rain on top of all the people."

@Ichinari
"Iori's already bad enough with crowds and the outdoors, I don't think she'd cope with rain too..."

@Ichinari
"Right, Iori?"

@Iori
"*fidget fidget fidget*"

@Iori
"...Huh?"

@Iori
"O-Oh, right, yes... It's great that it's raining, isn't it...?"

@Nodoka
"...This isn't going so well."

@Ichinari
"No, it's not, is it."

Iori has been freaking out with nerves all morning.

@Ichinari
"You okay, Iori?"

@Ichinari
"You really didn't have to force yourself to come..."

@Iori
"I-I'm fine! I'm absolutely fine!"

@Iori
"Nodoka's always doing so much for me!"

@Iori
"So I want to help her out when I can, too!"

@Iori
"But you can't leave my side, Ichinari, okay? Not even for a second?"

She clings to me, looking like she's about to burst into tears at any moment, and repeats the mantra she's been saying to me all morning.

@Nodoka
"Iori-san, are you SURE you're okay?"

@Nodoka
"You don't have to push yourself too far outside your comfort zone just for my sake."

@Nodoka
"You've already helped me out plenty with my manuscript..."

@Nodoka
"And I can handle the booth with my usual staff members."

@Iori
"I-I'm coming! I'm definitely coming!"

@Iori
"I mean, Ichinari's going too, and we both helped with the manuscript..."

@Iori
"...And I'd feel really left out if you went without me."

@Ichinari
"There it is."

Pouting sullenly, she looks down at her fingers as she twists them together. Damn, she's so cute!

I know it must be hard to live with her crippling shyness. Being a manga artist must be her life's calling, as you barely need to go outside.

Thinking fondly back on when we'd first met, I'm filled with a strong urge to protect her.

@Nodoka
"Hee hee, okay then."

@Nodoka
"I'm really happy to have you here at the event with me."

@Nodoka
"You can both just take it easy and use this as a chance to see how things work behind the scenes."

@Nodoka
"So long as you stay behind the booth, no one will try to talk to you, and you can avoid the crowds, too♪"

@Nodoka
"And I'll be at the booth the whole time."

@Iori
"Th-That's...reassuring..."

@Iori
"Um, I'm...sorry about my anxiety."

@Nodoka
"Not at all! You're so cute~♪"

@Nodoka
"So cheer up, okay? Pet pet~♪"

@Iori
"Wahhh, Nodoka!"

Nodoka wraps her up in her arms and pets her like she's a little kid. You wouldn't think Iori's the older one of the pair.

But the two of them do make a pretty picture. Feeling all warm and fuzzy inside, I watch over them with a stupid grin on my face.

@Nodoka
"Seems like Akira-san's already there."

@Nodoka
"So shall we go join her?"

@Ichinari
"Huh? Join her? But the station's that way—"

@"Taxi Driver"
"Apologies for the wait."

@"Taxi Driver"
"I have a reservation under Amabane-sama?"

@Nodoka
"Ah, perfect timing. The taxi's here!"

@Nodoka
"Okay, let's go♪"

@Ichinari
"Huh? We're going by taxi? All the way from Yokohama to Egg Sight?"

@Iori/Iori＆Nodoka
"Huh? But transportation costs are a business expense, right?"
"Huh? But transportation costs are a business expense, right?"

@Ichinari
"Okay..."

Of course, the manga maestros are operating on an entirely different level. Onee-chan, I don't think I'm ever gonna make it up there with them.

I can't even remember the last time I rode in a taxi. I contemplate just how low down on the scale I am as we hum gently along the roads.

Incidentally, the taxi fare to Egg Sight is over 10,000 yen. That's expensive, you know.

@Ichinari
"WHOOOOOOA?!"

@Ichinari
"It's still three hours to opening time and the line's already this long?!"

The moment we arrive at Egg Sight, I'm struck by the masses of people already crammed both into and around the premises.

It's so packed, we have a hard time even making our way to the entrance.

@Ichinari
"I can't believe how many people there are."

@Ichinari
"I mean, I'd seen it on the news and stuff, but it doesn't compare to reality..."

@Iori
"I-I don't think I've ever seen this many people in one place before."

@Iori
"Ugh... I already feel sick..."

@Nodoka
"Once we get inside it'll be much calmer."

@Nodoka
"So just hold on until we get to the booth, okay?"

@Iori
"R-Right... I'll do my best... Urgh..."

Rubbing Iori's hunched shoulders, Nodoka leads us into the venue with  sure-footed familiarity.

@Nodoka
"Oh, there it is, there it is!"

@Nodoka
"This is where our booth will be today~"

@Ichinari
"Huh? Here?"

When we arrive at the booth against the wall of the hall, I'm taken aback by the sheer number of boxes, stacked as tall as I am.

@Ichinari
"Uh... So are there like, about 100 volumes per box?"

@Ichinari
"And you have enough boxes to build an entire wall...?"

@Ichinari
"Huh? Huuuh?!"

@Ichinari
"Wh-What the hell?! You're gonna sell ALL of these today?!"

My gaze travels over the wall of boxes, which a quick guesstimate leads me to believe must contain several thousand copies.

@Nodoka
"Yes, we'll probably sell out about two or three hours after opening."

@Nodoka
"Some of these contain previous issues, so it's not all the new release, but..."

@Nodoka
"We've already sent consignment copies on to all the dōjin stores."

@Ichinari
"Oh, right... So you'll sell all of them... I see..."

If she sells out of all of them at 500 yen per book...

Being a popular dōjin artist is amazing. Beyond amazing. Selling out of more than my total sales run for my officially-published book in a single day of an event...

Well of course you'd take a taxi all the way from Yokohama to Tokyo!

@Iori
"Um... Ichinari?"

@Iori
"Is it really okay for me to be here?"

@Iori
"I-I'm not going to be bullied...or have rocks thrown at me...?"

@Iori
"And if people see you, a man, at Nodoka's booth, you might get stabbed...!"

@Ichinari
"What, for real?"

@Ichinari
"I could be stabbed for that? Seriously?"

I start to freak out right alongside Iori.

@Nodoka
"Of course that's not going to happen, to either of you."

@Nodoka
"There'll be no bullying, and certainly no stabbing, so please calm down."

@Nodoka
"Come on, Iori-san. The outside world isn't that scary, is it? There there♪"

@Iori
"Wahhh... Nodokaaa."

Nodoka hugs the teary Iori, comforting her; the heartwarming sight works to calm me down, too.

@"Soggy Panda Staff 1"
"Good morning, Nagomi-sensei!"

@"Soggy Panda Staff 1"
"The staff are all here. We look forward to working with you today!"

@Nodoka
"Good morning, everyone."

@Nodoka
"I'll be counting on you all again today♪"

@"Soggy Panda Staff 2"
@"Soggy Panda Staff 3"
@"Soggy Panda Staff 4"
@"Soggy Panda Staff 5"
@"Soggy Panda All Staff"
"Let's do this!"

@Iori
"Huh? What are these ten girls doing here...?"

@Ichinari
"Are they all staff members for your circle, Nodoka?"

@Nodoka
"Yep. They've all been helping me out for a long time now."

@Nodoka
"They're so good at what they do, I could just leave it all to them♪"

@Nodoka
"So you two can just relax and watch them work their magic, okay?"

@Ichinari
"Haa... I see..."

@Iori
"I-Ichinari! I'm scared! I'm so scared!"

@Iori
"There's so many people! Aah... Aaaaahhh!"

@Ichinari
"There there. It's okay—they're all practically friends, you see? There there."

I console Iori, who looks like she might pass out.

@Nodoka
"Okay, I'm just going to go change. I'll be right back."

@Nodoka
"The staff will get everything set up, so don't worry about that."

@Nodoka
"You two just sit down on these chairs and wait for me to get back."

@Ichinari
"Huh? Change...?"

@Announcer
"Now, it is my great pleasure to announce..."

@Announcer
"...that today's Comic Carnival is now open!"

@Nodoka
"One copy of the new release? That will be 500 yen. Thank you very much~♪"

@Nodoka
"These are our previous releases, and this is our newest dōjinshi."

@Nodoka
"Sorry, the newest release is limited to three copies per person."

@Nodoka
"Ooh, thank you so much for the snacks♪"

@Nodoka
"I'll share them with the other staff later!"

@Nodoka
"Thank you for all your support♪ I'll keep on doing my very best♪"

@Nodoka
"Yes, next customer please♪"

@"Soggy Panda Staff 1"
"This is the end of the line for Soggy Pandaaa!"

@"Soggy Panda Staff 2"
"Could I ask everyone in line for Soggy Panda to move forward slightly!"

@"Soggy Panda Staff 3"
"Please have the correct change ready so we can facilitate a smooth transaction!"

@"Soggy Panda Staff 4"
"The newest release is limited to three copies per person! There are still plenty available!"

@Iori
"Umm...! These are boxes for the new release!"

@Iori
"And, um, these are the ones with the previous issues!"

@Ichinari
"S-Sorry, Iori, do you have the box cutter?"

@Iori
"Oh, I put it down over there!"

@Ichinari
"Thanks. Okay, I'll flatten these empty boxes!"

@Iori
"R-Right! And I'll help Nodoka out!"

Mere moments after the event had opened, a huge line had snaked out in front of Soggy Panda's booth.

With four people manning the registers, the flow of customers is uninterrupted, and the books are flying off the table.

In all the hububb, even Iori and I end up voluntarily helping out.

@Ichinari
"I-I'd heard the rumors, but...this rush is really something...!"

@Iori
"Y-Yes, it really is...!"

@Iori
"I don't even have time to remember I'm a shut-in with social anxiety...!"

Drenched in sweat, Iori and I continue to work as efficiently as we can. We're so busy we barely even have time to think.

@Nodoka
"Senpaiii!"

@Nodoka
"We're almost out of new releases, so do you think you could top us up?"

@Ichinari
"O-On it! Just wait a moment, I'll open up a new box!"

@Nodoka
"Iori-saaan! Could I get you to help out up front for a moment?"

@Nodoka
"Don't worry, I just need you to stand beside me and take the money."

@Iori
"O-Okay!"

@Iori
"I don't think I'll be able to talk to anyone though...!"

@Nodoka
"That's okay. I'm right here, so you'll be absolutely fine~♪"

@Nodoka
"Okay, three copies of the latest release will be 1,500 yen♪"

@Nodoka
"Here are your items. Thank you very much!"

Nodoka's cheerful voice rings out incessantly.

As well as purchasing things, people also come by to wish her luck and give her snacks and fan letters.

Each time she responds with a bright smile and an expression of gratitude.

@Ichinari
"So this is the dōjin life, huh?"

This is what Nodoka had been talking about yesterday.

I get it now. When I see that smile on her face, I totally get it.

@Akira
"Heeey guuuys, how's it going?!"

@Akira
"Looks like Nagomi-sensei's booth is as popular as ever!"

Akira-chan pops up beside the line of customers.

@Ichinari
"Oh, Akira-chan! Great timing!"

@Ichinari
"Could you take this cardboard out to the trash area?"

@Akira
"Alrighty! You just leave the heavy lifting to the one with the black belt!"

@Akira
"Wait, can't I do this later?! Why are you trying to send me away when I just got here?!"

@Ichinari
"Oh, good point."

Akira-chan sets the cardboard down again.

@Akira
"Anyway, I brought you some nice cold refreshments! On my dime, of course!"

@Akira
"You sweat a lot at these summer events, so you've gotta make sure to replenish your fluids, okay?"

@Akira
"You artists aren't used to exercise, so if you overdo it you can end up fainting from dehydration."

@Iori
"Th-Thank you, Akira-chan! I-I'd love a drink!"

@Iori
"Ngh! Nnngh!"

@Iori
"Sorry, Ichinari, I can't open it. Could you?"

@Ichinari
"Alright, time for me to shine!"

I uncap the plastic bottle for Iori, who seems a bit out of it.

This is one shut-in hentai manga maestro who's reached her physical limits. I get her to sit down in a chair and rest.

@Ichinari
"Have things calmed down at your booth, Akira-chan?"

@Akira
"We're not selling anything this time, so we're just running the editorial clinic for people to bring their manga to."

@Akira
"We give advice from a profession perspective and, if we come across someone with raw and ready talent, talk about potentially getting them in a magazine."

@Akira
"So we're nowhere near as busy as you guys."

@Ichinari
"Huh, I didn't know the editorial department did stuff like that."

@Akira
"A lot of artists are putting out new releases here, so they come by to show them to us while they have the opportunity."

@Akira
"And if we can discover some new talent while we're at it, it's a win-win all round."

@Akira
"Although my job is mostly to go around checking in with our current artists."

@Akira
"Which is how I snuck out to see you! Wahoo!"

@Ichinari
"Ooh, great job, great job."

Not really understanding, I give her an appreciative clap anyway. Times like these, you've just gotta go with it.

Onee-chan seems pretty happy anyway.

@Akira
"Although I'm only half joking."

@Akira
"You said you'd all be here..."

@Akira
"And I was wondering if you might be short-handed."

@Akira
"But of course, I needn't have worried about Nodoka-chan."

@Akira
"And you have all your veteran staff here, too."

Akira-chan nods approvingly as she watches Nodoka and the others handle the endless waves of customers.

@Iori
"Don't you need to go and say hello to your other artists, too?"

@Akira
"If I tell them I'm with Ishitaka-sensei and Nagomi-sensei, they'll let me off♪"

@Akira
"The editor-in-chief's told me to hurry up and scout Nodoka-chan for the magazine already."

@Akira
"Even though Nagomi-sensei's made it clear she's not interested in commercial publishing, she just won't let up."

@Akira
"And yet she won't even refund me my expenses for the snacks! Ugh!"

@Akira
"Ichi! Pet meee!"

@Akira
"Heal my frayed nerves!"

@Ichinari
"There, there, there. You're having a real tough time of it, aren't you. *pet pet*"

@Akira
"Haaa~ That's better~♪ You really do make everything better~♪ Haaaa~♪"

My onee-chan can be a real cutie. As I keep petting her, I feel myself being soothed, too.

@Akira
"Thinking back on it, I first met Nagomi-chan at Comica."

@Ichinari
"Oh, really?"

@Akira
"I think it was when she brought her work to our editorial booth."

@Akira
"Of course, I realized right away that she was a talent to look out for, but..."

@Akira
"She said she'd only come to hear our feedback, and that she had no interest in commercial publication."

@Akira
"Well, seeing how things are going for her now, I can't say I blame her."

She looks at me with a knowing smile.

@Ichinari
"Huh, she did that?"

I look over at Nodoka, manning the booth.

Nodoka's been taking her manga really seriously too; it's easy to forget, given that she never shares her struggles.

The reason she's progressed so far since high school is all down to her own continued efforts.

@Nodoka
"I always loved you, Senpai."

@Nodoka
"Which is why I worked so hard..."

@Nodoka
"...hoping that I could see you again."

@Ichinari
"..."

The thought of her straightforward determination makes my heart clench in my chest.

@Nodoka
"Senpaiii!"

@Nodoka
"Could I get some more refills of the new publication?"

@Ichinari
"Gotcha! Leave it to me!"

@Akira
"Okay then, I suppose I should get out there and visit the other artists."

@Akira
"Keep doing your best, Iori-chan—but don't overdo it."

@Iori
"Yeah, you too, Akira-chan."

With an energetic wave of her hand, Akira-chan moves off into the crowd and is quickly lost to sight.

@Ichinari
"Well then, I'd better pitch in for the final push, too."

@Ichinari
"You doing okay, Iori?"

@Iori
"Yep. I'll keep working, too."

@Iori
"But before we get back to, could I ask for...just one thing?"

@Ichinari
"Sure, what is it?"

@Iori
"Could you...give me a pet to keep me going, too?"

Just like I'd done for Akira-chan, I give Iori a good head pat.

@Iori
"Haaa~♪ I feel so much better~♪"

@Iori
"This really is...goood~♪ Haaa~♪"

Man, Iori's so sweet and open. Even the way she gets a little jealous is cute.

I keep petting her head as I think about how adorable she is.

@Nodoka
"Senpaiii!"

@Nodoka
"Quit canoodling with Iori-san and get me those books NOW!"

@Iori/Iori＆Ichinari
"I-I'LL BE RIGHT THEEERE!!!"
"I-I'LL BE RIGHT THEEERE!!!"

We both scramble to open up fresh boxes as Nodoka shouts at us.

@Announcer
"Ladies and gentlemen..."

@Announcer
"Comic Carnival is now closed."

@Nodoka
"Great work out there today, everyone♪"

@Nodoka
"We got through it thanks to all of you~♪"

@Nodoka
"We'll be back at it again tomorrow, so let's call it day now."

@"Soggy Panda Staff 1"
@"Soggy Panda Staff 2"
@"Soggy Panda Staff 3"
@"Soggy Panda Staff 4"
@"Soggy Panda Staff 5"
@"Soggy Panda All Staff"
"Great work, guys!"

@Iori
"Haa... It's finally over."

@Iori
"As a shut-in, that almost killed me..."

@Ichinari
"I know, right... I don't wanna move from this spot..."

@Ichinari
"In fact, I don't think I can..."

Iori and I are slumped on the floor.

My feet are killing me, and I feel gross from sweating all day long. Plus I'm starving. And absolutely exhausted.

@Nodoka
"Senpai, Iori-san. Great work, both of you."

@Nodoka
"I ended up dragging you into helping with a bunch of stuff. Sorry about that."

@Ichinari
"Oh, no, I'm just glad I could be of help."

@Iori
"Me too. I actually surprised myself..."

@Iori
"Although I can't wait to get back home."

@Nodoka
"Hee hee. You were a real lifesaver today. Thank you."

@Nodoka
"Now, let's go home, shall we."

@Iori
"Yeah... And let's take a taxi back, too."

@Ichinari
"Even I'm not gonna argue with that."

We both respond sluggishly.

@Nodoka
"Iori-san? You can't go out in public looking like that."

@Nodoka
"Here, I have some wet wipes, so please wipe down your face and body."

@Nodoka
"As women, we've got to pay attention to these things."

@Iori
"It's not necessary, we're just going home."

@Iori
"I'll take a shower as soon as I get in."

@Nodoka
"Nope. We have standards to maintain."

@Nodoka
"And they say sweat is basically the same as pee, compositionally speaking."

@Nodoka
"Think about Senpai smelling all that stinky sweat of yours..."

She turns to me with a smirk.

@Iori
"P-Pee...! I-Ichinari?!"

@Iori
"Don't tell me...! You've been judging me all day long?!"

@Iori
"Nyaah♪ Oh nooo, it's not just sweat flowing out of me now♪"

@Ichinari
"Don't worry, I won't look."

I'm so lethargic, I don't even have the energy to make a joke.

@Nodoka
"There are people around, so you can't wipe yourself down here."

@Nodoka
"Please go ahead and use the cosplay changing rooms. Here are the wet wipes."

@Iori
"Okay. I'll go clean myself up."

This time she nods obediently and drags herself off to the changing rooms.

Now it's just me and Nodoka left at the booth.

@Nodoka
"It'll probably be a while before she's back, so..."

@Nodoka
"How about we go outside and get some air for a bit?"

@Nodoka
"I'm seriously tired myself."

The hall is emptying out quickly, so we can easily get outside as Nodoka suggests.

@Ichinari
"Yeah, good idea. Let's do that."

Going along with Nodoka's offer, I follow her out of the hall to a convenient bench.

@Nodoka
"Okay, I'll just take this seat right next to you♪"

@Nodoka
"Whoopsie daisy!"

@Ichinari
"Hey, Nodoka?!"

@Nodoka
"Hmm~? What is it, Senpai?"

@Ichinari
"People could see us...!"

@Nodoka
"And so what if they do?"

@Nodoka
"Besides, there's no one out back here, see? Hee hee♪"

Nodoka giggles to herself as she lays her head on my shoulder.

@Nodoka
"This is to make up for before..."

@Nodoka
"...when you were petting Iori-san and Akira-san and ignoring me."

@Nodoka
"You can allow me this much, can't you?"

She leans into me, her expression calm and peaceful.

@Ichinari
"Well, I guess if you're okay with it, then I am too."

After checking that there's no one else around, I allow myself to relax beneath the gentle outdoor breeze.

@Nodoka
"So how was your first event?"

@Nodoka
"The dōjin world has a lot to offer too, doesn't it?"

From my shoulder, her voice tinkles in my ear like a bell.

@Ichinari
"Seeing just how many people are excited to come and buy your books..."

@Ichinari
"It made me realize just how amazing you really are."

@Ichinari
"I mean, I already knew, to an extent, but..."

@Ichinari
"Seeing it for myself really brought it home to me."

Narrowing my eyes against the glow of the sunset, I respond to her with my genuine, unfiltered thoughts.

@Nodoka
"I never really aimed to become a pro or anything."

@Nodoka
"I've just been working hard at creating, like you taught me back in high school."

@Nodoka
"Although it does give me a little bloom of pride..."

@Nodoka
"...to know that that's led me to have the support of so many people. Hee hee."

@Nodoka
"I always believed that, so long as I kept drawing manga, I'd get to see you again someday."

@Nodoka
"Do you understand just how hard I worked for that?"

@Nodoka
"It's all thanks to you that I've made it this far."

Her tone is softer than usual as she delivers her words of gratitude.

@Ichinari
"No, this is all down to you."

@Ichinari
"Maybe joining the manga club was what sparked it, but it's not like I helped you with any of it."

@Nodoka
"It's not about what started it, or what you did..."

@Nodoka
"Honestly, you really know nothing about a woman's heart, Senpai."

@Nodoka
"Although that obliviousness is part of your charm. Hee hee."

Giggling sweetly, she slowly links her arm through mine.

@Nodoka
"Now..."

@Nodoka
"If you acknowledge how hard I've worked, then..."

@Nodoka
"Will you make my dream come true?"

@Ichinari
"Your dream?"

@Nodoka
"Yes. I've been waiting for it to come true for a long time now."

@Nodoka
"My dream is to one day make a collaboration dōjinshi together with you, Senpai."

@Nodoka
"You don't have to give me an exact timeframe."

@Nodoka
"But this time, I want you to keep your promise."

@Nodoka
"I've made it to where I am today because of my desire to see that dream fulfilled."

@Ichinari
"Nodoka..."

She squeezes hold of my arm tightly, seeming somewhat tense.

@Ichinari
"Okay. I promise."

@Ichinari
"I'm nowhere near your level yet, but I'll work hard to be able to draw something that lives up to your work."

@Ichinari
"So could you wait just a little longer for your dream to come true?"

I gently rest my head on top of hers.

@Nodoka
"Thank you, Senpai."

@Nodoka
"I'll be waiting for you to make my dream come true."

The tension drains from her limbs, and I feel the softness and warmth of her body sinking into mine.

I'm filled with a tender affection that makes my chest ache sweetly.

@Nodoka
"I'm glad I got to show off a little in front of you, Senpai."

@Nodoka
"Although I didn't mean to drag you into helping with the manuscript..."

@Nodoka
"I'm glad I mustered up the courage to invite you."

@Ichinari
"You mean, this was because..."

@Nodoka
"I wanted to show off to you."

@Nodoka
"It's kind of gross when a girl is obvious about what she wants, you know?"

@Nodoka
"I suppose I should be thankful to the gods for allowing me to be this open. Hee hee♪"

With a familiar mischievous smile on her, she nuzzles her cheek against me adoringly.

@Nodoka
"You know, I'm having so much fun these days."

@Nodoka
"I'm so much closer to Iori-san and Akira-san than I used to be."

@Nodoka
"Of course, I love you too, but I'm really enjoying all of this."

@Nodoka
"Almost too much. Hee hee."

@Ichinari
"Nodoka..."

She sounds both pleased and troubled as she whispers words similar to the ones I'd heard from Iori.

@Nodoka
"Well, I suppose we should head back inside."

@Nodoka
"Iori-san will probably be back anytime now."

@Ichinari
"Yeah, you're right."

We get up from the bench and make our way back into the hall.

@Nodoka
"Now then, let's get something yummy to eat, then head on home♪"

@Nodoka
"I'll treat you to anything you like♪"

@Ichinari
"And as usual, I'll gladly take you up on that offer."

I bow my head to the great and powerful Nagomi-sensei.

And so, filled with a profound sense of both exhaustion and satisfaction, my very first event comes to a successful close.

