#start|Unsung Heroes

@Nodoka
"Iori-saaan?"

@Nodoka
"Isn't it about time for your salon appointment?"

@Iori
"Oh, right, yeah..."

@Nodoka
"You should find a good stopping point soon, or we'll be late."

@Iori
"Mm, but I can't really leave what I'm doing right now..."

@Iori
"Let's reschedule for another day, okay? Yeah, that'd be for the best."

@Nodoka
"Iori-san?"

@Nodoka
"You said the exact same thing when you flaked out on your appointment last time."

@Nodoka
"And you said you'd DEFINITELY go next time."

@Nodoka
"Plus I know you're not working on anything urgent right now."

@Iori
"Uh... No, well, you see... Er..."

@Iori
"..."

@Iori
"Oh, Nodoka, look at this funny video I found!"

@Iori
"It's soooo hilarious, you won't believe it."

@Nodoka
"Okie dokie, time to go!"

@Nodoka
"We girls have to take care of our appearance, you know?"

@Nodoka
"We'll be back this evening! Don't wait up♪"

@Iori
"No, please! I PROMISE I'll DEFINITELY go next tiiime!"

@Iori
"I-I don't want the world to see me! I don't think that they'll understand!"

@Iori
"H-Help me...! Ichinari, please, help me...!"

@Iori
"Ah, ah...! Ahh...!"

@Iori
"NoooOOOoooOOOoooOOOooooo!!!"

The front door slams shut, cutting Iori off mid-scream.

@Akira
"Nodoka-chan sure has her hands full with her."

@Ichinari
"Does Iori get like that every time she has to go to the salon?"

@Akira
"Pretty much."

@Akira
"Reminds me of whenever we'd take the family dog to the vet."

@Akira
"Ahh, good times~ I wanna go back home~"

Akira-chan gazes off into the distance.

I remember Iori saying that Nodoka accompanied her to the hair salon. But the reality is, it's more like Nodoka drags her there.

@Akira
"Well, a lot of artistic geniuses have their social issues."

@Akira
"I mean, they can't help it—they have all their eggs in one basket, so to speak."

@Akira
"Yeah, the greats of the world do things on their own terms... Ahaha...ha..."

She's looking even further into the distance now, her eyes unfocused.

Being an editor sounds rough... I look away from Akira-chan, not wanting to get swallowed up in the dark void emanating from her.

@Ichinari
"But, still..."

@Ichinari
"I suppose I'm one to talk, huh. People in glass houses, and all that."

Both of them are working really hard...

Seeing both of them putting their all into their work really brings it home to me that I have to work my ass off, too.

At the same time, it reminds me of how far I still have to go to close the gap between us. Ugh, why does improvement have to take TIME.

@Akira
"Ichi?"

@Akira
"You've seemed down in the dumps lately. What's up?"

Akira-chan comes over to look right into my face.

@Ichinari
"Oh, no, it's nothing."

@Ichinari
"Sorry to worry you."

@Akira
"Doofus. It doesn't matter how big or small an issue it is..."

@Akira
"I've been in love with you all this time!"

@Akira
"No! I mean, I've been by your side all this time!"

@Ichinari
"Akira-chan..."

I don't think she really needed to bother correcting herself, but I keep that thought to myself.

@Akira
"Honestly, Ichi, what am I going to do with you?"

@Akira
"With everyone else around, I haven't been able to give you your daily dose of Onee-chan lately."

@Akira
"C'mere."

She opens her arms wide to me, a gentle smile on her face.

@Ichinari
"Onee-cha-ngh?!"

@Ichinari
"No, no, no! That was close!"

I'm about to jump into her waiting arms on reflex, but I manage to stop myself at the last moment.

@Akira
"Ichi? What's wrong?"

@Ichinari
"Oh, ah..."

@Ichinari
"I figured it wasn't fair to let you indulge me, given how unresolved things are between all of us..."

@Akira
"Honestly, it's a bit late for that, don't you think?"

@Akira
"Besides, we always do this, so it doesn't count."

@Akira
"It can be our little secret."

@Akira
"So c'mon."

She flashes me that indulgent smile as she opens her arms to me again.

@Ichinari
"Gah...!"

@Ichinari
"I really appreciate the sentiment, but...!"

@Ichinari
"Right now... I can't...! Gah...!"

Again, it takes all the strength I have in me to hold myself back from being swallowed up in her warm embrace.

@Akira
"Ichi..."

@Akira
"Seriously, what's eating you?"

@Akira
"For you not to let me pamper you..."

@Akira
"...there must be something weighing on your mind. So spill."

Her tone is genuinely concerned. She peers concernedly into my face as she pets me.

@Ichinari
"Akira-chan..."

@Ichinari
"It's really not that big a deal."

@Ichinari
"But seeing Iori and Nodoka working from up close..."

@Ichinari
"It's like, always in my face how talented they are, and I guess I get frustrated at myself."

@Ichinari
"I mean, I already knew they were on a totally different level to me, but..."

@Ichinari
"Recently it's really been getting to me."

I smile self-deprecatingly as I voice my inner conflict to my earnestly concerned onee-chan.

@Akira
"Ichi..."

@Akira
"Hee hee. You really are such a doofus."

Her response to my whining is to giggle. Then she wraps me up in a gentle hug.

@Akira
"You're right, you knew all this before."

@Akira
"But that's exactly why you decided to work hard here, right?"

She whispers into my ear as she strokes my head. Her voice is softer than usual.

@Akira
"I know you're probably getting worked up over this precisely because you're taking it so seriously, but..."

@Akira
"Don't."

@Akira
"You're moving forward, one step at a time."

@Akira
"Before taking this job, you were only moving sideways, weren't you?"

@Ichinari
"Akira-chan..."

@Akira
"You're gonna learn a lot from both Iori-chan and Nodoka-chan."

@Akira
"But I'm here for you too, okay?"

@Akira
"When you're struggling, it's my job as your onee-chan to do things like this for you."

@Akira
"It's got nothing to do with the fact that I'm in love with you..."

@Akira
"...or because I want an answer from you, or anything like that."

@Ichinari
"Onee-chan..."

She squeezes her arms around me a little tighter. Her soft, comforting voice tickles my ear.

@Ichinari
"...You really do spoil me."

@Akira
"Hee hee. I'm all about that carrot, as well as the stick."

@Akira
"After all, I'm your onee-chan."

There's a lively note to her voice. She gives her affection freely, putting everything she has into comforting me.

Then she slowly pulls away from me.

@Akira
"You feeling a bit better now?"

Giggling a little bashfully, she flashes me a big smile.

@Ichinari
"Yeah, much better."

@Ichinari
"I know you're having a tough time with work, too..."

@Ichinari
"Sorry for unloading on you all the time."

@Akira
"Oh, come on, this is nothing♪"

@Akira
"I don't know anything about drawing manga, so this is all I can really offer."

@Akira
"But when it comes to pampering you, Ichi, the other two have nothing on me♪"

There isn't a trace of anything but genuine kindness in her smile.

@Akira
"Alright, that's enough Mrs. Nice Guy for today!"

@Akira
"Work your hardest, Ichi, you hear me?"

@Ichinari
"Yessir! I'm on it!"

@Akira
"Good boy, that's what I like to hear♪"

@Akira
"A journey of a thousand miles begins with a single step! TAKE THAT STEP!"

@Ichinari
"Yeah! Here I gooooo!"

Akira-chan's got me fired up. I give my cheeks a hard pat.

@Ichinari
"Whoa, is that the time?"

When I look at the clock, it's already past 1 a.m. Time flew away from me while I was engrossed in practicing the fundamental techniques of drawing.

And it's thanks to my stable employment as an assistant that I'm able to carve out time to work on myself.

I think to myself in the empty office as I stretch out my cramped muscles.

@Akira
"..."

@Ichinari
"Oh, Akira-chan."

@Akira
"Ah... Ichi...?"

@Akira
"I didn't realize you were still up."

@Akira
"Did you lose track of the time again?"

@Ichinari
"Yeah, something like that."

@Ichinari
"What about you? Were you still working?"

@Ichinari
"Today's a really late one, isn't it?"

@Akira
"Uh, yeah. I'm kinda busy at the moment."

@Akira
"Although it's my own fault I'm so slow. Ahaha."

@Ichinari
"...?"

There's something off about her smile tonight.

It looks fake, like she's forcing it.

@Ichinari
"Akira-chan...?"

@Ichinari
"Did you have some trouble at work?"

@Akira
"Huh? Why would you ask that?"

@Akira
"No, everything's fine."

Tilting her head, she gives me a blank look, like she doesn't know what I'm talking about.

@Ichinari
"Well, if you say so..."

The gesture is so normal for her, I suddenly find myself unsure.

@Akira
"Hee hee. You're so weird, Ichi."

@Akira
"But thanks for caring."

@Akira
"I'm just gonna go get some fresh air out on the balcony."

@Ichinari
"...Is there really nothing wrong?"

I murmur to myself as she disappears behind the blinds.

She'd said everything was fine, so maybe I'm just imagining things...

@Ichinari
"Hmm...?"

I just can't shake the feeling that something's not quite right here.

@Akira
"Haa... I suck..."

@Akira
"I meant to be back to my usual happy self once I stepped through the door, but..."

@Akira
"I guess I'm just not cut out for this job."

@Akira
"Haa..."

@Ichinari
"Akira-chan?"

@Akira
"Hm? What is it, Ichi?"

@Akira
"Oh, you want a cuddle from Onee-chan?"

@Akira
"You're so spoiled, Ichi, what am I going to do with you?"

The humid summer air caresses my skin as I step out onto the balcony. Akira-chan flashes me her usual affectionate smile.

@Ichinari
"Well, I wouldn't say no, but that's not what I'm here for."

@Ichinari
"I've brought you some hot milk with honey, just how you like it."

@Ichinari
"It'll warm you up from the inside. Here you go."

I pass her the mug.

@Akira
"Ichi..."

@Akira
"Mm. Thanks."

I raise my own mug into the air and clink it against Akira-chan's in a toast.

@Akira
"Mm... You made this for me..."

@Akira
"I can feel it warming me up inside..."

She murmurs to herself as she gazes down at the ground below the balcony.

Beside her, I follow her gaze. Then I try asking her again.

@Ichinari
"Akira-chan, is something wrong?"

@Akira
"Ichi..."

@Akira
"No! I already told you, everything's fine."

@Akira
"What's with the inquisition? Are you worried about your onee-chan?"

@Akira
"Aww, you're sooo sweet♪"

Just like before, her smile looks forced.

This time, I look her straight in the eye and speak clearly and firmly.

@Ichinari
"Yeah, I am worried about you."

@Ichinari
"Because I can tell that you're hiding your pain."

@Akira
"Huh...?"

She seems at a loss for words.

@Ichinari
"You said you'd been beside me these last few years, right?"

@Ichinari
"Well I've been right there beside you, too."

@Ichinari
"So I know you."

@Ichinari
"And I can tell when something's wrong."

@Akira
"Ichi..."

She squeezes her hands tightly around her mug of milk.

Her eyes as round as saucers, she gazes back at me, seemingly in a daze.

@Ichinari
"I know I'm a loser, and you probably view me like a useless younger brother, but..."

@Ichinari
"I still care for and worry about you."

@Ichinari
"I mean, I may be a loser, but I still have my pride as a man."

@Ichinari
"So it hurts me to think that someone I care about can't trust me."

@Akira
"Ichi..."

@Akira
"Ngh, waaaaah! Waaaaaaah!"

@Akira
"Fweh... Weeeeeeehhhh!"

Squeezing her eyes shut, she starts to bawl. Fat tears slide down her porcelain cheeks.

@Ichinari
"A-Akira-chan, what's wrong?!"

@Ichinari
"A-Are you okay?!"

U-Um...! Er...! What do I do...?!

Totally at a loss, I peer into her wet face.

@Akira
"D-Don't mind me...! I'm fine...!"

@Akira
"Sorry, sorry...! I'm totally fine...!"

@Akira
"Wahhhh *sniff*...! Waaaaaaah!"

Even as she insists that she's fine, her small frame trembles as sobs wrack her body.

Her usually bright and cheerful face is now crumpled and wet with tears.

@Ichinari
"Akira-chan..."

My heart clenches painfully in my chest. Without thinking, I reach out and draw her head close to me.

@Akira
"*sniff* I-Ichi...?"

@Ichinari
"Don't worry, I've got you."

@Ichinari
"There's no need to try and act tough."

@Ichinari
"I'm here for you."

@Ichinari
"I'll always be here for you, whenever the going gets tough."

@Akira
"Ichi..."

I speak to her in a slow, soft tone as I try to ease her worries away.

At the same time, I gently stroke her hair...

...just like she always does for me.

@Ichinari
"Whenever I'm upset..."

@Ichinari
"...you always do this to calm me down."

@Ichinari
"So now let me do the same for you."

@Ichinari
"Like I said, I may be a loser, but I can still be the man you need."

@Akira
"Ichi..."

As she lets me stroke her head, Akira-chan's wide-eyed surprise slowly fades away.

@Akira
"To be honest..."

@Akira
"I did have a bad experience at work today."

@Akira
"I overheard some guys talking about how..."

@Akira
"...it's so easy for women. That they don't need any real skills..."

@Akira
"...and they can get an editing position just by looking good and sucking up."

@Akira
"It just kinda got me down. Heh."

She lets out a little derisive laugh, her eyes still wet with tears.

@Ichinari
"Well that's not true! You work super hard!"

@Ichinari
"I know that better than anyone—"

@Akira
"Mm. It's fine, though."

She presses her slim index finger to my lips.

I'd been leaning forward intently, and she gently reigns me in with a smile.

@Akira
"Because I have you."

@Akira
"Knowing I have someone who understands me the way you do..."

@Akira
"It reminds me that those guys are just dicks. Hee hee."

@Ichinari
"Akira-chan..."

Her laugh is more restrained than usual, but the vulnerability she'd shown a moment ago is gone.

Now her expression is one of gentle femininity... I haven't seen her look at me like this since the time she kissed me.

The sight sends warmth flooding through my chest. It's like there's something warm and fuzzy tickling at my insides.

@Ichinari
"Are you really okay now?"

@Akira
"Yeah. I really am this time."

@Akira
"Thanks, Ichi. Tee hee."

I remove my hand from where it'd still been stroking her head. She gives me a warm smile, reassuring me that I have nothing to worry about.

@Akira
"Something about you's changed, Ichi."

@Akira
"It's like you've become more proactive or something."

@Ichinari
"Proactive?"

@Akira
"Yeah. Although who you are inside hasn't changed."

@Akira
"It's just, like, you've become more...cool?"

@Akira
"Yeah, definitely more cool."

@Ichinari
"Hmm~ I don't really think I've changed at all."

@Akira
"It's a good change, so I wouldn't worry about it."

@Akira
"Right now, I'd be proud to say you're the man I'm in love with."

@Ichinari
"Well, I'm, uh...flattered..."

@Ichinari
"But if you're gonna fall in love with me for something as small as this..."

@Ichinari
"...I'd say that makes you the kind of trash who's attracted to other trash."

@Akira
"Ahaha~ I'm a trashy woman, huh?"

@Akira
"I'm fine with that."

@Akira
"I mean, I love you, and that's not gonna change♪"

@Akira
"So if I'm trash for that, then I guess I'm trash~ Tee hee~♪"

@Ichinari
"Akira-chan..."

She's completely open and forthright with her affections. Damn, she can be so cute sometimes...

The look on her face right now is making my heart flutter.

@Akira
"Mm, thanks to you I feel muuuuch better!"

@Akira
"Thanks for looking out for me."

@Ichinari
"Nah, I really didn't do anything."

@Akira
"Just one last thing..."

@Akira
"Think you could give me one more pet?"

@Ichinari
"Sure thing *pet pet*"

@Akira
"Mmhmhm~♪ Mmhmhmhm~♪"

@Akira
"Alrighty! I'm gonna POWER THROUGH! YEAH!"

@Akira
"I'm gonna go take a shower now!"

@Akira
"Oh, would you come wash my back for me?"

@Ichinari
"Er, I don't think that's a good idea right now..."

@Akira
"Juuuust kidding♪"

@Akira
"Thanks again. I love you, Ichi♪"

Akira-chan seems to be back to her old self. With a wave of her hand, she heads off to the bathroom.

After she's gone, I head back into the living room by myself. I flop back onto the sofa and stretch my hand up toward the ceiling.

@Ichinari
"...Have I really changed?"

I stare at my palm, which I'd just used to comfort someone else for the first time.

If I really have changed, then...I'm okay with that.

I want to work hard so I can repay the kindnesses bestowed upon me...

...by Akira-chan, Iori, and Nodoka.

@Ichinari
"Alrighty."

@Ichinari
"Let's get in a bit more practice."

Filled with energy, I leap up from the sofa. Then I sit down in front of my computer and grab my pen.

@Ichinari
"Whoa, there's a whole bunch of new releases."

I'm looking over the new releases shelf at Tomato Books. I go through the stacks of books, searching for one in particular.

What am I doing by myself in Tomato Books? Well...

@Nodoka
"Iori-saaaaan!"

@Nodoka
"How could you forget to tell me about a 16-page coloring job?!"

@Nodoka
"And a two-day deadline—that's insane! Seriously, are you crazy?!"

@Iori
"W-Well there's nothing I can do about that now, is there?!"

@Iori
"I'll make it up to you after. For now, if you have time to complain, you should be using it to work!"

While I can assist with drawing, I've yet to master Iori's coloring techniques. It still takes a long time for me to mimic her style.

Which means I had no chance of keeping up with the two of them as they abruptly switched to coloring mode in perfectly-matched synchronization.

I'd only slow them down if I tried to help, so in order to avoid disrupting them, I left them to their deadline hell and headed out into town.

I feel most at ease in places like this. As I browse the shelves, as I feel as refreshed as though I'm going for a stroll through the forest.

@Akira
"Please! I'm begging you!"

@Akira
"Please! I promise you!"

@Ichinari
"I know that voice..."

A familiar voice resonates through the store.

Following the sound, I peek around a shelf toward the corner of the shop floor.

@Akira
"I promise you, this author is going to be the next big thing!"

@Akira
"So could you please push this book?!"

Akira-chan is fervently bowing her head to someone.

@Shopkeep
"I know you have a lot riding on this, but we're a business too, you know..."

The person before her looks to be the manager, and she's holding a comic in their hands.

I stare at it, suspicion already rising in my mind—sure enough, the cover is one I know all too well.

@Ichinari
"...That's my comic, isn't it."

It is, without a doubt, a copy of my anthology.

@Akira
"Ichineri-sensei's working super hard right now!"

@Akira
"And he's training under Ishitaka-sensei, so he's definitely gonna make it big now!"

@Akira
"So I have to work hard on my end too!"

@Akira
"Just a small space is fine, so please!"

...Has she been going this far in her promotional duties for me?

I'm always jokingly telling her I'm just lying low and biding my time...

And she's always telling me not to worry my head about things...

@Ichinari
"Akira-chan..."

As I stare at her figure, hunched over in a deep bow, I find my hands clenching into fists, and I hold my breath.

@Akira
"He'll do anything you need—signings or meet and greets; part-time stocktaking, or even cleaning!"

@Akira
"I'll get you as many original, signed prints as you like to put up on the walls!"

@Akira
"So please, please support Ichineri-sensei!"

Hearing her desperation, my heart throbs painfully in my chest.

...Stocktaking and cleaning don't seem like tasks usually asked of manga artists, but I'm willing to do anything she needs me to.

@Shopkeep
"Hmm, well it is hard to say no to a request from you, Higashibojo-san..."

@Shopkeep
"I suppose there's enough space over there for a small sign."

@Akira
"Thank you so much! That will be plenty!"

@Akira
"...There we go."

@Akira
"Alright, that should do it."

She's stacked a few copies of my book backed by a small, handmade sign.

@Akira
"Hee hee♪ Do your best, Signy♪"

@Akira
"You're Ichi's head cheerleader, understand?"

@Akira
"So you've gotta support him by showing yourself off to lots of people, 'kay?"

Akira-chan smiles to herself as she gives the little sign an affectionate prod.

@Ichinari
"Akira-chan...!"

I'm so, so grateful to her. A lump rises to my throat unbidden, and I swallow hard.

@Akira
"...Huh?"

@Akira
"Ichi, is that you...?"

@Akira
"Wh-What are you doing here?!"

Akira-chan notices my presence and turns to face me.

@Ichinari
"Akira-chan...! I...I...!"

@Akira
"Hey now, don't you dare start crying in public!"

@Ichinari
"I...!"

@Ichinari
"I had no idea you were going to such lengths for me...!"

@Akira
"Hee hee. It's nothing to cry about, silly."

@Akira
"I am your editor, after all."

@Akira
"This is just part of the job."

@Akira
"Come on, let's get you outside."

@Akira
"It must be fate, us meeting here, so Onee-chan will treat you to lunch."

@Ichinari
"*sniff* I'd be forever in your debt...!"

Now I'm about to be moved to tears for a different reason.

@Akira
"Ahh, that was yummy♪"

@Akira
"There's nothing like ramen to bring you back to life♪"

After leaving the famous ramen restaurant, Akira-chan and I walk shoulder-to-shoulder along the road to the station.

@Ichinari
"Sorry you always end up paying for me..."

@Akira
"Don't worry—since it's lunch with an author, I can put it on expenses."

@Akira
"Although since that author is you, I might not get anything back."

@Ichinari
"Pretty sure they can't do that."

@Akira
"Ahaha♪ Juuust kidding♪"

@Akira
"You're a serialized author, so they have the budget for that. Probably."

@Ichinari
"My sincerest apologies for always being such a disappointment."

Even if my anthology doesn't sell and my serialization is on hold, they still have to reimburse my expenses, right?!

Although I'm starting to worry about my treatment within the editorial department, I do my best to put it out of my mind.

@Ichinari
"...Thanks, Akira-chan"

@Ichinari
"I'm glad I got to see all the extra effort you're making."

@Ichinari
"It's really inspired me."

@Akira
"It's our job as editors to make sure you artists can focus on creating."

@Akira
"Since we can't help with that aspect of things."

@Akira
"So of course I do everything I can for my client."

Smiling her usual bright smile, she says it like it's the most natural thing in the world.

The difference between amateur and commercial work has come up in conversation before, but I understand better now just how much support we artists get from the editorial department.

Now I have this extra kick in the butt that's made me realize success is not just for ourselves. 

@Ichinari
"There's just one thing I want to ask..."

@Ichinari
"Why are you trying to promote me now?"

@Ichinari
"It's not like I have a new comic out or anything."

I ask her the question that had popped into my head.

@Akira
"Ah, well, that's because, you know..."

She scratches at her cheek, looking like I've put her on the spot, and shoots me an awkward glance.

@Akira
"Remember how you comforted me recently?"

@Akira
"You stroked my head out on the balcony that time."

@Akira
"And it got me thinking..."

@Akira
"That this time, I want to be proactive, get results, and show those dicks at the company what I'm capable of."

@Akira
"And so I decided to really push your books."

@Akira
"As your editor, I believe you'll make it, Ichineri-sensei."

@Ichinari
"Akira-chan..."

@Akira
"I really, really love your work."

@Akira
"It's straightforward and awkward—it's just like you."

@Akira
"I can't draw manga myself, but I can support you while you do."

Cheeks slightly flushed, she averts her gaze and looks down at the ground.

@Akira
"No, actually..."

@Akira
"I may have lied a little..."

@Ichinari
"Lied?"

@Ichinari
"About what?"

As I ask her, she peers into my face with a mischievous smile.

@Akira
"When I said that I believe in Ichineri-sensei, as his editor..."

@Akira
"That was half true, but..."

@Akira
"Really, I believe in you."

@Akira
"I believe that Ichinari Tsuzurigi will make it."

@Ichinari
"Akira-chan..."

@Akira
"And so I'll support you, both as your editor, and as Akira Higashibojo."

@Akira
"I know you're not supposed to mix business and personal matters, but who cares."

She sticks her tongue out at the concept then giggle self-consciously.

@Ichinari
"I'm flattered you have such faith in me..."

@Ichinari
"Although for now I'm focusing on being a pro assistant, so I'm not sure when I can restart my serialization..."

@Akira
"I told you not to worry, silly."

@Akira
"I'm doing this because I want to."

@Akira
"I think of it as investing for the future—in both love and business♪"

@Ichinari
"You're so cool, Akira-chan."

@Akira
"That's my selling point!"

@Akira
"Now that you happened to see me working..."

@Akira
"...it'd be nice if that swayed your heart in my direction. Kidding♪"

She speaks her mind with characteristic buoyancy.

Then she links her hands together behind her back and looks up at the sky.

@Akira
"But, y'know, I'm enjoying how things are at the moment."

@Akira
"Of course, I love you, and I want to be your girlfriend."

@Akira
"But..."

@Akira
"On the other hand, if you don't tie yourself down to anyone..."

@Akira
"...things can go on how they are. It's a complicated feeling. Ahaha~"

@Ichinari
"Not tie myself down to anyone...?"

@Ichinari
"You mean, have everything stay all weird and unresolved like it is now?"

@Akira
"I think it depends on the person as to whether they find it weird."

@Ichinari
"Huh? What do you mean?"

@Akira
"Oh, nothing, it was just a random thought."

@Akira
"Don't think about things so hard and just follow your instinct♪"

I don't sense any hint of worry or jealousy from her.

She pats me lightly on the chest then starts walking, humming to herself as she goes.

@Ichinari
"Uh, hey...!"

@Ichinari
"What did you mean by that, Akira-chan?"

@Ichinari
"About how it depends on the person?"

@Akira
"I already told you, I didn't mean anything."

@Akira
"Anyway, don't tell the others about what you saw today, 'kay?"

@Akira
"We editors aren't supposed to let the authors know of our behind-the-scenes struggles."

@Ichinari
"Whaaat? But it's such a good story."

@Akira
"Nooo, they don't need to hear about it."

@Akira
"I mean, Iori-chan and Nodoka-chan get promoted by the stores even without me having to push it."

@Ichinari
"I'm sorry to be such trouble to you, Oh Great Editor."

@Akira
"Ahaha! I like the troublemakers the best~"

@Akira
"I have high hopes for you, Ichi♪"

@Ichinari
"Owwies! Ow!"

@Ichinari
"Akira-chan, you don't know your own strength!"

I complain as Akira-chan gives me a hearty slap on the back.

We continue walking along the streets of Yokohama, side by side.

