#start|Happiness is Coming

@Iori
"Huh...?"

@Iori
"Uh... Huh?"

@Ichinari
"Hm? Iori? What's up?"

I ask Iori, who's peering behind her computer.

@Iori
"My screen suddenly turned off..."

@Iori
"Huh? That's weird... Umm..."

@Ichinari
"Really? Let's have a look."

@Ichinari
"The keyboard and mouse aren't responding either."

@Iori
"And nothing happens when I press the power switch."

@Iori
"All my work data is backed up, so there's nothing to worry about there."

@Iori
"But I'm in a pickle now... I can't work without a computer."

@Iori
"Nodoka would probably know what the problem is, but..."

@Iori
"She's out at the salon today."

She'd headed out this morning saying she was going to beautify herself for Senpai.

While I'm flattered that my girlfriend would do that for me, I can't really tell what effect spa treatments have. Sorry, Nodoka.

Akira-chan is also working at the company today, so it's just me and Iori.

@Ichinari
"She'll be back this evening though."

@Ichinari
"You're not pressed for time right now, so why not take today off?"

@Ichinari
"You're always working."

@Iori
"Hmm, I guess I could..."

@Iori
"..."

@Iori
"...Wanna get freaky until then?"

@Iori
"I mean, I can't use my computer, so what else are we gonna do? Right?"

@Ichinari
"We can't help that YOUR computer's broken, but..."

@Ichinari
"If I don't make any progress, I'm not gonna be able to face Nodoka and Akira-chan."

@Iori
"Ugh... Well..."

@Ichinari
"We were just talking yesterday about how if we descend into depravity, we'll lose our hold on the things important to us."

@Iori
"Ughhh... I know..."

Nodoka had finished up her work before she left.

How disgraceful would it be if I had to admit I'd got no work done because I was too busy literally screwing around?

@Ichinari
"Although, I mean, I do wanna do stuff with you, too."

@Iori
"Really? You really do? You're not lying?"

@Ichinari
"I wouldn't lie about that."

@Iori
"..."

@Iori
"So you're saying that if you finish your work, we can do it with no problems?"

@Iori
"That, once you're done, we can fuck to our hearts' content?"

@Ichinari
"Huh? Uh, well..."

@Ichinari
"I guess...?"

@Iori
"I understand."

@Iori
"Mind if I use your computer for a moment?"

@Ichinari
"Uh, sure, go ahead."

I stand up and let Iori take my seat.

@Ichinari
"Iori? What are you doing...?"

@Iori
"Okay."

@Iori
"I'm gonna focus REAL hard now, so stay quiet for a bit."

@Ichinari
"Huh? Focus on what?"

@Iori
"*Deep breath*"

@Iori
"...!"

@Iori
"Nnnnnnnnghhh~!"

@Ichinari
"Huh? What are you—?! Iori?!"

@Iori
"Ngh, it's been ages since I've focused so hard on something~♪"

She stretches energetically.

@Iori
"Your work is all done, so now we're free to go on a da—"

@Iori
"Ahem. We're free to go look for a new computer for me, right?"

@Ichinari
"Uh... Right..."

It's about two hours later. Iori had finished up my quota for me in no time, so now we're heading out to Toyohashi Camera together.

God-tier artists are incredible when they unleash their full powers.

And she unleashed it so she could go on a shopping date with me. I feel a complex mix of flattered and awed.

@Ichinari
"But wouldn't it be better to have Nodoka take a look at it before you go buying a brand new one?"

@Iori
"I've had that one for a while, so I think it's about time to get a replacement."

@Iori
"Plus this way I have an excuse to go on a date with you."

She pouts at me, her cheeks flushed.

@Ichinari
"You are too cute, Iori."

@Iori
"Really? Do I deserve a pet?"

@Ichinari
"Yeah, yeah. *pet pet*"

@Iori
"Tee hee~♪ It was worth all the effort, hee hee~♪"

@Iori
"A-Also..."

@Ichinari
"Yeah, what is it?"

@Iori
"Could we hold hands?"

@Ichinari
"..."

@Iori
"Ichinari?"

@Ichinari
"Argh, geez! YOU ARE TOOO CUTE, IORI! *pet pet pet*"

@Iori
"Yaaay~♪ Pet me more, Ichinari~♪"

This is already shaping up to be a great date. We make our way to Toyohashi Camera together.

@Iori
"Hmm."

@Iori
"I don't really know what's good, so maybe I should just get the same as I had before?"

@Iori
"It had good specs and was easy to use."

Iori mumbles to herself as she gazes at an embedded LCD tablet.

It's 570,000 yen, including tax.

@Ichinari
"Sure, looks good."

I respond robotically to her usual grand shopping habits.

I'm not really in any position to be looking after her, am I?

Given her previous work speed, too, I really feel like she's the one protecting me.

@Clerk
"Are you looking for an all-in-one computer?"

@Iori
"...!"

@Iori
"Ichinari...! Ichinari!"

Iori hides behind me, looking like she's about to burst into tears.

@Clerk
"Umm... Shall I leave you to it?"

@Ichinari
"Oh, don't mind her, this is just how she is."

@Iori
"Ichinari! Take my card...!"

@Ichinari
"We'll be paying by card."

@Iori
"O-Options...! I'll take all the extras!"

@Iori
"The one with the highest specs...!"

@Ichinari
"The one with the best specs plus all the extra bells and whistles, please."

@Clerk
"Erm... Of course!"

Aaand the god-tier artist's social anxiety never lets her down.

@Ichinari
"They said they'll deliver it later on tonight."

@Iori
"Mm. I'm glad they had it in stock."

I hand Iori her credit card and the delivery receipt.

@Iori
"Hee hee. We did the same thing just a little while back, didn't we?"

@Ichinari
"When I'd just joined your team."

@Iori
"At the time, I never thought I'd become your girlfriend."

@Iori
"Although I may have hoped. Hee hee."

@Ichinari
"I never thought I'd get such an adorable girlfriend either."

@Ichinari
"I was on the brink of quitting manga entirely, too."

@Iori
"Hee hee. Well I'm glad you found me."

She says it with a gentle, open smile that's totally different to back then. Squeezing my hand, she smiles up at me.

@Ichinari
"Although that's not the only reason I love you, of course."

@Iori
"Ichinari..."

I answer her smile with one of my own; and I squeeze her hand back a little tighter in return.

@Iori
"Ichinari?"

@Iori
"We still have some time, so... Um..."

@Iori
"..."

Her words trail off at the end as she looks down at the ground. She glances up at me awkwardly through her lashes.

I know what she's trying to say. This time I'll take the initiative.

@Ichinari
"Well, since we have more time than I expected..."

@Ichinari
"Shall we keep this date going a bit longer?"

@Iori
"Ichinari..."

@Iori
"I-Is that okay?"

@Ichinari
"It's not a case of me just being okay with it. I said I wanted to go on a date with you, didn't I?"

@Iori
"Ichinari..."

@Iori
"Yeah. You're right, you did say that."

@Iori
"I'm so happy! Tee hee."

We fall into step beside one another, our fingers still entwined together.

@Ichinari
"I know I'm the one who suggested it, but..."

@Ichinari
"What do you even do on a date anyway?"

@Iori
"I've never been on a date, so I have no idea either."

We've come to Sakuragicho, a popular date spot, but neither of us know what to do next, so we're kinda stumped.

@Iori
"I've researched it and gathered info for drawing scenes in my manga, but..."

@Ichinari
"I generally skip right over the date scenes."

Readers of hentai manga are there for the sex, so date scenes are considered a bit of a waste of space.

The ideal is to get down to business within three pages from the beginning.

While you could say that sex is an extension of romance, hentai manga is always predominantly about the sex.

@Iori
"We didn't have the usual teenage romance experience, did we..."

@Iori
"Not that I think I would have had it even if I'd chosen a different career path."

@Ichinari
"I'm absolutely with you on that."

It's kind of reassuring to hear that from her.

I'm one thing, but she's a total hottie! Besides, her lack of experience is also kind of part of her appeal.

I don't think Akira-chan's ever been on a date either. My girlfriends are all extreme, in one way or another.

@Iori
"But maybe we don't really have to do anything in particular?"

@Iori
"I'm honestly so, so happy..."

@Iori
"...just walking around with you hand in hand like this."

@Ichinari
"Iori..."

@Ichinari
"That kinda makes me feel like a pathetic excuse for a boyfriend."

@Iori
"Hee hee! No way."

@Iori
"I told you before, remember—up there."

She points up to the very top of Symbolic Tower.

@Iori
"You make me happier than anything else in the world."

@Iori
"More than any luxury, or any success."

@Iori
"I am truly happy with you, Ichinari."

@Ichinari
"Iori..."

Her expression is a picture of bliss as she squeezes my hand ever so gently, but tightly.

I can feel her warmth flowing into me, and my heart aches sweetly in my chest.

@Iori
"Just having you hold my hand and smile at me..."

@Iori
"That alone makes my heart feel like it's about to burst."

@Iori
"Even though we've already been all the way... It's strange. Hee hee."

@Ichinari
"Yeah. I get it."

@Ichinari
"I feel the same way."

It doesn't matter what we do or don't do; being beside the one you love is happiness in and of itself.

We don't need to follow the manual and go around the prescribed date spots. I can tangibly feel that our happiness is already right here, between us.

@Iori
"So it's the same for you."

@Iori
"Hee hee! I'm so happy. Tee hee♪"

We continue walking along the street with silly grins on our faces and our hands entwined.

@Iori
"Oh, hey..."

@Iori
"Since we're here, why don't we ride that together?"

@Ichinari
"By that, you mean..."

@Iori
"Wow, the sunset is so beautiful."

We're at the top of the huge ferris wheel at Minatomirai.

We gaze down at the streets of Yokohama below, gilded by the rays of the setting sun. Iori's gentle voice reverberates through the small gondola.

@Iori
"You know, there's a superstition about this ferris wheel."

@Ichinari
"There is?"

Still staring out the window, Iori hugs my arm even tighter.

@Iori
"That any couple who kisses at the top of the wheel will be together forever."

@Iori
"I heard about it when I was doing research for work, and I didn't think anything of it at the time."

@Iori
"But now that I'm up here, it sounds kind of wonderful. Hee hee."

Turning her gaze to me, she giggle bashfully.

@Ichinari
"You can be such a girly girl, Iori."

@Iori
"Well I did always believe in a promise I never knew would actually be fulfilled."

@Ichinari
"That's true."

I smile as I think back on the memory from ten years ago.

Snuggling together, gaze down on the city where we were brought together again.

@Iori
"We're really lovers now."

@Iori
"Even now, it still feels like a dream."

@Ichinari
"And to think that just a little while back I was thinking of quitting manga outright."

@Ichinari
"And now I get to continue my work, I live in an amazing apartment..."

@Ichinari
"...and, most importantly, I have this amazingly adorable girlfriend."

@Ichinari
"I think I must be the one who's dreaming."

@Iori
"Hee hee. Then I guess we both are."

@Iori
"Shall we pinch each other's cheeks?"

@Ichinari
"But if it is a dream, I don't wanna wake up."

@Iori
"Ahaha. Don't worry. It's not a dream."

She rests her head lovingly on my shoulder.

Her gentle warmth seeps into me. It helps me feel like this is really real.

When I look out the window again, I can tell that we're approaching the peak.

@Ichinari
"We're almost at the top."

@Iori
"Yeah. Almost."

Our voices are muted.

We turn slowly to gaze into each other's eyes.

We naturally lean in toward one another.

@Iori
"Mm... Ichinari..."

@Ichinari
"Iori..."

@Ichinari
"I love you, Iori."

@Iori
"Hee hee."

@Iori
"You're a girly girl yourself, Ichinari."

@Iori
"Saying something like that in a scene like this."

Her voice is quiet and her smile affectionate.

The warm evening sun illuminates her face.

@Ichinari
"Superstition includes stuff like Fates."

@Ichinari
"So, given what we know about Fates, we should probably believe it."

@Iori
"Hee hee. Right."

@Iori
"We all have to believe."

Her smile is so pure and innocent, and her cheeks are flushed redder than the fiery sun.

@Ichinari
"I know I'm not quite worthy yet, but..."

@Ichinari
"I'll do my very best to always make you happy."

@Iori
"Yeah. Me too."

@Iori
"I'll do my very best to make you happy, too."

We make a promise to each other again.

The gondola sways slightly.

We stay snuggled up together until we arrive back at the bottom.

@Ichinari
"It's getting late."

When we alight from the ferris wheel I check my phone to see it's already 5 p.m.

The sun's rays seem to be weakening, too.

@Ichinari
"We should probably—"

@Iori
"Ichinari..."

I still have my phone in my hand. Iori reaches out to cover the screen.

@Ichinari
"Iori?"

I say her name quietly. She hangs her head, her expression conflicted.

@Iori
"I...don't want to go back yet."

She says it so quietly I can barely hear her.

@Iori
"I don't want to end the date yet..."

@Iori
"I know it's not fair of me to ask that."

@Iori
"I know that, but...!"

She raises her head determinedly and the pleading look in her eyes makes me swallow my words.

Her hand is still covering my phone screen. I lay my own hand on top of hers.

@Iori
"I...can't take it any longer..."

@Iori
"I love you so much, I...I..."

@Ichinari
"Iori..."

She's adorable.

I wrap my arms around my cute little Iori.

