#start|Happiness is Coming

And I cut any further words off with a kiss.

@Iori
"Mm... Mmph?!"

@Iori
"Ichi...nari..."

@Iori
"Mm...mm..."

@Iori
"Mm... Mmph, haa... Mm..."

@Iori
"Haa, haa... Ichinari..."

Misty-eyed, she nestles limply against me.

@Ichinari
"I promised to make you happy..."

@Ichinari
"And yet I'm making you have to ask for things. I'm sorry."

@Ichinari
"I'll let Nodoka and Akira-chan know we'll be home late."

@Ichinari
"So will you stay with me a while longer?"

@Iori
"Ichinari..."

@Iori
"Yeah... I want to spend more time with you, too."

She nods and I take her hand in mine. Then I hail a conveniently passing cab.

@Iori
"Mm... Ichinari... Mmm!"

@Iori
"Ahn, mm! Mllp, ngh, mwah, ngh!"

@Iori
"Haa! Mm, mwah, shllp, mlllp!"

@Ichinari
"Iori... Mwah, mllp, ngh, mm!"

@Iori
"Haa... Kissing feels good... Really, really gooood."

@Iori
"Look at us...going at it the moment we entered the hotel..."

@Iori
"You couldn't hold back any longer either? Haa..."

@Ichinari
"Well you were looking at me so seductively..."

@Iori
"Yeah... I mean, all through our date..."

@Iori
"I've been wanting to kiss you... So please, kiss me more..."

@Ichinari
"Yeah, I will."

@Iori
"Hahn, mwah, mllp! Mmm, ngh, mmm!"

@Iori
"Shllp, mllp! Mmm! Haa, ngh, mmm!"

@Iori
"Ngh, haa, ah! More...tongue...mmm!"

@Iori
"Give me a real...deep, sloppy kiss...ngh!"

@Ichinari
"Iori... Stick your tongue out further."

@Iori
"Ngh, l-like this? Mwah! Mllp, shllrrp!"

@Iori/Iori
"Shllp! Mmm! Mwah, mllp, shllrrp!"

@Iori
"Haa, ah! This is so hot...I'm tingling all over!"

@Iori
"Ichinari, mm, Ichinari! Shllp, mllp! Shlllrrrrp!"

@Iori
"Haa, haa... I'm covered in...Ichinari's saliva..."

@Iori
"All around my mouth is...so wet and sticky... Haa, haa!"

@Ichinari
"You're making such a lewd face, Iori."

@Iori
"Well... I mean... Your kisses feel so good... You're making me feel amazing."

@Iori
"I...can't think of anything but sex right now."

@Iori
"I wanna go even further, Ichinari."

@Iori
"Aha♪ You're sooo hard, Ichinari♪"

@Iori
"And you're all wet and sticky down here, too♪ Haa♪"

@Iori
"Did you get so hard because of me? From kissing me?"

@Iori
"Did your cock swell from wanting to be inside me?"

Iori's fingers make a wet sound as they wrap around my length.

@Ichinari
"I-Iori! Ah, gah!"

@Iori
"Hee hee♪ Does it feel good when I stroke it like this?"

@Iori
"Go ahead... If it feels good, let me hear it♪"

@Ichinari
"Ngh... Y-Yeah, it feels good."

@Iori
"Aha, I'm glad♪ I'm getting Ichinari off with my hand♪"

@Iori
"Okay, I'm gonna make it feel even better."

She grips my rod tightly.

Then she starts to slowly move her hand up and down.

@Iori
"Haa♪ It's sooo hot and hard♪"

@Iori
"It feels so naughty, having your dick in my hand. I'm getting wet too♪ Haa♪"

@Iori
"Hmm, you like it like this? I bet this part here is real sensitive..."

Shlick, shlick, shlick, shlup.

@Ichinari
"Ah, gah! Ah!"

@Ichinari
"I-Iori! That feels...fucking incredible!"

@Iori
"Aha♪ Listen to you, moaning like a girl♪"

@Iori
"Do you like this? Does my hand make you feel that good?"

@Ichinari
"Y-Yeah! I love it!"

@Iori
"Haa♪ My body won't stop shuddering♪ Mmm♪"

@Iori
"I...can't can't control myself either♪ Mm♪"

@Iori
"Mm! Ah,m haa, ah, aah!"

@Iori
"I can't...believe how wet I am♪ Mm, mmm♪"

@Ichinari
"I-Iori? Are you...fingering yourself?"

@Iori
"Yeah... I couldn't restrain myself♪ Ah, haa♪"

@Iori
"Listen... Can you hear how dripping wet I am?"

@Iori
"I'm getting myself off...while jerking Ichinari's cock♪ Ahh♪"

@Iori
"I'm so turned on... My panties are flooded..."

@Ichinari
"Iori... You're so fucking hot!"

@Iori
"Hee hee, yay♪ Your dick is twitching for me♪"

@Iori
"If you like it...I'll get even more lewd for you♪"

@Iori
"Look, I'll use my juices to get your cock all nice and slippery."

@Iori
"Maybe this'll feel even more amazing for you?♪ Ngh♪"

@Ichinari
"Ah, w-wait a—!"

@Ichinari
"If you do that, I'll...!"

@Iori
"Mmm♪ Ngh, mwah, mllp♪ Shlllp♪"

@Iori
"Mllp, shllrrp, mm♪ Mwah, mllp, shllp♪"

@Iori
"Hee hee, c'mon! Let me tongue-fuck your mouth, too♪"

@Iori
"Just relax and enjoy it♪"

@Iori
"C'mon... I'm gonna go even harder on you now♪"

@Iori
"Give in... Give in to the pleasure..."

@Iori
"Ngh, mlllp♪ Shlurp, mwah♪ Hahn, ngh, mm, mllp♪"

Shlick, shlick, shlick, shlup.

@Ichinari
"Mmmm! I-Iori!"

@Ichinari
"I-I'm...! I'm gonna...! Mmmmmm!"

@Iori
"Mmm♪ Ngh, haa... You're squirting so much jizz♪ Mm, haa♪"

@Iori
"I'll keep going right to the end and milk it all out of you♪"

@Iori
"Hahn, mwah, mllp♪ Mwah, shllp, shlurp, mmm♪"

@Ichinari
"Iori! Ngh, mmmm!"

@Iori
"Mmm♪ Mwah, mllp, shlllp, mwah, shllrrrp♪"

@Iori
"Shllp, mm, haa♪ Ngh, mllp, shllrrp♪ Mmm♪"

@Iori
"Haa, haa♪ Aah, ah, haa♪"

@Iori
"Aha, you came a lot, didn't you? You came so much for me♪"

@Iori
"I came too... I got myself off while you blew your load♪ Haa♪"

@Iori
"I've never...got so wet from fingering myself before♪"

Her thighs are drenched in her love juices.

There's so much it's even dripping down onto the floor.

She licks the milky white cum off her fingers.

Then she turns her hazy gaze on me and smiles.

@Ichinari
"Aah, that was incredible."

@Ichinari
"But now it's my turn to make you feel good."

@Ichinari
"I don't think I'm gonna be able to go easy on you... That okay?"

@Iori
"Yeah♪ I want you to fuck me up real good, Ichinari♪"

@Iori
"C'mon, hurry up and put your fat dick in me♪"

@Iori
"Nyaaaaah! Ah, aaaaah!"

@Iori
"Ah, aaah♪ Ichinari's dick is inside me♪ Ah, nyaaah♪"

@Ichinari
"Whoa?!"

@Ichinari
"Fuck, you're so wet and slippery! Gah!"

@Iori
"Well you can't blame me♪ It's because I licked your jizz♪"

@Iori
"Ah, aaah♪ Haaa♪"

@Iori
"I-I can't take it! H-Hurry up! Hurry up and fuck me!"

@Iori
"I-I'm...already about to cum!"

@Iori
"This is so frustrating... You're driving me insane!"

@Iori
"Please, give it to me! Fuck my pussy up♪"

@Ichinari
"Yeah! I'm gonna fuck you, Iori!"

@Iori
"Ah! Nyah, aah! Ah, aah, aaah!"

@Iori
"Ah, wow! Aah, i-it feels so good! You're amazing, Ichinari!"

@Ichinari
"Me too! It feels fucking incredible for me too, Iori!"

@Iori
"Th-This time is...even more intense than before! Ah, aaah!"

@Iori
"It's too much! I just came...but I'm already about to cum again!"

@Iori
"Ah, aaah! Ngh, ah, aaah!"

@Iori
"I-Ichinari? I can take it even deeper and harder..."

@Iori
"So do whatever you like to me, okay? Destroy my pussy!"

@Iori
"I'm gonna cum soon too, so...you should get yourself there too..."

@Ichinari
"Do you want me to go harder? Do you want me to make you cum?"

@Iori
"Y-Yes! I wanna cum! Not from my fingers, but from your cock!"

@Ichinari
"Then...do you think you can beg for it?"

@Iori
"Huh? Beg...?"

@Ichinari
"You know what I mean. You're always drawing it in your manga."

@Iori
"That's...just because it's my job..."

@Ichinari
"But I wanna hear my sweet Iori begging me."

@Ichinari
"If you can do that for me, I'll fuck you harder. Okay?"

@Iori
"I-Ichinari..."

@Iori
"Nnngh!"

@Iori
"F-Fine... I'll beg!"

@Iori
"I'll do it!"

@Iori
"F-Fuck me...! Shove your dick into my pussy!"

@Iori
"Make me...feel really good...!"

@Ichinari
"You're not doing it right."

@Ichinari
"Ishitaka-sensei should know that's not how it goes."

@Iori
"Uuuugh! You're so mean, Ichinari!"

@Iori
"I-It's so embarrassing...being made to say it in my own words!"

@Ichinari
"But I can feel you getting even wetter inside."

@Ichinari
"So this is turning you on too, right?"

@Iori
"Uuuuugh! D-Don't say that!"

@Iori
"I-I'll do it! I'll beg like a good girl, so...! Uuuugh~!"

@Iori
"D-Destroy my sloppy wet pussy..."

@Iori
"Fuck Iori's hole with your fat cock!"

@Iori
"M-Make me cum harder than I ever have! Please... Please!"

@Iori
"Ughhh! This is SO embarrassing!"

@Iori
"I'm so ashamed to be begging you, and yet...I-I'm getting even more turned on!"

@Iori
"P-Please...! I'm begging you, fuck me harder!"

@Ichinari
"Yeah, good girl, that's what I wanted to hear."

@Ichinari
"You're so cute when you're honest, Iori."

@Ichinari
"Now I'll give you your reward."

@Iori
"Ah, aah! Nyah! Ah, aaaah!"

@Iori
"That's so gooood! Ngh, aaah! Aaaaah!"

@Iori
"No, it's too much! You're gonna make me cum...right away!"

@Iori
"Ah, aah! Ah! Nyah, aaaaah!"

@Iori
"Aaaaaaah! Ah, hyah! Hyaaaaah!"

@Iori
"I-I'm cumming! I'm cumming...soooo hard!"

@Iori
"Wait! Just wait for a second! Uwaaaaaah!"

@Ichinari
"But you begged me to make you cum, didn't you?"

@Ichinari
"So go on and cum as many times as you like."

@Ichinari
"But you've gotta keep going until I make it there too, okay?"

@Iori
"I-I can't...! I can't!"

@Iori
"I-I've already...cum so many times! Ah, ooooh!"

@Iori
"I-I'm going crazy! I've cum too much, I'm losing my mind!"

@Iori
"Ah, I'm cumming, I'm cumming, I'm cumming! I'm cumming agai— Ah, aaaaaaah!"

@Ichinari
"Your pussy's clamping down on me so tightly!"

@Ichinari
"Do you get off on being tormented like this?"

@Iori
"N-No! It's not that I like being tormented!"

@Iori
"It's because I'm being tormented by you... By the man I love!"

@Iori
"I wouldn't like it if it was just torture! I wouldn't get like this for anyone else!"

@Iori
"Ah, aaah! Ah, no, I'm—! I'm cumming agaiiiiiiin!"

@Ichinari
"You're so fucking cute, Iori."

@Iori
"Ah, aaaah! Please cum already, please!"

@Iori
"I can't believe... I can't believe I'm still cumming!"

@Iori
"I...! I'm going insaaane! Nyaaaaaaaah!"

@Iori
"Please, cum in me! Hurry up and shoot your load!"

@Iori
"Please, I'm begging you! Hurry, do it nooow!"

@Iori
"If you don't, I'll—! Nyaaaaah, ooooh!"

@Ichinari
"Iori! I'm almost there!"

@Iori
"D-Do it! Cum in meee!"

@Iori
"P-Please! I'm begging you... Fill my pussy up with your cum!"

@Iori
"Fill me up with your hot jizz! Please, cum for me! Nyaaaah!"

@Iori
"Ah, ah! Aaah! Ah, nyaaaaaaah!"

@Iori
"Haa, haa! Aaaaah, mm!"

@Iori
"Haa, aaaah! Ah, it's coming out!"

@Iori
"Aah, mm, ah, aah."

@Iori
"Haa, haa... You came so much... Haa."

@Iori
"Haa, haa, ooh, haa."

@Ichinari
"You okay, Iori?"

@Ichinari
"Sorry, I kinda lost control there."

@Iori
"No, I'm fine. I'm super duper happy♪"

@Iori
"Are you happy too...? Did I get you off good and proper?"

@Ichinari
"Yeah, you did a real good job."

@Iori
"Hee hee. I'm glad to hear it♪"

@Iori
"It makes me sooo happy to know I could satisfy the man I love. Tee hee♪"

@Ichinari
"Really?"

@Iori
"Yep. I am your girlfriend, after all."

@Iori
"Isn't it normal to want to satisfy the person you love?"

@Ichinari
"Man, you really do say the sweetest things."

@Ichinari
"If that's how you really feel..."

@Ichinari
"Then how about we go one more round?"

@Iori
"Huh? One more...?"

@Iori
"Nyaaah! Ah, nyah, ah! Aaaaaah!"

@Iori
"I-Ichinari! You can't just suddenly—! Ah, aah! Aaaaah!"

@Iori
"N-Noooo! I'm going to cum, I'm going to cum again! Ah, aaaaaaaaahhhnnn!"

@Iori
"Ah, aaaah! Ah, aaah, nooo! I'm cumming again! Ah, aaaaaah!"

@Ichinari
"Gah! Your pussy's even more sopping wet than before!"

@Iori
"I-I don't understand! I don't get it, but I'm still turned on from cumming before!"

@Iori
"I-I'm cumming already! Ah, aaaaah! Nyaah, aaaaaaah!"

@Iori
"It just keeps going! Aaaah, I'm cumming agaaaiiiin! Nyaaah, ah, aaaaaah!"

@Ichinari
"Iori, are you just having one continuous orgasm?"

@Ichinari
"Guh! You just keep cumming and it feels incredible inside!"

@Iori
"I-I...! I can't...! Ichinari, I can't...!"

@Iori
"Please, please, I'm begging you! I can't take it anymore! I'm sorry, but I can't! Ah, ah, nyaah!"

@Iori
"I-It's too intense... Y-You're gonna break me! I'm going crazy!"

@Iori
"Haa! Haa! S-Seriously...! Ah, again...! Nnngggaaahhh!"

@Ichinari
"Sorry! You're just too cute right now!"

@Iori
"Ah, nooo! I-I'm so happy! So happy you said that!"

@Iori
"But that's making the pleasure even more intense! I really can't take much mooore!"

@Iori
"I can't... I can't take it! I can't take it, but I want your cum, Ichinariii! Ah, nyaaaah!"

@Iori
"P-Please! Please, Ichinari! It's a safe day, so...CUM INSIDE MEEE!"

@Iori
"I'll keep going until you cum! So I want you to fill me up with your baby batter! Pleeease!"

@Ichinari
"Iori! I wanna cum in you too!"

@Ichinari
"So can you keep it up just a bit longer?"

@Iori
"Yes, yes, yes♪ G-Go for it♪ I'll take it, I can take it♪♪"

@Iori
"Cum inside me, fill me up♪ Plug my hole with your hot cum♪♪"

@Iori
"Mm, ah, aah♪ I'll bear the pleasure until you deliver your load♪"

@Iori
"So fuck me♪ Fuck me harder... Cum deep inside meee♪♪"

@Ichinari
"Iori!"

@Iori
"Ah, aah! Nyah! Ah, ooh! Gah, mm, aaah!"

@Iori
"Hyaah, ah! Ah, aaah! I'm cumming, I'm cumming! Aah, aaah, I'm cumming agaiiin!"

@Iori
"Ah! Haa, haa! Ah, nyaaaaah! Again! Aaaaah!"

Shlup! Shlick! Sllllrp! Shlap!

@Iori
"Aaaaah! Ah, so deep! Ah, nyaaah!"

@Iori
"I'm still—! Ah, I—! Cumming, aaaaah! Ah, aaaah!"

@Iori
"Ah, aaah! I'm cumming, cumming, cumming! AAAAHHH!"

@Ichinari
"I'm gonna cum deep inside you, okay?"

@Iori
"Yeah, yeah♪ Cum in me, all the way inside♪"

@Iori
"Your cock's reaching all the way in♪ All the way to my baby-making chamber♪"

@Iori
"Shove it all the way in♪ Fill my womb with your semen♪"

@Ichinari
"Yes! I'm gonna shoot it right into your womb! The whole load!"

@Iori
"Aaaaah! I'm cumming too, I'm cumming! Ah, aaah!"

@Iori
"I'm gonna squeeze down on your cock and milk it dry!"

@Iori
"Like that, yes, like that! Ah, aaaah! Ah, ah, aaah!"

@Iori
"Ah, aaah! NYAAAAAAAAAAH!"

Spurt! Shplurt! Splash!

@Iori
"Nyaaaaaah! Ah, aaah, aaaah!"

@Iori
"Ah, aaaah! Ah, wow, I can feel it spurting inside me!"

@Ichinari
"Iori! I'm still going!"

Sploosh! Shplurt! Splash!

@Iori
"Nyaaaah, ah♪ Haa, nyaaah♪"

@Iori
"There's so much♪ Ah, wow, it's still going♪ Nyah, aaah♪"

@Iori
"Yes, give it to me♪ I'll take all your jizz, to the last drop♪ Haa, aaah♪"

@Iori
"Haa, ahh♪ Haa, aaaaah♪"

@Iori
"Ichinari♪ You came so much inside me♪"

@Iori
"It's so warm in my belly... I'm so happy♪ Haa♪"

@Ichinari
"You okay, Iori?"

@Iori
"I'm done♪ I feel too good... I'm gonna die from happiness♪"

@Iori
"So could you...pet me? Hug me tight♪"

@Ichinari
"Yeah, of course."

@Iori
"Haa♪ I'm sooo happy, inside and out♪"

@Iori
"And...kiss me, too?"

@Ichinari
"Yeah, of course, Iori. Mm."

We both collapse, spent, onto the bed.

With our sweaty limbs entangled together, we bask in the afterglow.

