#start|Happiness is Coming

@Iori
"Haaa~♪"

@Iori
"What an amazing day♪"

Iori is practically glowing as she smiles up at the night sky.

@Iori
"I know we showered, but do you think the others will know something happened when we get back?"

@Ichinari
"Well, it still happened, whether they know or not."

@Ichinari
"You may have stolen a bit of a march on them, but I don't think it's something to hide."

@Iori
"Ichinari..."

@Iori
"Yeah, you're right. It'd be weirder to try and hide it."

She squeezes my hand in hers.

Then she flashes me a cute, bashful smile.

@Iori
"But if I were in their shoes, I'd probably be jealous."

@Iori
"So make sure to show Nodoka and Akira-chan the same love, okay?"

@Ichinari
"Iori..."

@Ichinari
"Don't worry."

@Ichinari
"I'll love you all equally."

@Iori
"Yep. Good."

Although she admitted she'd be jealous...

...she's still making sure to look out for Nodoka and Akira-chan's feelings.

I'm the selfish one in this relationship.

Which is why I've gotta be extra vigilant. Yep.

Iori's words help me reaffirm what's important to me.

@Ichinari
"I'm so lucky to have such wonderful girlfriends."

@Iori
"Hee hee. What's this for all of a sudden?"

@Ichinari
"Oh, it just came back to me all over again."

@Iori
"...Naughty."

@Iori
"Well, I can't say I'm not happy about it myself..."

@Ichinari
"Uh, no, I didn't mean it in that way at all."

The caring side she just showed, and the side of her that's always thinking about sex...

They're both her, and I love that.

She's so true to herself, and that makes me smile.

@Ichinari
"Well, let's buy a little gift for the others and head home, shall we?"

@Iori
"Ah, I want ice cream."

@Iori
"There's a famous ice cream parlor in King's Square."

@Ichinari
"It'd melt before we got it home though."

@Iori
"Then we can take a cab."

@Ichinari
"I'd never think to get a taxi to somewhere within the basic fare range..."

@Iori
"Hee hee, you know fare is no issue."

@Iori
"Okay, shall we get going? I can't buy it without you, so thanks in advance."

@Ichinari
"I am at your service, my lady."

This girl is always herself—and she's also mine.

Holding onto each other's hands even tighter than before...

...we head out to buy presents for Nodoka and Akira-chan.

At the same time, back at the office...

@Akira
"Hey, Nodoka-chan! What's this package?!"

@Akira
"It's heavy! Suuuper heavy!"

@Akira
"Quick, grab that side! I'm about to drop it! Hurry!"

@Nodoka
"Hey, Akira-chan, stop wobbling around! I can't get a grip on it!"

@Nodoka
"Sheesh, what are those two doing out till this hour!"

The two girls struggle to move Iori's newly-delivered computer.

