#start|Hot Spring

@Nodoka
"Oh, Iori-san."

@Nodoka
"You're getting tons of replies on Dwitter."

Nodoka calls out to Iori as she types away at her computer.

@Iori
"I ignore them. It's just an announcement account; I don't follow anyone."

@Iori
"I only made it because the the editor-in-chief told me to."

@Iori
"I don't use social media at all myself."

@Ichinari
"Typical Iori!"

@Akira
"I don't think the editor-in-chief understands how bad her social anxiety really is."

@Akira
"Still, Ishitaka-sensei sells even without engaging with the fans."

@Ichinari
"And then there are some artists who don't sell whether they engage or not. Ahaha!"

@Akira
"Don't give me that attitude. Shwp!"

She gives me a light karate chop.

@Nodoka
"I wish I'd taken that approach from the beginning."

@Nodoka
"But it'd look bad if I suddenly changed my stance now."

Nodoka looks annoyed as she sends replies to the Dweets.

@Ichinari
"But I thought you liked interacting with fans at events?"

@Ichinari
"You said that direct communication is one of the best things about the amateur scene."

@Nodoka
"Oh, I'm fine with people coming to say hi when I'm at an event."

@Nodoka
"But the people who only care that I'm a female hentai artist, and never even glance at my work, are just a pain in the butt."

@Nodoka
"You can tell which comments are from real fans and which are just fawning."

Looking at Nodoka's replies, the difference in tone is quite impressive. It's a total mix of cold shutdowns and perfect professionalism.

I guess when you have 16,000 followers, there's gonna be some weirdos in there.

Still, it's unusual to see Nodoka annoyed, since she always has a smile on her face for me. I can't help but smirk at the feeling of superiority that gives me.

@Nodoka
"Oh, Iori-san."

@Nodoka
"Isn't it almost time for your spa appointment?"

@Iori
"Hey, Nodoka, check out this funny gif."

@Nodoka
"You're the one who wanted to go, remember?"

@Nodoka
"And you made me get an appointment for you, remember?"

@Iori
"...Sorry. I'm going. Please don't get mad at me."

@Nodoka
"Akira-san, please make sure she actually gets there."

@Nodoka
"It's my regular place, so it'd be awkward for me if she cancels last-minute for no reason."

@Akira
"Yes, boss! I'll drop her off on my way to the company!"

@Iori
"H-Hey, wait a minute! I need time to get emotionally prepared!"

@Akira
"Shut it! We're basically family now, so I won't go easy on ya!"

@Akira
"Get your ass in gear! Nothing ventured, nothing gained! GO GO GO!"

@Iori
"Ah, wait! I'm going, I'm going!"

@Iori
"If you drag me out before I'm fully prepped, my allergy to the outdoors will— Ah, argh!"

@Nodoka
"Phew. It's always the same with Iori-san."

@Nodoka
"Although I think she might have changed a little bit since she started dating you, Senpai~"

@Nodoka
"Still, she is who she is. Hee hee."

The two of us are suddenly all alone.

Nodoka's merry giggle reverberates through the quiet room.

@Ichinari
"Did Iori really say she wanted to go to the salon?"

@Nodoka
"She did. It's rare—maybe even the first time."

@Nodoka
"I've always just invited her along with me before."

@Nodoka
"But this time she suddenly came to me saying she wanted to go herself."

@Ichinari
"Why would someone with her anxiety do that?"

@Nodoka
"She said she wants to pretty herself up for her boyfriend."

@Nodoka
"My boyfriend is a real catch if he can make her go that far out of her comfort zone~♪"

@Nodoka
"To make Iori-san say something like that, the power of love really is incredible~♪"

@Ichinari
"Well I don't really know how to respond to that..."

@Ichinari
"But, uh...I guess I'm flattered."

Nodoka really does love Iori. By all rights, their relationship should be kind of dicey.

And just now Akira-chan also said they're like family. I'm sooo grateful that they're still getting on as well as ever.

I'm so thankful that my girlfriends are such good girls. Seriously.

@Nodoka
"Although..."

@Nodoka
"I did also have my own personal reasons for getting her an appointment for today~"

Her voice comes from behind me while I'm still facing my computer.

Then her slim arms wrap around me.

@Ichinari
"And what would those reasons be?"

@Nodoka
"I made sure it coincided with Akira-chan's editorial meeting. Hee hee♪"

She pokes her tongue out.

Her usual mischievous smile curls up the corners of her mouth.

@Nodoka
"I mean, I wanted some alone time with you, Senpai."

@Nodoka
"Am I a bad girl?"

She whispers into my ear, sounding a little worried.

@Ichinari
"No..."

@Ichinari
"You're a super cute good girl, Nodoka. There, there."

I spin my chair around so I'm facing her.

Then I pull her into my arms and pet her head.

@Nodoka
"Mm~ Senpai~♪ Purr, purr, purr~♪"

@Nodoka
"I love it when you take the initiative, Senpai~♪ Haa~♪"

She nuzzles her cheeks against me childishly. She feels sooo soft and smells sooo good.

I've seen all the bodycare products she has stacked up in her room. She really takes care of herself down to the smallest detail.

After enjoying her snuggling for a while, I pull back.

@Ichinari
"Well then, why don't we take a break?"

@Nodoka
"Yes, let's take a little break♪"

@Nodoka
"Okay, Senpai."

@Nodoka
"Open wide♪ Aahn~♪"

@Ichinari
"Mm, this chocolate is sooo good."

@Nodoka
"It's my favorite kind, so I'm really glad you like it♪"

We're on Nodoka's bed.

We're nestled up close together.

I'm making sure to treat everyone equally, but...

@Nodoka
"Hm? What's the matter?"

This is seriously the height of extravagance.

I can't believe I'm surrounded by such gorgeous girls.

Equality and all that aside, this really is the best thing ever.

@Nodoka
"Tee hee. Will you feed me now, Senpai?"

@Ichinari
"Of course."

I pick up a chocolate and bring it to Nodoka's lips.

@Nodoka
"No, not like that."

@Nodoka
"I want you to bring it to my mouth with yours, like lovers do, okay?"

@Nodoka
"Mm♪"

She seems a little bashful.

But she goes ahead and closes her eyes like she's waiting for a kiss.

@Ichinari
"Okay, here goes."

I put the chocolate between my lips.

Then I slowly lean in to her and pass the chocolate to her mouth.

@Nodoka
"Mm... Senpai♪"

@Nodoka
"Shall we...break this chocolate and share it?♪"

She murmurs.

Nodoka's tongue pushes the slightly melted chocolate back to me.

I curl my own tongue around it and thrust it back into Nodoka's mouth.

@Ichinari
"Nodoka... Mm..."

@Nodoka
"Senpai, mm♪ Mwah, ngh, mm, mllp♪"

@Nodoka
"Aha♪ Your kisses...are so sweet, Senpai♪ Mm, mllp♪"

@Nodoka
"Hee hee. Our lips are all sticky now♪"

@Nodoka
"Let me clean you up..."

@Nodoka
"Mllp, mwah, ngh, mllp♪"

@Nodoka
"Mwah, mmph♪ Mllp, hahn, mwah♪"

@Nodoka
"Haa♪ Now you're all nice and clean. Hee hee♪"

She wraps her arms around my neck.

As she smiles, I catch a whiff of the sweet scent of chocolate.

@Ichinari
"Nodoka, you're making a really lewd expression."

@Nodoka
"I am. Time when I have you to myself, and when we can get down and dirty, is precious."

@Nodoka
"So of course I'm not going to hold back, am I?♪"

@Nodoka
"Because I love you, Senpai♪"

She presses herself against me. I can feel her full breasts pushing up on me.

Crap...

I wanna touch her boobs. And we just shared those erotic kisses. I know we're on a break at work, but... 

My sense of reason is truly being tested right now.

@Nodoka
"...Do you not want to touch me?"

She's peering at me a little sulkily.

@Ichinari
"Nodoka?"

@Nodoka
"I brought us to my room, kissed you, and now I'm pressing myself up against you..."

@Nodoka
"I'm giving you all the obvious signs, but..."

@Nodoka
"Are you not in the mood, Senpai?"

@Ichinari
"Nodoka..."

@Ichinari
"No, it's not that..."

@Nodoka
"If you leave me hanging now, I'll be really sad."

@Nodoka
"I always want to do it with you..."

@Nodoka
"You went on a date with Iori-san recently, didn't you?"

@Ichinari
"Th-That's...!"

@Ichinari
"..."

@Ichinari
"Yeah, I did."

I swallow the excuses I'd been about to make.

Instead, I look Nodoka in the eye and nod.

@Nodoka
"Hee hee. It's fine, I'm not mad or anything."

@Nodoka
"Iori-san is your girlfriend, and I love her, too."

@Nodoka
"But that doesn't mean I don't get jealous and lonely sometimes."

She sticks her tongue out at me.

She forces a smile, clearly trying to lighten the mood.

@Ichinari
"Nodoka..."

Iori had said she gets jealous, too.

If I'm really going to treat them equally, then I need to be proactive!

@Ichinari
"I never learn, do I."

@Nodoka
"Hm? Senpai?"

@Ichinari
"Nothing, just talking to myself."

Nodoka gives me a confused look as I caress her cheek.

@Ichinari
"Will you go on a date with me, Nodoka?"

@Ichinari
"It's just the two of us right now, and we can do our work later tonight."

@Ichinari
"Sorry to drag you away from work, but will you join me?"

@Nodoka
"Senpai..."

@Nodoka
"Yes, of course♪ I want to go on a date with you, too♪"

@Nodoka
"Ugh, I just love this sincere side of you~♪"

@Nodoka
"Mm, mwah, mwah, mwah♪ Nnngghh~♪"

@Ichinari
"Hey, Nodoka! I can't breathe! Seriously!"

Nodoka's boobs squash me as she showers me with kisses.

Feeling like I'm about to suffocate, I tap out on her back.

@Ichinari
"Having said that, I'm actually not so clued-up on date spots..."

@Ichinari
"Is there anywhere you wanna go?"

@Nodoka
"Hmm~"

@Nodoka
"Oh, there is one place I've been wanting to go. Is that okay?"

@Nodoka
"It's somewhere we can take it easy together♪"

@Ichinari
"Aaaaaaahhh~!"

@Ichinari
"This is amaaazing~"

I'm submerged up to my shoulders in an outdoor bath with a view of Yokohama.

I scoop up handfuls of water and splash them on my face.

@Ichinari
"I had no idea there was one of these huge bath houses so close by."

It's only a ten minute walk from our workplace.

The "Mirai no Yu" outdoor hot springs are situated on the coast in Minatomirai.

And this is a private bath we've rented out.

@Ichinari
"I never knew how good baths feel in the middle of the day."

I narrow my eyes against the bright sunlight streaming in through the huge windows.

@Nodoka
"I'm coming in too, Senpai."

