#start|Hot Spring

@Nodoka
"Fwah~♪"

@Nodoka
"I got such a thorough seeing-to from Senpai I thought I might die~♪"

After one more dip in the bath, we're on our way home.

Nodoka stretches, looking so refreshed she's practically glowing.

@Nodoka
"Honestly, Senpai, to say you're usually so calm and gentle..."

@Nodoka
"You sure are rough in the bedroom~♪ Argh, I love you so much~♪"

@Ichinari
"Well you turn ridiculously cute, when usually you're all collected and self-assured."

@Ichinari
"Super sexy and cute. "

@Nodoka
"Tee hee! Senpai called me sexy and cute~♪"

@Nodoka
"I'll keep improving so I can get more and more of Senpai's loving. Tee hee~♪"

She hooks her arm through mine and presses up against me, not caring that we're out in public.

I respond by nuzzling my cheek against hers affectionately.

@Ichinari
"Sorry for making you worry about stuff."

@Ichinari
"It might take some time, but I'll get better as a boyfriend."

@Ichinari
"I'll make sure to take you on dates and tell you I love you."

@Nodoka
"Senpai..."

@Nodoka
"Yes. I'd really like that."

I squeeze her hand in mine.

She smiles happily and squeezes it in return.

@Ichinari
"Iori should be coming home soon..."

@Ichinari
"So shall we head back too, and make up for the work we missed?"

@Nodoka
"Yes. Let's do our best together at work, too♪"

We slowly walk home, side-by-side...

...through city streets draped in the light of the sunset.

Meanwhile, back at the office...

@Akira
"Akira Higashibojo has returned in one piece from the editorial meeting!"

@Akira
"Man, was that rough! It went on sooo long! And the editor-in-chief totally railed on me!"

@Akira
"Come console me, Ichi! Quick! Waaaahn!"

@Akira
"...Huh? Iori-chan?"

@Akira
"Wh-What're you doing splayed out on the sofa like a dried-up jellyfish?"

@Akira
"Didn't you just come back from the spa? Shouldn't you be all refreshed and energized?"

@Iori
"Yeah... The spa treatments felt nice and all, but..."

@Iori
"Spending two hours with complete strangers really wore me out mentally."

@Iori
"I'm down for the day, so...just leave me alone."

@Akira
"It must be tough being you, Iori-chan."

@Akira
"Hang on, where're Ichi and Nodoka-chan?"

@Iori
"They said they were going out for a bit."

@Akira
"Oh a date?! It's a date, isn't it?! And while I was having my ass handed to me in a meeting!"

@Akira
"That fucker Ichi, leaving us behind! I'm gonna make him massage my shoulders when he gets back!"

@Akira
"It's not right for a working adult to be skipping off work to go out on dates, is it, Iori-chan?"

@Iori
"..."

@Akira
"Hm? Hmmm?"

@Akira
"Iori-chan? Why are you looking away?"

@Iori
"...I'm not looking away."

@Akira
"Huh? What? What's going on? Huh? Huh?"

@Iori
"Oh, there's some baumkuchen in the fridge that's supposed to be really yummy."

@Akira
"Really?! You rock, Iori-chaaan♪"

@Akira
"Thank youuu♪"

Akira-chan can be surprisingly easy to please.

