#start|Both Sides

@Akira
"Haa... I'm baaack~"

@Ichinari
"Oh, Akira-chan, welcome home."

@Ichinari
"You're pretty late back again today, too."

@Akira
"Yeah~ Super late~ I'm sooo tired~"

Akira-chan flings herself down onto the sofa exhaustedly.

The clock is showing 2 a.m. Both Iori and Nodoka are the early-to-bed, early-to-rise types, so I'm the only one in the living room.

I'd been practicing my drawing, but now I put my pencil down. I make the prostrate Akira-chan her favorite hot milk with honey.

@Ichinari

"Here you go; hot milk with honey."

@Ichinari
"Careful, it's hot."

@Akira
"Oooh! Thanks! Thanks so much, Ichi!"

@Akira
"*sip*"

@Akira
"Haa~♪ The sweetness is spreading though me, body and soul~"

@Akira
"You're really shaping up to be a great downtrodden house-husband, Ichi~I'm proud of you."

@Ichinari
"What you're saying is the opposite of a cool guy. The total opposite."

I'm really doing my best right now. Seems like I've missed the mark though.

Well, for now I'll just take her ribbing like a man.

@Ichinari
"Anyway, you're coming home at this time every day lately. It can't be good for you."

@Ichinari
"Don't you think you're pushing yourself a bit too hard?"

@Akira
"I am~ I'm pushing myself way too hard~"

@Akira
"Being a corporate slave is a heavy burden to bear, ya know? Like, about twelve tons, I'd say."

@Ichinari
"That's, like, a whole freight truck. It'd crush the asphalt."

@Ichinari
"Anyway, all joking aside..."

@Ichinari
"What's suddenly got you so busy?"

@Ichinari
"Don't tell me you're putting in all this extra time to push Ichineri-sensei's stuff...?"

@Akira
"No, no. I don't have anything to sell anyway."

@Ichinari
"Well, yeah, that's true."

It's not like I've released a new book recently.

I'm not sure whether I should feel glad or discouraged...

@Akira
"One staff member suddenly called out sick."

@Akira
"Companies are organizations built on everyone pulling their weight, so it's tough when you've gotta fill in for people."

@Ichinari
"Sick leave, huh? Well, I guess there's not much you can do about that."

@Ichinari
"But even so, you shouldn't sacrifice yourself for the sake of a company."

As I look into Akira-chan's exhausted face, my true feelings spill from my lips.

@Akira
"Ichi..."

@Akira
"Hee hee♪ Tee hee hee~♪"

@Ichinari
"Onee-chan? What's with that laugh...?"

@Akira
"Oh, you know~ It's just so nice to know that you're seriously concerned about me, Ichi♪"

@Akira
"I might be a waste of space as an employee, but as your girlfriend, it makes me really happy. Tee hee♪"

Hunched over and cradling her mug in both hands, she giggles like she can't help herself.

Her unexpected reaction dissolves any criticisms I might have uttered.

@Ichinari
"Well, you're doing your best, so if you insist on working yourself to the bone..."

@Ichinari
"...as your lover, I'll support you in it."

@Ichinari
"Now, shall I give you a shoulder massage, my lady?"

@Akira
"Oooh, hell yes♪"

@Akira
"Okay, can you make sure to really go for it?"

She sits up on the sofa and I move behind her. I carefully start to massage her slender shoulders.

@Akira
"Ahhh~♪ Aaaaah~♪"

@Akira
"That's good♪ That's really good~♪ Oooh~ Aaaah~♪♪"

@Akira
"When you're working at a computer all day, your shoulders get super stiff~♪ Aaahhh~♪"

@Ichinari
"Yeah, your shoulders are super tense."

Gauging her reactions and taking care not to hurt her, I dig deep into her shoulders, loosening her taut muscles.

@Akira
"Man, I'm sorry for making you rub my shoulders, Ichineri-sensei~"

@Akira
"Really I should be the one massaging you~"

@Ichinari
"Silly Onee-chan."

@Ichinari
"We're lovers before we're artist and editor, aren't we?"

@Ichinari
"And I'll do this anytime, if it makes my girlfriend happy."

@Akira
"Ichi..."

@Akira
"Hee hee. You're really cool these days, Ichi."

@Akira
"It's like, you're a proper boyfriend, or like you're treating me like a proper girlfriend?"

@Akira
"They might be just offhand comments to you, but they make me sooo happy. Hee hee."

@Ichinari
"Akira-chan..."

@Ichinari
"Yeah. If I've gotten even a little closer to being a good boyfriend, then I'm glad."

@Akira
"Yep, just a teeny tiny bit. Ahaha."

Her laugh is bright and cheery. I continue massaging her, feeling supremely happy, too.

@Akira
"It's because I'm seeing you up close like this..."

@Ichinari
"Hm? What is?"

@Akira
"I told you I'm taking on my share of the absent employee's work, right?"

@Akira
"Well I've taken over looking for new talent and prepping contest winners."

@Akira
"Since there's stuff from other departments too, there's a helluva lot of work."

@Ichinari
"Huh, so you guys do that kinda thing, too."

@Akira
"For the really big competition, we recruit other published authors to enter."

@Akira
"And as a publishing company, we of course get new submissions on a daily basis."

@Akira
"I wonder if an editor like me should really be in a position to judge other people, but..."

@Akira
"You know, because I see people like you around me working their hardest every day... "

@Akira
"It makes me realize I've gotta do my very best, too."

@Ichinari
"Akira-chan..."

Despite her exhaustion from working day and night, she's showing me a smile and talking in her usual cheery tone.

This is exactly why I fell for her.

Affection wells up in me for this forthright, hardworking, proud woman, and I hug her slender frame from behind.

@Ichinari
"When's your next day off, Akira-chan?"

@Akira
"Huh? Day off?"

@Ichinari
"Yeah. Would you go on a date with me?"

@Ichinari
"As your boyfriend, I want to show you a fun break from work, but..."

@Ichinari
"Mostly, I just want to go on a date with you."

@Akira
"Ichi..."

@Akira
"Yeah, let's do it! Let's go on a date! I wanna go on a date with you, too!"

@Akira
"That's enough to keep me alive till my next day off! HELL YEAH! OOHRAH!"

@Akira
"Now, as thanks, I'll give you a nice cuddle♪ C'mere."

@Ichinari
"Onee-chaaan!"

@Akira
"There there there♪ You're sooo cute, Ichi. Good boy, good boy♪"

@Ichinari
"Aaah, it's been too long! You're sooo great, Onee-chaaan!"

@Nodoka/Nodoka＆Iori
"It's the middle of the night! Keep it down!"
"It's the middle of the night! Keep it down!"

@Akira/Akira＆Ichinari
"Sorry..."
"Sorry..."

The two previously sleeping girls shout at us.

It's only fair, really.

@Akira
"Ichi, Ichi!"

@Akira
"Look! Look at that! And that looks sooo tasty, too!"

@Akira
"I'm gonna buy one of those too, so you just wait here♪"

@Akira
"Mm, sooo goood♪ Local food is the best~♪"

@Akira
"And there's nothing better than good food to take your mind off work! I feel totally invigorated♪"

We're wandering around Chinatown, both hands weighed down with bags of food.

Akira-chan is stuffing her face.

@Ichinari
"Akira-chan, are you sure we haven't bought too much...?"

@Akira
"Don't worry, it's all good♪"

@Akira
"These are just, like, snacks!"

@Akira
"And we're on a date, so you're gonna eat with me too, right?♪"

@Ichinari
"Well, sure, but..."

@Ichinari
"My stomach has its limits."

@Akira
"Are you a man or not?♪"

@Akira
"This is Onee-chan's treat, so just go for it. Ahaha♪"

In the lively, bustling streets...

...Akira-chan skips along with the merriest smile I've ever seen on her face.

She's so cute when she's in high spirits like this.

The powerful rays of her joy warm my heart like the sun.

@Akira
"Oh, but..."

@Akira
"It's not cute for a girl to overeat, is it?"

@Akira
"It's like, kinda gross, or childish..."

@Ichinari
"Not at all."

@Ichinari
"In fact, I think it's super cute, and very you."

@Ichinari
"I've always loved seeing you happily digging into your food."

@Akira
"A-Always?"

@Akira
"You mean... You've always thought of me as this greedy girl character?"

@Ichinari
"It's hardly a surprise at this point, is it?"

@Ichinari
"You've always been this way."

@Ichinari
"And we've often eaten together because you've always looked after me."

@Akira
"S-Sorry...for being such a vulgar woman..."

@Akira
"I mean, I've always been into sports, you know?"

@Akira
"And I've like, always really loved my food..."

@Akira
"And since I've never been on a date before, this was the only idea I could come up with."

@Akira
"I guess I'm not a girly girl like Iori-chan or Nodoka-chan."

She averts her gaze awkwardly. I can't help but chuckle at the sudden contrast with her previous demeanor.

@Ichinari
"I told you, it's not like that at all."

@Akira
"Huh? What isn't?"

@Ichinari
"I have fun when I'm with you, and I feel more energized."

@Ichinari
"Sure, you can sometimes be a little much, but..."

@Ichinari
"...your boundless energy and optimism always lifts me up."

@Ichinari
"And that's the Akira-chan I fell in love with."

@Akira
"Ichi..."

@Ichinari
"And so, if you're ever feeling down..."

@Ichinari
"As your boyfriend, I want to be able to cheer you back up."

@Ichinari
"That's why I asked you out on a date."

@Ichinari
"I'm so happy I get to see your happy, smiling face."

@Ichinari
"So don't be self-conscious. I just want you to be you."

@Akira
"Ichi..."

@Ichinari
"Well, I also just wanted to go on a date with you anyway."

I peer down into Akira-chan's eyes, slightly below my level.

Then I stroke her head, like she always does for me.

@Akira
"I really do love you, Ichi. Tee hee♪"

@Akira
"I was already happy enough you asked me on a date."

@Akira
"But your words just now made me even happier. My heart skipped a beat."

@Akira
"Oh, look at me, getting all teary-eyed. Ahaha."

@Ichinari
"Really? If I was able to cheer you up, then that's good enough for me."

@Akira
"Yeah. I'm actually feeling better than ever right now. Hee hee."

Her large eyes are narrowed. She smiles at me, blinking back her tears.

@Akira
"Ever since I heard you'd been on dates with Iori-chan and Nodoka-chan..."

@Akira
"I'd been wondering if you were gonna ask me on a date too."

@Akira
"So just having you ask me was enough to give me butterflies. Hee hee."

@Ichinari
"You're overexaggerating."

@Ichinari
"But, um..."

@Ichinari
"I'm sorry I left you until last."

@Akira
"Nah. It's okay, I forgive you."

@Akira
"I am the onee-chan, after all. Ahaha."

@Akira
"You get extra points for worrying about it though. Good boy."

This time she's the one petting my head.

@Akira
"You're sooo serious, Ichi."

@Akira
"I like that about you. I love it."

@Akira
"I know it's got nothing to do with ranking."

@Akira
"And I know that you care about me."

@Akira
"Could you bend down slightly?"

@Ichinari
"Bend down? Like this?"

@Akira
"Yeah, that's it, perfect♪"

@Akira
"Oh, Ichi, you've got something stuck to your eyelashes."

@Akira
"Close your eyes and I'll get it for you."

@Ichinari

"Oh, really? Thanks, Onee-cha—"

@Akira
"Mwah."

@Ichinari
"...!"

@Ichinari
"A-Akira-chan?!"

@Akira
"I just kissed you in front of aaall these people. Tee hee♪"

@Akira
"It's so cute that you fell for the oldest trick in the book."

She pokes her tongue out at me, grinning like a little kid that's just pulled off a prank.

@Akira
"That was a make-up kiss, 'kay?"

@Akira
"So now we're totally even. All done and dusted."

@Akira
"Today's our fun date day, so let's only think about fun things. 'Kay?"

@Ichinari
"Akira-chan..."

Her smile lights up her whole face, and her joy is infectious.

@Ichinari
"I'm no match for you, Akira-chan."

@Ichinari
"You're always the one pulling me up with you."

@Akira
"What are you talking about? This is just how things are with us."

@Ichinari
"Yeah, you're right. It's how things always are with us."

@Ichinari
"Which is why, this time, I want to be the one taking care of you."

@Ichinari
"And from here on, I want to be the one protecting you."

@Ichinari
"You may be my onee-chan, but..."

@Ichinari
"I'm also your boyfriend."

@Ichinari
"And as your boyfriend, I want to grow up a little bit."

It's something important to me, that I want to work toward on my own.

It's a little embarrassing for me, but I manage to put my feelings into words and deliver them clearly to Akira-chan.

@Akira
"Ichi..."

@Akira
"..."

@Ichinari
"Hm? Akira-chan?"

@Ichinari
"What's up?"

@Akira
"Y-Yeah..."

@Akira
"That really...hit me hard just now..."

@Akira
"My defenses were down...and you went straight for the heart... Haa..."

She presses her hand to her ample chest. Her face flushed, she lets out a long breath of air.

It's...startling erotic. I find myself averting my gaze, my heart pounding.

@Akira
"Ichi..."

She places one of her small hands in mine. Hesitantly, she gently squeezes down on it.

@Akira
"I'm sorry."

@Akira
"Since we're on a date, I was thinking we could enjoy ourselves doing tons of fun stuff, but..."

@Akira
"You've made me sooo happy..."

@Akira
"...Onee-chan can't contain herself any longer."

@Ichinari
"Akira-chan...?"

@Akira
"Will you take care of me...in ways only a boyfriend can?"

