#start|Chasing a Dream

@Akira
"Awwright! Congrats everyone on another installment sent to print!"

@Nodoka
"Yes, good work everyone♪"

@Iori
"Mm. Thanks to everyone, we were ahead of schedule this time, too."

@Iori
"And Ichinari seems to have gotten used to his assistant role now."

@Iori
"Even though we're publishing more work, it actually feels like things are easier since he joined us."

@Nodoka
"Yes, and not just in terms of manpower, but in emotional terms, too♪"

@Ichinari
"I'm just happy I could prove useful to you manga maestros. I'm at your service."

@Akira
"I always knew you had it in you, Ichi~♪"

@Akira
"I'm pretty proud of myself for bringing you along~ Nice one, me♪"

@Ichinari
"Ow! I keep telling you, it actually hurts when you do that, Onee-chan!"

It's been around a month since I started as Iori's assistant. I'm completely at home in the job now, and even I can tell I've improved.

We've completed everything according to schedule this time, too. And, most importantly, I also think I've grown emotionally.

And it's all thanks to these women.

@Akira
"Now, I know it's a little early, but..."

@Akira
"Shall we all go out to celebrate?"

@Iori
"Honestly, Akira-chan, you just want a reason to go out drinking on the company's dime, don't you?"

@Akira
"It's because you always hand everything in bang on time, Ishitaka-sensei♪"

@Akira
"If I tell the editor-in-chief it's a party for you, she'll let me off with just a tongue-clicking♪"

@Ichinari
"Oh, so you get tutted at?"

@Nodoka
"That editor-in-chief sounds like a real hardass~"

@Iori
"Social hierarchies sure are complicated..."

@Akira
"But when it comes to Ichi, I don't think I could get away with even taking you for a coffee."

@Akira
"Compared to the earful I'd get about that, this is absolutely nothing. Ahaha~"

@Ichinari
"Owwies. Kick me in the balls, why don't you."

Well, I guess the truth hurts.

@Nodoka
"But there's still a while until The Black Cat opens..."

@Nodoka
"Oh, the wine I ordered should be arriving today, so why don't we drink at home for once?"

@Nodoka
"We can go pick up other drinks and snacks from the supermarket~♪"

@Akira
"Oh, great idea, yeah! House party! No, pajama party!"

@Iori
"Yes, that sounds like fun."

@Iori
"If I place an order online now, we can get stuff delivered before evening."

@Ichinari
"You really don't go outside unless you have to, do you, Iori?"

Even though there are supermarkets and convenience stores a mere stone's throw away.

The manga maestros know exactly where they want to spend their skill points, huh.

@Iori
"Okay, let's get that order in then."

@Iori
"What do you guys want?"

@Akira
"Beer for me! Not the cheap stuff!"

@Nodoka
"The wine is red, so I'd like some kind of nice, flavorful meat dish♪"

@Nodoka
"Like tripe, or roast beef, or pizza~"

@Nodoka
"Oh, since we're staying in, something garlicky might be good too♪"

@Ichinari
"If there's some kind of light, fruity cocktail for me..."

@Iori
"Hmm~ I dunno much about about those, so I'll just add the most expensive ones to the cart."

@Ichinari
"Your shopping is always a sight to behold, Iori-san."

She keeps adding stuff into the shopping cart.

@Iori
"Oh, we don't have many wine glasses or plates."

@Iori
"Could I ask you to get those, Nodoka?"

@Iori
"Since we're getting all new ones, could we make it a cute matching set?"

@Nodoka
"Sure thing~ Leave it to me~♪"

@Nodoka
"Oh, this glass is cute~♪ It's delicate, and the rim looks good~♪"

@Nodoka
"Okay, four of these."

@Akira
"Whoaaa, Ichi! Check out that glass!"

@Akira
"She just picked a design that costs over 10,000 yen for ONE!"

@Ichinari
"It's better if we don't look, Akira-chan. Ignorance is bliss."

Their sense of money is god-tier; it's too much to take in for a mere mortal like me.

@Iori
"It's fine, the price is no issue."

@Iori
"I like to spend money if it's on something fun."

@Iori
"It'll never be a waste if it helps us have fun together."

@Ichinari
"Iori..."

She really seems to be enjoying herself as she smiles cheerfully.

Well, it's her money, and this is how she enjoys using it.

@Ichinari
"You're right. Sorry for being crass."

I bow my head meekly to her.

@Iori
"Oh, no, it didn't bother me at all."

@Iori
"You know, I never had friends before..."

@Iori
"So I've never had a drinking party at home. I'm excited♪"

@Ichinari
"Yeah! Let's make it an awesome night!"

I vow to myself that I'll do my best to make this a night to remember.

For the sake of my beloved, slightly pitiable girlfriend...

@Iori
"Um... Okay, so..."

@Iori
"..."

@Iori
"Great work, everyone."

@Iori/Nodoka＆Akira＆Iori
"Cheeeers♪""Cheeeers♪""Ch-Cheers."

@Akira
"*glug glug glug* Pwaaaaah!"

@Akira
"Man, that really was a very Iori-ish toast~♪"

@Nodoka
"It's super cute how hesitant you are, Iori, but..."

@Nodoka
"I do worry a bit when I imagine you getting lost somewhere by yourself."

@Iori
"I never go out alone anyway. I have you guys, so I'm fine."

@Iori
"I'm living together with my boyfriend and his two other girlfriends."

@Ichinari
"I can't tell if you mean that in a positive or a negative way."

The table is filled with the food and drink we ordered in. We're all sipping on our drinks as we relax in our sleepwear.

Ever since I moved to the city, my life had been about nothing but manga, so this is really fun.

At any rate, right now it's really brought home to me just what a luxurious position I'm in.

@Nodoka
"But you've changed a lot too, Senpai."

@Nodoka
"It's like, he's really improved at, or even mastered this job."

@Nodoka
"Or like, he's become more focused and confident?"

@Akira
"Yeah, yeah, I totally get what you're saying~♪"

@Akira
"He's become way more proactive than before, and learned to say what he's thinking."

@Akira
"I really feel like I can depend on him now, as his onee-chan and his girlfriend♪"

@Ichinari
"I don't really feel it myself though."

@Ichinari
"But if you all say so, then..."

@Ichinari
"I guess I'm glad I've grown, even if it's just a little."

I clink my glass against the ones Nodoka and Akira-chan are holding out to me. An elegant tinkle rings out through the room.

@Iori
"I also think Ichinari's improved, but... Um..."

@Iori
"I-I wonder if...if I've improved, too...?"

@Ichinari
"Hm? I mean, I think you've always been super talented, ever since we first met."

@Iori
"S-Since we first met?!"

@Iori
"I mean, it's true that I've become more comfortable with masturbating over the years, but...!"

@Iori
"That was the first time I ever used a table corner...!"

@Ichinari
"Huh?"

@Iori
"Huh?"

@Nodoka
"Um, just want to check, but..."

@Nodoka
"We were talking about work, right?"

@Akira
"Yeah. Like, work and personality."

@Iori
"...Never mind, forget everything I just said."

Iori hangs her head, her face burning.

@Ichinari
"Well, you know, thinking about it now, I can't believed I moved to the big city with only the skills I had back then."

@Ichinari
"Studying under you guys has really brought that home to me."

@Ichinari
"It's not like I could draw as well as Iori or Nodoka."

@Akira
"You know what the editor-in-chief said about you when I first joined the company?"

@Akira
"'He's got ambition to spare, so we've got high hopes for him.'"

@Ichinari
"So that's how they introduced me, huh?"

The reality three years on is a bit of a bummer though.

@Nodoka
"But I really liked the manga you drew in high school, Senpai."

@Nodoka
"Even looking at it now, it's still got this, like, passion and vitality of youth to it♪"

@Iori
"And you were brimming with confidence when we promised to become manga artists together, too."

@Iori
"I was able to make it this far because of the passion you infected me with then. Hee hee."

@Ichinari
"Stop! Please, spare me the analysis of my depressing life!"

These two know way too much about me for comfort.

Although I guess it's kinda my fault for doing those things in the first place...

@Ichinari
"Still, I do think I had a hollow confidence back then."

@Ichinari
"Although I lost it somewhere along the way, at some point between going pro and totally stalling..."

@Ichinari
"But I've been given a second chance here."

@Ichinari
"And having you all acknowledge that I've changed..."

@Ichinari
"It makes me think that maybe now I'm gaining a little confidence with an actual foundation to it."

@Ichinari
"So thanks again, guys. I'm really grateful."

I clearly tell them my honest feelings.

That's another one of the ways in which I've grown.

@Akira
"Ahaha. You've become so open and honest, Ichi."

@Akira
"Is that thanks to the gods' power, like they did for us?"

@Nodoka
"Oh, speaking of that..."

@Nodoka
"It feels like that was all back in the ancient past now."

@Iori
"Being able to show our true feelings is just the norm now. Hee hee."

@Ichinari
"Even though it's only been just over a month."

I'd seen the article on Dwitter about black cats being messengers to the gods; then Blackie proved to me that it was all true.

She'd said that all she'd done was connect our existing Fates, but...

If it weren't for her, things may not have turned out this way.

@Akira
"Well, how about we ask the gods for another favor?!"

@Akira
"Like, please make my company not totally suck!"

@Nodoka
"Oh, interesting idea!"

@Nodoka
"I wish for that holy grail dōjin I never managed to get my hands on back in high school~♪"

@Iori
"Uh, then I guess I want...to be able to communicate with people better, or something?"

@Ichinari
"Um, guys?"

@Ichinari
"I don't think you can call upon the gods that easily, you know?"

@Iori
"But it's not like we actually meant to call on them before."

@Nodoka
"We told our wishes to Blackie, but it's the gods who made them come true."

@Ichinari
"Well, when you put it like that, I guess you're right."

I still don't think it works like that, though.

@Akira
"Anyway, it doesn't hurt to try, does it? It's all good, it's all good♪"

@Akira
"And like, just think how many people's lives would be improved if my company cleaned up its act!"

@Iori
"And if my social anxiety was cured, you guys wouldn't have to worry about me anymore."

@Nodoka
"And those old dōjin goods would actually be valuable antiques now~♪"

@Ichinari
"Hey, you're all drunk, aren't you?"

@Ichinari
"I can tell from how you're getting so worked up!"

This has nothing to do with Fates at this point—it's just their random wishes.

And the gods aren't like a dragon you can summon with seven balls or something.

@Ichinari
"Besides, Blackie's not even here to tell the gods, is she?"

@Iori
"Now that you mention it, you're right."

@Nodoka
"Oh, isn't she out on the balcony again?"

@Akira
"Wouldn't any stray cat work? So long as it's black."

@Ichinari
"You really haven't thought this through, have you."

@Iori
"Well, I suppose I've already had my number one wish granted."

@Nodoka
"Yes, I don't actually have any bigger wish♪"

@Akira
"So long as I have Ichi, I can tough it out in even the crappiest of companies. Ahaha♪"

The three of them are already wasted.

But, still, they're super cute.

As I sit there, surrounded by their smiling faces, I savor the bliss I'm thankful for every single day.

@Nodoka
"Oh, we finished the wine."

@Nodoka
"What shall we drink next? I'll pour it for you, Senpai♪"

@Akira
"Oh, then how about I pour it into your mouth from my boobs?"

@Akira
"If I push 'em together like this, I can put the drink into my cleavage♪"

@Iori
"S-Such skill! I'm overwhelmed...!"

@Nodoka
"I think I could do that too, you know?"

@Nodoka
"My body is at Senpai's disposal, if he wants it~♪"

@Iori
"Huh? Uh..."

@Iori
"I-I...I could pour it with my crotch...!"

@Ichinari
"Whoa, there. Calm down, guys. "

@Ichinari
"This isn't something we want to try while drunk, okay?"

@Akira
"Booo, Ichi, you're no fun!"

@Akira
"Your girlfriends are all putting themselves out there for you!"

@Nodoka
"Yes, this is something all couples do."

@Nodoka
"At least, I think they do."

@Iori
"D-Do you think I'll need to shave?!"

@Iori
"That might take some time to get ready...!"

@Ichinari
"No, seriously, just calm down, okay?"

@Ichinari
"It's a bad habit, the way you three are so quick to go overboard."

@Akira
"Then let's strip Ichi and have our own fun with him!"

@Akira
"Boys can pour stuff with their crotches too!"

@Nodoka
"Get rid of the hair, add a drink, and I bet it'd look kinda like a soft-shelled turtle soup."

@Nodoka
"That's quite intriguing to me, as both a manga artist and a girlfriend♪"

@Iori
"Th-Then I'll shave Ichi!"

@Iori
"I have a steady hand, so leave it to me!"

@Ichinari
"Ah, no, don't grab at my pants!"

@Ichinari
"Hey, three against one isn't fair! It's not fair!"

@Ichinari
"Seriously, wait! Please, just calm down! Please!"

@Ichinari
"I'm not a virgin anymore, but I still need the right moo-AAAAAAAAHHHHHH!"

I feel a sense of deja vu as the three of them converge on me... And so our boisterous night of drinking continues on.

@Akira
"Zzz... Zzz..."

@Akira
"Silly Ichi... What're you gonna do with me now you've got me drunk~♪ Nyah, nyah♪"

@Iori
"Ichinari's bouncy balls...are so nice and soft~♪"

@Iori
"It's like squishing Nodoka's boobies~♪ Tee hee~♪"

@Nodoka
"Noo, Senpaiii♪ We can't do this in front of the others~♪"

@Nodoka
"Squeeze my boobs harder~♪ Squishy squishy~ Tee hee♪"

The three of them are sprawled out across the living room, totally wasted. It's starting to become a familiar sight.

@Ichinari
"Heeeey, guuuys?"

@Ichinari
"If you're gonna sleep, do it in your own beds, please."

@Iori
"Nyaaah♪ Ichinari, you're so forceful~♪"

@Nodoka
"I love it when you get like this, Senpaiii♪ Harder~♪"

@Akira
"Doing me while I'm passed out drunk...♪ You're gonna wake me up~♪"

@Ichinari
"Okay, okay, I get it, I get it."

@Ichinari
"I'll carry you all!"

I stow the three out-of-it girls away in their own rooms.

@Ichinari
"They're all such lightweights, yet they sure love to drink."

Working, eating delicious food, going on dates, having sex...

It's so incredible being able to have such fun every single day.

@Ichinari
"Happiness, huh?"

"My number one wish has already been granted."

I think back on what they'd said earlier in the night.

@Ichinari
"My own wish is..."

"To be able to continue as a manga artist."

I revisit my wish from back then.

@Ichinari
"I can kinda say it's been granted."

But becoming a professional is only the starting point.

@Ichinari
"I need to figure what I'm really doing..."

"I don't wanna give up on my dream of being a manga artist."

@Ichinari
"No, I'm already plenty blessed enough. What more could I possibly wish for?"

I have Iori, Nodoka, and Akira-chan.

The three women who I love, and who support me.

@Ichinari
"Right. I've gotta treasure and hold onto these Fates I was bound to..."

In order to make it as a manga artist—

@"Black Cat"
"Exactly. You sure are a handful."

@"Black Cat"
"I connected your Fates; now it's up to you to make the most of them, Ichinari."

@Ichinari
"Blackie?"

I look around, certain I just heard Blackie's voice.

But of course, I don't see her familiar figure anywhere.

Still, I'm sure I heard it...

@Ichinari
"Welp, all I can do is my best."

For the sake of everyone who's rooting for me, and for my own sake, too.

Slow and steady, I've gotta keep doing what I can.

@Ichinari
"Alrighty."

I pat myself on the cheeks, shaking away the last traces of tipsiness.

Then I sit down in my chair. Alone in the silent office, I take hold of my pen.

