#start|Dōjin Artist Dream

@Nodoka
"Senpai, I have a favor to ask..."

@Nodoka
"Could I ask you to help out at another event?"

We're having a break during work. Nodoka asks me for a favor as we're setting out the snacks for everyone.

@Ichinari
"Sure, no problem. You pressed for time with your manuscript again?"

@Nodoka
"Oh, no, that's all good this time."

@Nodoka
"I was wondering if you could help out at the booth."

@Nodoka
"Since you worked so hard at it last time..."

@Nodoka
"I was wondering if you could help out again, if you're okay with it."

@Nodoka
"The other staff all said you did a great job too~♪"

@Iori
"It wouldn't affect your work here, so if Ichinari wants to, why not?"

@Iori
"After all, I had you all to myself recently."

@Akira
"Yeah, Ichi, you should go and help her out."

@Akira
"Go with her as her boyfriend, in place of a date♪"

Iori and Akira-chan offer their thoughts on the matter as they bring over the teacups and pour tea for everyone.

@Ichinari
"Of course. It's hardly a big ask."

@Nodoka
"Thank you! I'd really love for you to help out~"

@Nodoka
"And since you'll be involved, you could always contribute some guest illustrations, you know?"

@Nodoka
"You can give up your dōjin virginity to me~♪"

@Ichinari
"You're too cute to be making dirty jokes like that."

I chide Nodoka as she looks up at me through her lashes.

@Ichinari
"Besides, if my work's in it, it'll lower the overall value of your dōjins."

@Ichinari
"You know just how badly my comic sold, right?"

@Akira
"Whoa, what's with the self-flagellation?!"

@Iori
"Yes, it's not a good look, is it."

@Ichinari
"I didn't expect that to go down like a ton of bricks..."

I'm slightly hurt by their reactions.

Although I guess I'm the one who brought it up.

@Nodoka
"Silly Senpai, you totally underrate yourself~"

@Nodoka
"Whether it sells well or not has no relation to the actual quality of the work."

@Nodoka
"Plus, didn't I tell you already?"

@Nodoka
"It's my dream to draw a dōjinshi together with you, Senpai."

@Nodoka
"And you promised to make that come true, remember?"

After the last event, I'd promised Nodoka that we could release a collaboration dōjin together one day.

@Ichinari
"No, of course I wouldn't forget such an important promise."

@Ichinari
"Actually, after getting a look at your dōjin activities up close..."

@Ichinari
"...it got me thinking that maybe I'd like to give it a try, too."

@Ichinari
"But I get that it's not something you do just for the hell of it."

@Ichinari
"So if I'm gonna do it, I really want to do it right."

@Nodoka
"Senpai..."

I look Nodoka in the eye as I answer honestly.

Akira-chan tilts her head as she looks between the two of us.

@Akira
"Then surely it's fine, so long as you're not going into it with a half-assed attitude."

@Akira
"Which means you just have to put your heart into it, right, Ichi?"

@Ichinari
"Huh?"

@Akira
"That's what taking chances is all about, right?"

@Akira
"Like sometimes you get offered a spot in a magazine 'cause someone else didn't submit in time. Things are often kinda sudden."

@Akira
"The only thing that really matters is your own choice of whether to do it or not."

@Ichinari
"Akira-chan..."

@Iori
"I agree."

@Iori
"If you want to draw something, then that's a good enough reason to draw it."

@Iori
"Plus..."

@Iori
"I've already had my wish of drawing manga together with you granted."

@Iori
"So I want to help Nodoka have her dream come true, too."

@Iori
"If you don't have the time, I can reduce your workload here."

@Iori
"So I think you should go for it, and give it your all."

@Ichinari
"Iori..."

After hearing this from Akira-chan and Iori, I turn to face Nodoka beside me.

@Nodoka
"I'm sorry, Senpai."

@Nodoka
"I probably gave you the wrong idea by saying it jokingly, but..."

@Nodoka
"If possible, I'd really, genuinely like to create a dōjin together with you."

@Nodoka
"That's what I've been working toward, ever since we parted."

@Ichinari
"Nodoka..."

@Nodoka
"I know I brought it up quite suddenly this time, so it's okay."

@Nodoka
"But I'll be waiting until you're able to fulfill your promise to me."

She leans her forehead against my shoulder as she whispers to me. Her smile seems a tinge troubled.

@Ichinari
"I'm sorry, Nodoka."

@Nodoka
"No, it's okay, I don't need you to do it right away."

@Nodoka
"We have plenty of time♪"

@Ichinari
"No, that's not what I meant."

@Ichinari
"I think everyone's right."

@Nodoka
"Senpai?"

Her eyes widen as I gently stroke her head.

@Ichinari
"I'm sorry I've put it off for so long, even after all you've done for me."

@Ichinari
"I may not really be good enough for it, but..."

@Ichinari
"Would you allow me to contribute some drawings to your dōjinshi?"

@Nodoka
"Senpai..."

@Nodoka
"A-Are you serious? You're not joking?"

@Ichinari
"I wouldn't joke about this, would I?"

@Nodoka
"Senpai..."

@Nodoka
"I'm happy... I'm so, so happy."

@Nodoka
"I'm so happy...I could cry... Tee hee."

@Ichinari
"Thanks Iori, and Akira-chan."

@Ichinari
"Sorry for being such a burden of a boyfriend."

@Ichinari
"I'll put my heart into it."

I bow my head meekly to them as I thank them.

@Iori
"Hee hee. This was nothing."

@Iori
"I'm your girlfriend, and Nodoka is super important to me, too. Hee hee."

@Akira
"It's a girl's job to give her hopeless boyfriend a push in the right direction."

@Akira
"Although since you gave a very manly response this time, I suppose I should praise you, huh?"

The two of them give me exasperated smiles.

@Nodoka
"Iori-saaan! Akira-chaaan!"

@Nodoka
"I love you both sooo much! Waaaahn!"

@Nodoka
"I'm so glad you two are my...friends? Best friends? Lovers? Whatever..."

@Nodoka
"Anyway, I'm sooo glad I have you two~ Waaahn!"

@Iori
"Nodoka, you're squeezing a bit too tight."

@Iori
"Don't cry over something so trivial. There, there."

@Akira
"C'mere, come blubber into Onee-chan's boobies♪"

@Akira
"They're ready and waiting for you, Nodoka♪"

@Iori
"Oh, now you're setting me off, too... *sniffle*"

@Akira
"Oh, you two are just sooo cute♪ There, there♪"

@Ichinari
"I sure am lucky to have such wonderful girlfriends."

I gaze at their smiling faces, feeling grateful to them all over again for always indulging my selfishness.

@Iori
"Now go on and finish up your work early today."

@Iori
"Then you two can go out for a meeting over dinner."

@Akira
"Yep, yep. Iori-chan and I'll hold down the fort here."

@Akira
"So you two go out and have fun♪"

@Nodoka
"Thank you. We'll take you up on that♪"

@Nodoka
"Okay, Senpai, let's get stuck into it and finish up our work for the day~♪"

@Ichinari
"Gotcha. Let's do this."

@Ichinari
"Well, I'd better cut this break short and get back to work."

@Nodoka
"Oh, then so will I~"

@Akira
"Honestly, Ichi's a real handful of a boyfriend, isn't he."

@Iori
"Hee hee. Well it's a good thing he's got us to make up for his shortcomings."

@Akira
"Yeah, we really complement him♪"

@Akira
"But, of course, you're really important to me too, you know?"

@Akira
"I want to do whatever I can to help you, too."

@Iori
"Y-You...mean a lot to me too, Akira-chan."

@Iori
"I'll...do the same for you, you know?"

@Akira
"Ngyaah! You're sooo freakin' cute, ya lil bastard!"

@Akira
"Come lay down on Onee-chan's lap and let her pet you♪ C'mere, pet pet pet~♪"

@Iori
"Ah, oh no... This feels amazing~♪"

@Iori
"I get why Ichinari's so into this now~♪ Haaa~♪"

@Ichinari
"Those two sure are getting along well."

@Nodoka
"Yes, they really are."

@Ichinari
"Alrighty, let's get down to our own business, shall we?"

@Nodoka
"Yep, let's work hard♪"

With a final glance at the loved-up girls, I pick up my pen to finish the rest of my day's work.

@Nodoka
"Ahem. Now then..."

@Nodoka
"To our dōjinishi! Cheers~♪"

After clinking our glasses together, we take a drink of our sweet cocktails.

@Nodoka
"Hee hee. Somehow the drinks taste even better when it's just you and me."

@Ichinari
"But we've gotta be careful not to overdo it this time."

@Nodoka
"Of course."

@Nodoka
"Since the main point of this is to discuss our collaboration comic♪"

We both have our notebooks spread open on the table.

@Nodoka
"I was thinking about it while I was working today, and..."

@Nodoka
"I figured, if we released it under the Soggy Panda brand, you wouldn't really feel free to draw what you want."

@Nodoka
"And so I was thinking how about if we released it as a joint publication between Nagomi and Ichineri."

@Nodoka
"We could still sell it at the Soggy Panda booth."

@Ichinari
"Yeah, that does sound like a good idea."

@Ichinari
"I was thinking it wouldn't really be fair to the fans for me to take over a Soggy Panda release."

@Nodoka
"Okay, let's do it this way then♪"

We come to an agreement and are scribbling down notes when it occurs to me...

@Ichinari
"So if we're doing this as a separate joint publication..."

@Ichinari
"...that means it won't count as Soggy Panda's new release, right?"

@Ichinari
"Which means that the stuff you've been working on for that will instead go in this joint book?"

@Nodoka
"Nope. As I told you earlier, to participate in the event you're required to have a new dōjinshi release to sell at it."

@Nodoka
"So now that we're releasing this collaboration dōjin, I'll be drawing something new especially for it."

@Ichinari
"Something especially for it..."

@Ichinari
"Huh? You mean you're gonna draw a whole new comic?"

I ask her for confirmation, since I can't quite believe what I'm hearing.

@Nodoka
"Since you said you're going to try your very best..."

@Nodoka
"...that means I've gotta work my very hardest too, right♪"

@Nodoka
"Plus there's something I've always wanted to draw, if we ever got to make a manga together."

@Nodoka
"I'm super hyped right now, so I think it'll be a breeze~♪"

Smiling brightly, she drains her drink and signals the bartender for another.

@Ichinari
"Okay. I know me telling you not to push yourself isn't gonna stop you, but..."

@Ichinari
"If there's anything I can do to help, just let me know."

@Ichinari
"I mean, not that I'll have much free time myself, but I'll do whatever I can."

@Nodoka
"Okay. And I'll do anything I can to help you out, too."

@Nodoka
"And I'm sure Iori-san and Akira-san'll help us out."

@Ichinari
"Yeah, maybe we can drag them into this, too."

While this is mine and Nodoka's project, it'd be nice if we could all work on it together.

I'm sure the others will feel the same way.

Man, I'm seriously the luckiest guy in the world.

@Ichinari
"Anyway, since this is a collab, we should probably be on the same page in terms of theme."

@Ichinari
"So what kind of story are you thinking of drawing?"

@Nodoka
"Since it's just an amateur publication, I was thinking you could just draw whatever you wanted, but..."

@Nodoka
"I suppose it would be more like a real collab if our stories complemented each other, right~♪"

@Nodoka
"Hmm, if I had to summarize my theme in one word..."

@Nodoka
"I guess it'd be 'dreams.'"

@Nodoka
"I thought it'd be perfectly fitting, since that's what this collaboration means to me♪"

@Ichinari
"'Dreams,' huh?"

It's a theme that's open to interpretation\: desires, hopes, wishes, aspirations.

This collaboration in and of itself is a dream come true for Nodoka.

@Ichinari
"Yeah, I think that's a great theme."

Voicing my agreement, I write the word down in big letters.

@Nodoka
"Oh, but there's one requirement\: it's gotta be lewd."

@Ichinari
"So as to stay on brand for your circle?"

@Nodoka
"Nope—because I wanna see porn drawn by Senpai♪"

@Nodoka
"So make sure it's reeeal spicy, okay?"

@Ichinari
"...I'll do my best."

Beside the word "dreams," I add the word "lewd."

Until a moment ago it'd sounded story-based, but suddenly the theme has turned into something far more wild.

Well, I suppose I'd known all along I'd be drawing something sexy; we are hentai artists, after all.

@Ichinari
"But if you ask me what I really want to draw..."

@Ichinari
"...to be honest, nothing springs to mind right away."

These past few years I've been creating things with a commercial publication in mind.

Since I've always been so focused on sales and popularity, I've never given much thought to what I WANT to draw.

Even though, back in manga club with Nodoka, that's all we'd done.

@Ichinari
"Guess I've changed a lot without realizing it, too."

@Nodoka
"We've both had different experiences since high school, and our views have changed."

@Nodoka
"Isn't that the only real difference between me as an amateur and you as a pro?"

@Ichinari
"That'd sound like bragging if I didn't know you had the receipts to back it up."

@Ichinari
"I think it's incredible how you've maintained your amateur mindset while achieving professional-level success."

@Nodoka
"Hee hee. Am I a girlfriend you can be proud of?"

@Ichinari
"Almost too much so."

We banter back and forth like old times; although now it's alcohol we're drinking, rather than juice.

@Nodoka
"Thank you, Senpai."

@Nodoka
"By becoming my boyfriend, and collaborating with me, you've made both my dreams come true."

Her cheeks are slightly flushed with intoxication as she smiles blissfully.

She really has matured...

Traces of her past self linger in her smile, even as it hits me again how much she's grown as a woman.

@Ichinari
"It's still too early to thank me for either of those."

@Ichinari
"I've still gotta prove myself in both respects."

@Ichinari
"I'll do my best not to let you down."

@Nodoka
"Hee hee. Same here."

@Nodoka
"I want to keep showing you how cool I am."

We share a chuckle as we clink our classes together again.

@Ichinari
"By the way, what kind of story are you planning around this theme of 'dreams'?"

@Nodoka
"Let's save that for the day♪"

@Nodoka
"I'll do my best to make it something that'll blow your mind♪"

@Ichinari
"Okay, then I'll be looking forward to it."

@Nodoka
"Yes, please do♪"

@Owner
"Apologies for the wait."

@Owner
"One carpaccio, one pasta of the day, and one cheese risotto."

@Nodoka
"Oh, the food's here."

@Nodoka
"We can keep talking while we eat."

@Ichinari
"Right, we still have a lot to work out."

@Nodoka
"Yep, so let's combine the real good meal with a real good meeting♪"

Our dōjinshi discussions go late into the night as we enjoy our meal together.

@Nodoka
"Mm, here we are~♪"

@Nodoka
"I'm glad the weather's held up for us this time, too~♪"

Alighting from the taxi at the familiar spot, Nodoka stretches her arms up toward the clear blue sky.

@Ichinari
"There aren't as many people lining up as there were at the last event."

@Nodoka
"Not all dōjin events are created equal."

@Nodoka
"Some people only go to the big events, while some people come to all of them."

@Ichinari
"I see. So that's how it is, huh."

Nodding, I look out over the crowd, which is far sparser than the throngs at Comica.

@Ichinari
"Is the lack of people gonna be a problem...?"

I'd left everything to do with the printing to Nodoka, so...

If she ends up in the red because of me, I'll seriously wanna die.

@Nodoka
"Hee hee. You worried about sales?"

@Nodoka
"It'll be fine; I did plenty of PR, and the responses on social media were pretty good."

@Ichinari
"I sure hope you're right..."

@Ichinari
"But when I think about the day my anthology went on sale... Ugh, my stomach hurts."

When it comes to commercial sales, print numbers and pre-orders mean you have a pretty good idea of how it's going to do even before release.

But in the dōjin world, it all comes down to what happens on the day, so you really have no way to tell.

When I imagine us not selling a single copy...

@Nodoka
"Ahaha, you're such a worrywort."

@Nodoka
"I've had plenty of requests from dōjin retailers to stock it afterward."

@Nodoka
"Trust me—I have experience. We'll be fine♪"

@Nodoka
"Besides, you have me right here with you, remember?"

@Ichinari
"Nodoka..."

She hugs my arm comfortingly.

@Nodoka
"Although it's kinda cute to see you all nervous like this. Hee hee♪"

@Ichinari
"...You're right."

@Ichinari
"I've come this far, so now I've just gotta man up."

@Ichinari
"I don't wanna look lame in front of you."

@Ichinari
"...Although I guess it's a bit late for that now."

@Nodoka
"Hee hee. That's not true."

@Nodoka
"You know, there's nothing better than knowing I've given my readers enjoyment, but... "

@Nodoka
"Just being able to come to an event like this with you is a dream come true."

@Nodoka
"That alone has me so happy, I don't even have to room to worry about sales and stuff. Hee hee♪"

@Ichinari
"Nodoka..."

Nodoka smiles happily, then pokes her tongue out in her usual impish way.

Seeing her acting the same as usual is incredibly reassuring.

@Ichinari
"Yeah. We've done all we can do, so..."

@Ichinari
"Now all that's left is for us to enjoy the event."

@Nodoka
"Yep. Let's treat this as a date~♪"

@Ichinari
"I-I'm not sure Nagomi-sensei's fans should catch her on a date..."

The risky idea sends a shiver down my spine as we walk into the Egg Sight building.

@Nodoka
"Our booth will be over here today."

@Nodoka
"Looks like all the books arrived without any issues~♪"

@Ichinari
"Yeah, they're all here alright..."

Staring at the tower of boxes—enough to construct a small cardboard house—I find myself lost for words.

This looks like double the amount we had for Comica...

@Ichinari
"Nodoka-san?"

@Ichinari
"Don't you think...you might have over-ordered..."

@Nodoka
"Oh, no, Senpai."

@Nodoka
"I ordered reprints of some of my previous issues, too."

@Nodoka
"People were requesting them, so I figured this would be a good amount."

@Nodoka
"Worst comes to worst, the staff from the dōjin shop will come collect the leftovers."

@Ichinari
"R-Right... I see..."

I guess...that makes sense? But still, this amount...

I know we sold several thousand copies at Comica, but... Is this for real?

@Ichinari
"So how many of these contain our collab dōjin...?"

@Nodoka
"About half."

@Ichinari
"H-Half..."

@Ichinari
"I...see..."

Well, we can't change the fact that we already ordered several thousand copies.

And if Nodoka says we'll be fine, then I'm sure we will be...

I nod blankly at Nodoka, who seems way too indifferent to this whole situation.

@Nodoka
"More importantly, take a look at this, Senpai♪"

@Nodoka
"The colors came out so vibrantly. It looks amazing~!"

@Nodoka
"This is our first joint creation, Senpai. Tee hee♪"

I take the freshly-printed book from Nodoka.

@Ichinari
"Wow, it really has turned out nicely."

Bubbling up inside me I feel the same joy as when I'd first held my own comic in my hands.

It's only now it's physically here that I feel like, "Yes, I made this!"

@Ichinari
"Can I read your section now?"

@Nodoka
"Yep, of course♪"

@Nodoka
"Although I'm nervous..."

She fidgets awkwardly as I open the cover; internally, I'm vibrating with excitement, too.

@Ichinari
"Oh, so you went with a club setting."

@Ichinari
"Huh~ The characters are a guy and a younger girl in manga club..."

@Ichinari
"And they're the only two in the club..."

@Ichinari
"...Hang on."

@Ichinari
"..."

@Ichinari
"Um... This is..."

@Ichinari
"Um, Nodoka-san?"

@Ichinari
"This setting and these backgrounds are...real familiar..."

@Nodoka
"Hee hee, are they now?"

@Nodoka
"But it's my own original creation, based on the theme of 'dreams'~♪"

Averting her gaze bashfully, she twists her fingers together in front of her chest.

In the story, the senpai (me) pushes the younger girl (Nodoka) down in the club room after school.

...As to be expected of Nagomi-sensei, it's top-tier filth.

@Nodoka
"So, what do you think of my dream?"

@Ichinari
"It is, to put it lightly, the best thing ever."

@Ichinari
"I think I'll need to take this with me to enjoy on my own later."

@Nodoka
"Oh, then could you livestream it for me?"

@Nodoka
"I want to see Senpai jerking it to the manga I drew about us...♪"

@Nodoka
"Argh, we've got an event to run, but now you've got my panties all soaking wet, you fiend~♪"

@Ichinari
"Um, we're in public, remember? So just contain yourself, okay?"

@Nodoka
"A-Anyway, I'll go change into my costume♪"

@Nodoka
"I-I might be a while though, just so you know♪ Ngh♪"

She totters off in the direction of the changing rooms.

@Ichinari
"But I guess this is Nodoka's real style, huh..."

Recently she's been mimicking Iori's style, but Nodoka's extreme content is really something else.

@Ichinari
"Was she imagining this back then...?"

I give the book another quick flick through.

@Ichinari
"Damn, Nodoka's work is so hot."

Despite being in public, I'm suddenly super turned on.

My one-eyed trouser snake is already perking up, ready for action—

@"Soggy Panda Staff 1"
"Good morning, Ichineri-sensei!"

@"Soggy Panda Staff 1"
"Looking forward to working with you again today!"

@"Soggy Panda Staff 2"
@"Soggy Panda Staff 3"
@"Soggy Panda Staff 4"
@"Soggy Panda Staff 5"
@"All Soggy Panda Staff"
"Looking forward to working with you!"

@Ichinari
"GOOOOOOD MOOOOOORNING!!!"

@Ichinari
"I'M LOOKING FORWARD TO WORKING WITH YOU ALL TOO!"

@"Soggy Panda Staff 1"
"Hm? Why're you bending over like that? Are you alright?"

@Ichinari
"Oh, er, yeah, just some warmup exercises. I'm not usually on my feet all day, ya know?"

@"Soggy Panda Staff 1"
"Uh-huh..."

I make an exaggerated show of doing squats, making sure to lean forward over my groin.

@Ichinari
"Hokay, warm-up complete. Let's start setting up, shall we?!"

@Ichinari
"Should I open up the boxes and start displaying the books?!"

@"Soggy Panda Staff 1"
"Oh, um, yes. We should start with the books."

@Ichinari
"Understood! I'll get to it!"

The staff are all giving me suspicious looks.

Hoping to smooth things over, I throw myself into the booth prep.

@"Soggy Panda Staff 2"
"This is the end of the line for Soggy Panda!"

@"Soggy Panda Staff 3"
"This is the end of the line! Please line up here for Soggy Panda!"

@Nodoka
"Here you go, one copy of our new collaboration dōjin. Thank you~♪"

@Nodoka
"This plus the new release is 2000 yen in total♪"

@Nodoka
"The previous releases will be on sale again later, so feel free to pick them up later♪"

@Ichinari
"Nodoka—I mean, Nagomi-sensei!"

@Ichinari
"I've opened up another box of the new release and the collab!"

@Nodoka
"Okaaay, thanks♪"

@Nodoka
"Oh, but it looks like we're gonna run out soon, so please open up another one too♪"

@Ichinari
"Huh? O-Okay! I'm on it!"

@"Soggy Panda Staff 4"
"You can take a look at Soggy Panda's catalog here!"

@"Soggy Panda Staff 5"
"Please have your money ready to facilitate a smooth transaction!"

@"Soggy Panda Staff 6"
"Copies of the latest and past releases are still available!"

Thirty minutes after the start of the event, and the line at our booth is already so long I can't see the end.

@Ichinari
"While you can't argue that there are less visitors overall than to Comica..."

@Ichinari
"...when it comes to the opening rush, this event might have Comica beat?!"

A huge wave of customers is pressing down on us.

Frantically tearing open a new box, I replenish the supply of books.

@Nodoka
"See, didn't I tell you there was nothing to worry about?"

@Nodoka
"Our collab is selling just as fast as my circle's lastest publication~♪"

@Ichinari
"Y-Yeah, so it is..."

@Ichinari
"It feels like every time I open a new box, it's already empty."

There's still a solid wall of boxes left, but if we keep going at this rate, it'll be leveled in no time.

Even as we're having this conversation, the books are flying off the table.

@Nodoka
"The collab dōjin and new release are limited to five per person♪"

@Nodoka
"Five of each? Yaaay, thank you so much~♪"

@Nodoka
"Sorry, if you'd like me to sign it, could you please come back when we're less busy?"

I keep replenishing the supply in front of Nodoka as she serves everyone with a smile.

Wow, people even want her autograph... It's seriously amazing watching her at events like this.

Every time, I fall in love with her all over again. She's just so cool!

@Nodoka
"With the amount we've sold, we should be able to check out plenty of reactions on social media."

@Nodoka
"I'm super duper confident the collab will receive positive reviews♪"

@Nodoka
"I'm looking forward to it, aren't you, Senpai?♪"

@Ichinari
"Actually I'm kinda terrified..."

@Ichinari
"But equally excited too, I guess."

@Nodoka
"Yes♪ Let's do some egosurfing together when we get home~♪"

@"Female Customer"
"Excuse me. Three copies each of the new release, and the collaboration dōjin."

@Nodoka
"Okaaay, that'll be 6000 yen♪"

@Nodoka
"I'm looking forward to hearing your opinions~♪"

@Nodoka
"Great work, Senpai♪"

@Nodoka
"I brought us some cold drinks."

@Nodoka
"Let's take our break now."

@Ichinari
"Thanks, Nodoka."

@Ichinari
"You're a lifesaver."

We step back further behind the booth, and I look down at my phone as I take a long drink of the tea she brought.

@Ichinari
"The event's already been going for two hours, huh."

I'm shocked—the time really has flown by.

While it's not as packed as at the beginning, there's still a line of customers in front of the booth.

@Nodoka
"It's been even busier than I expected."

@Nodoka
"And it's all thanks to our collaboration."

@Ichinari
"No way. It's all because you were posting about how this was your best work ever."

@Ichinari
"I mean, hearing that it's Nagomi-sensei's best work, I'd be running out to buy it, too."

@Nodoka
"That's not true, Senpai."

@Nodoka
"No matter how hard I shilled it..."

@Nodoka
"...the book wouldn't sell if it wasn't good, you know?"

@Nodoka
"This may be an amateur scene, but the fans have standards."

@Nodoka
"So please have more confidence in yourself, Senpai."

She smiles at me.

@Ichinari
"Well, if you say so..."

I gaze out from behind the wall of boxes at the line of customers.

@Author
"Is Nagomi-sensei around?"

@Nodoka
"Oh, Musabi-sensei! Long time no see!"

@Nodoka
"Senpai, my friend's come over to say hi, so I'm just going to chat for a bit."

@Nodoka
"No one will disturb you behind these boxes, so please take all the rest you need."

@Nodoka
"Musabi-sensei, it's been too long! This is our latest publication. Here, it's on the house~♪"

@Ichinari
"Huh, so she has friends in the dōjin world..."

Well of course she does—she's a best-seller AND a cutie.

Isn't this Musabi-sensei also an author in a big circle like hers?

So that author's also a woman around the same age as Nodoka, huh...

@Ichinari
"The dōjin world truly is a meritocracy, huh."

My eyes are being opened again today.

@Male Artist
"Hey, Nagomi-chan. It's been ages! I didn't know you'd be here today."

@Male Artist
"This is my new—"

@Nodoka
"I'm sorry, I'm just in the middle of something."

@Nodoka
"Oh, here's a copy of our latest release. Bye~"

@Male Artist
"Uh, hey—!"

@Male Artist
"..."

@Ichinari
"Yup. That's my girl."

She deals with the man with a perfectly frosty demeanor.

I do feel a bit bad for him as he trudges off, but what can ya do.

I'd better let her know she did good later. Yep.

@Ichinari
"She's really got all sorts coming to see her."

From fellow dōjin artists to business people, it's been a constant stream of visitors.

I can see people around the booth waiting their turn to greet her.

Being a popular dōjin artist seems pretty stressful—you've gotta be good with people.

@Female Customer
"Um, sorry, I know you're busy, but..."

@Female Customer
"Is Ichineri-sensei here today?"

@Ichinari
"Oh, I'm Ichineri..."

@Ichinari
"Um... C-Can I help you with something?"

Being asked for specifically has caught me off-guard.

The one doing the asking is a cute girl who looks to be a little younger than me.

A smile immediately blooms across her face, and she leans forward eagerly.

@Female Customer
"You're Ichineri-sensei?!"

@Female Customer
"I heard that you were debuting a collaboration with Nagomi-sensei today, so..."

@Female Customer
"I thought maybe you'd be here at the booth, too!"

@Ichinari
"Y-Yeah... I'm here helping out..."

Taken aback by her fervor, I force an awkward smile to my face as I nod.

@Female Customer
"I buy every magazine issue you appear in!"

@Female Customer
"I preordered your comic before it came out too, and I've picked up your collaboration dōjin today!"

@Female Customer
"Um, i-if you wouldn't mind...do you think you could sign your comic for me?!"

@Ichinari
"Huh? Me?!"

@Female Customer
"Yes! I'm a huge fan of yours!"

I take the book and sharpie she thrusts at me.

@Ichinari
"Um..."

@Ichinari
"Sorry, I don't really have an autograph or anything..."

@Ichinari
"I could just write my name, if that's okay...?"

@Female Customer
"Would you?! I'd be sooo happy if you did!"

@Female Customer
"If you could just write your name on the inside cover, that'd be plenty!"

@Female Customer
"Or even on the cover would be fine! I have two more first edition copies at home anyway!"

@Ichinari
"Huh? Two more?"

@Ichinari
"You mean, you bought it three times?"

@Female Customer
"Well as a fan, it's the least I could do♪"

@Ichinari
"Are you for real...?"

I mean, I get what it's like to be a fan, too.

But now, being on the receiving end of that adoration, it somehow doesn't feel real.

Feeling like a fraud, I hesitantly sign the comic.

@Ichinari
"Er, sorry..."

@Ichinari
"I'm not used to writing my own name..."

@Ichinari
"So it came out kind of uneven..."

@Female Customer
"No, no, not at all! I'm just so happy to get your autograph!"

@Female Customer
"Plus it's kinda cute how unused to all this you are♪"

@Female Customer
"Oh, I'm sorry, it's really rude to call a guy cute, isn't it...!"

@Ichinari
"Oh, no, I'm not offended at all!"

@Ichinari
"It's just this is my first time, so, um..."

@Ichinari
"I'm really, really happy."

Feeling incredibly awkward, I hand the signed comic back to her.

@Female Customer
"I know it was a sudden request, so thank you so much for being so willing to oblige!"

@Female Customer
"I can't wait to read the new dōjinshi! I'll post my thoughts online!"

@Female Customer
"Thank you! Bye!"

She keeps turning back to smile and bow as I watch her go.

Once she's out of sight, I slump weakly down behind the wall of boxes.

@Ichinari
"...Hahaha."

@Ichinari
"I have...fans..."

@Ichinari
"Drawing manga is so worth it."

Although I'd been completely flustered by the suddenness...

It's all starting to sink in now, and I'm overjoyed.

@Nodoka
"Senpaiii~?"

@Nodoka
"You seemed like you were realllly enjoying talking with that fangirl of yours~"

@Ichinari
"N-Nodoka?!"

@Ichinari
"Uh, n-no, it wasn't like that...!"

@Nodoka
"Sheesh, I look away for one second and this is what you get up to~"

@Nodoka
"I was RIGHT HERE and yet there you were making googly eyes at her~"

@Ichinari
"No, no, no! There were no googly eyes! I swear!"

@Ichinari
"If it looked like that, then I'm sorry! But it wasn't like that!"

@Nodoka
"Hee hee, don't worry, I know♪ I'm just messing with you♪"

@Nodoka
"You're so cute when you get all flustered, Senpai~♪ Hee hee♪"

@Ichinari
"Hey..."

The tension drains out of me as she giggles.

@Nodoka
"I told you, didn't I?"

@Nodoka
"You have fans, Senpai."

@Nodoka
"Even if they don't follow you online or whatever, there are still people watching out for you."

@Nodoka
"Besides, did you really think an artist endorsed by me, Iori-san, and Akira-san would have no fans?"

As she speaks she sits down beside me and lays her head on my shoulder.

@Ichinari
"Yeah... I just can't believe I really have fans."

@Ichinari
"I've never had anyone approach me before, so I was more shocked than pleased."

@Nodoka
"Like I told you before, being able to interact with fans this way is one of the best things about the amateur scene."

@Nodoka
"Although I don't want you taking on any more wives, you hear me?"

@Nodoka
"You have enough with Iori-san and Akira-san."

@Nodoka
"They're the ones who truly understand you."

@Nodoka
"I know that you love them, and I love them too."

@Nodoka
"But those people who only know you on the surface..."

@Nodoka
"Honestly, I don't want you eyeing up those other women."

@Ichinari
"Nodoka..."

@Ichinari
"Yeah, I understand."

@Ichinari
"I was relieved when you blew off that guy, too."

@Ichinari
"And I'm already taking advantage of your goodwill by dating all of you at once."

@Ichinari
"Sorry for making you anxious. I'll be more careful from now on."

I pet her head then take her hand in mine as I reassure her.

@Nodoka
"Ooh~ So you get jealous too, Senpai?"

@Nodoka
"I'm kinda surprised—I didn't take you for the type."

@Nodoka
"You're sooo cute, Senpai~♪ Pet pet~♪"

This time Nodoka's the one petting me.

@Nodoka
"I probably don't even need to say this, but I have no interest in any man but you."

@Nodoka
"I already have someone who truly knows me, and loves me for who I am; and that's enough for me♪ Tee hee~♪"

Smiling bashfully, she puts her hands to my cheeks and smushes my face.

Then she looks up at me mischievously though her lashes.

@Nodoka
"Now, as your punishment for ogling another woman..."

@Nodoka
"Would you give me a kiss?"

@Ichinari
"A kiss?"

@Ichinari
"Uh, here?"

@Nodoka
"Yep. Right here."

I look around.

Sure, we're behind the box wall, so we're hidden from view, but...

There's tons of people walking around the venue, and the staff are right there...

@Ichinari
"N-No, nope, no way!"

@Ichinari
"Nuh-uh! We can't do that!"

@Ichinari
"We don't know who might be watching, and if one of your fans catches us...!"

Nodoka grins at my flustered state and leans in closer.

@Nodoka
"Aha, you're so cute when you're freaking out♪"

@Nodoka
"So, what's it going to be?"

@Nodoka
"Are you going to give me what I want?"

@Nodoka
"Because if you don't, you'll be in my bad books. Hee hee♪"

She traces a slim finger down my cheek, clearly reveling in this.

Uh-oh. Doesn't look like she's gonna back down.

Screwing up my resolve, I lean in toward her (while making sure we're hidden by the boxes).

@Ichinari
"Nodoka..."

@Nodoka
"Mm... Senpai... Mwah♪"

@Nodoka
"Hee hee♪ You're such a sweet, obedient boy."

@Nodoka
"No one can see us here unless they're purposely peeking♪"

