#start|Dōjin Artist Dream

@Nodoka
"I've had this fantasy about you and me..."

@Nodoka
"...doing it in a place just like this...♪"

@Ichinari
"N-Nodoka? Doing it here would be..."

@Nodoka
"No one can see us behind these boxes... Right?"

Her eyes are hazy, as she presses herself against me.

@Nodoka
"We just have to be quiet."

@Nodoka
"You can't make a sound, okay? Hee hee♪"

Murmuring into my ear in a sweet, low tone...

...she slowly straddles me.

