#start|Ichinari's Decision

@Iori
"Haa~♪ I keep looking at it, and it's like it gets prettier every time♪"

@Iori
"I can't believe I got an engagement ring from Ichinari~♪ Tee hee~♪"

@Nodoka
"I toootally get what you're saying, Iori-san~♪"

@Nodoka
"Every time I look down at my left hand I get all sappy, and I can't concentrate on work~♪ Tee hee~♪"

@Akira
"I'll have to explain things to the editor-in-chief, and our business partners~♪"

@Akira
"I wonder if I'll get away with just a little scolding when I tell them we're getting married~♪ Tee hee~♪"

It's the next day.

All morning, the three of them have been staring at their rings with stars in their eyes.

@Ichinari
"I'm really glad you're all so happy with them."

@Ichinari
"I'll get you even better rings for the wedding."

@Ichinari
"I should have gotten paid for my comic sales by then."

@Iori
"Hee hee. You know price isn't an issue."

@Iori
"The value is in it being the only ring in the world given to me by Ichinari."

@Nodoka
"She's right, you know? To us, these are the best rings in the whole wide world."

@Akira
"Exactly, exactly! So don't say crude thing like that, got it?"

@Ichinari
"I see. Yeah, you're right. Sorry."

They all have the biggest smiles I've ever seen on their faces.

I'm so happy that there's no room for embarrassment; I apologize genuinely.

@Ichinari
"You really are the best girlfriends—no, wives—a guy could ask for."

@Ichinari
"I'm gonna keep trying even harder."

@Ichinari
"So please take care of me, now and forever."

@Iori
"Yes, of course."

@Iori
"And we'll be counting on you for our whole lives, too."

@Nodoka
"Hee hee. He's definitely not a loser anymore, is he?"

@Akira
"Still, he was pretty cute back when he was all pathetic, ahaha!"

@Ichinari
"I'll take that as a compliment."

There's nothing but warm fuzzy feelings between us.

As their laughing voices reverberate around the room...

...my heart is so filled with joy it almost aches.

@Iori
"But this place might be a little small for us, once we're married."

@Nodoka
"Right! Even with just one child each, we'll be a family of seven."

@Akira
"I think I want two or three kids."

@Ichinari
"If you have three each, we could form a whole baseball team..."

@Akira
"Don't you go getting snarky when you pumped all those gallons of your little swimmers into us!"

@Nodoka
"We might already have three little ones inside us now~♪"

@Iori
"Then shall we find a new place to live?"

@Nodoka
"Oh, that's a great idea♪"

@Nodoka
"How about a biiig detached place out in the suburbs?"

@Nodoka
"With our jobs, we're not bound to one particular place~♪"

@Akira
"I like it! Yeah, I'm in!"

@Akira
"I wanna get a big doggo!"

@Iori
"Oh, I've always wanted a pet cat♪"

@Nodoka
"It'd be so nice having a dog and cat being buddies together♪"

@Nodoka
"I hear that if you get the dog first, they'll get along~♪"

@Ichinari
"Yeah, that does sound fun."

My waifus are all working themselves up with excitement.

I nod along as I imagine our perfect happy family life.

Just then, a more realistic thought pops into my head, bringing me back down to earth.

@Ichinari
"But, you know, now that I think about it..."

@Ichinari
"Polygamy is illegal in Japan, isn't it?"

@Iori
"Well in that case, we just don't make it official, right?"

@Nodoka
"And if worst comes to worst, we can just move somewhere where it IS legal♪"

@Akira
"What the hell're you doing bringing something like that up when it's already way too late~♪"

@Ichinari
"Damn, you girls are all as dependable as ever."

They easily put paid to my doubts.

But when I look into their strong, smiling faces...

...I can't help but chuckle.

@Ichinari
"Yeah, you're right."

@Ichinari
"Our happiness is our own, and it can take whatever form we like."

@Iori
"Exactly."

@Nodoka
"Otherwise we'd never even have considered a polyamorous relationship."

@Akira
"If this is what makes us happy, then it's all good♪"

@Akira
"That's how we do things, isn't it?"

@Ichinari
"You're exactly right."

@Ichinari
"Okay, now, first things first. For the sake of our future together..."

@Ichinari
"...Shall we do some work?"

@Iori
"Mm. In order to achieve our new dream."

@Nodoka
"With this group, I'm sure we'll achieve it in no time flat♪"

@Akira
"Well then we'll just have to come up with an even bigger and better dream! Ahaha♪"

We'll create our own unique dreams together.

As our happy voices fill the room...

...I pick up my pen...

...ready to draw my way to our promised future.

